### ISSUE TITLE
Bug: Unexpected space after the section separator

### ISSUE THREAD

**Issue by ifyouseewendy** [nvim-lualine/lualine.nvim#1014]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in existing issues or PRs.

Thanks for making this wonderful plugin ❤️ 

### How to reproduce the problem

<img width="938" alt="Screenshot 2023-04-09 at 6 09 31 PM" src="https://user-images.githubusercontent.com/1019171/230806297-6e55eb37-0c4e-41c2-a450-839286b22ac8.png">

### Expected behaviour

No space after rendering the section parameter in section x, y, z

### Actual behaviour

There is a weird space rendered after the section parameter. 

### Additional information

* OS: MacOS
* NVIM v0.8.1, v0.9.0
* Font: Hack Nerd Font Mono, JetBrainsMono Nerd Font Mono
* iTerm (with builtin-Powerline grayphs enabled)

**Comment by shadmansaleh** [comment]
I can't seem to reproduce it. can you provide a minimal reproduction as suggested in the issue template?

**Comment by ifyouseewendy** [comment]
I guess this more of a problem for non-ascii font rendered in my terminal. I'll close it for now.
