### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Roboticyang** [nvim-lualine/lualine.nvim#1034]
### Self Checks

- [x] I'm using the latest lualine.
- [ ] I didn't find the issue in existing issues or PRs.

### How to reproduce the problem

Today, Barbar and lualine packages have some of the icons as question marks with rectangle box around them. Barbar shows the close button as above symbols. Lualine shows the language server warning/issues/errors as above symbols.

### Additional information
I am currently using mononoski nerd font mono. My Nvim-Tree works okay. And the icons are only partially broken. I tried use packer to remove both barbar and lualine. And reisntalled one of them at a time. The issue persist. The terminal I am using right now is iTerm2. I barely have any modification on the lualine.lua configuration. Its in my repo here:
lua/lualine-config/init.lua
https://github.com/Roboticyang/Nvim_lua_config.git

![image](https://user-images.githubusercontent.com/46727070/235568663-cc8b06eb-5dfb-4303-8ec6-c4c657648a68.png)

**Comment by moshiur-raj** [comment]
I am facing the same problem after updating the nerd fonts today

**Comment by tgw314** [comment]
https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0

It's because there was a breaking change in Nerd Fonts.

**Comment by Roboticyang** [comment]
@tgw314 Thanks alot on the information. I guess, because I used brew to install the font on my macOS, and installed differently on my ubuntu device. I don't have any issue on my ubuntu device so far.

**Comment by rootex-** [comment]
great tool to deal with obsolete symbols: 
https://github.com/loichyan/nerdfix 
waiting for lualine update to fix the issues with outdated symbols

**Comment by Roboticyang** [comment]
@moshiur-raj barbar.nvim has fixed the close button issue already.

**Comment by Roboticyang** [comment]
@yujingyuz Cool! I will keep an eye on the new updated with Nvim packer.
