### ISSUE TITLE
Feat: globalstatus for winbar

### ISSUE THREAD

**Issue by Alyzmal** [nvim-lualine/lualine.nvim#1064]
### Requested feature

A component option for the winbar that would set some equivalent to what "globalstatus = true" does for the statusline

### Motivation

It would allow users to have one singular winbar going across their screen instead of an awkward cut that, to some extent, defeats the purpose of a winbar.

**Comment by shadmansaleh** [comment]
This is not possible to do from plugin space without gross hacks. The global status option only toggles an option implemented in Neovim. There's no such option available for winbar for now. You can make a request for neovim to add it.

**Comment by Alyzmal** [comment]
Okay, good to know. Thanks!
