### ISSUE TITLE
Hello; how to display breadcrumbs? Similar to the effect in vscode.

### ISSUE THREAD

**Issue by whxcode** [nvim-lualine/lualine.nvim#1065]
According to the position of the cursor; it can display the state of the current method and object field.

![image](https://github.com/nvim-lualine/lualine.nvim/assets/44012914/c7642259-e50c-45ad-ad0b-a40c3e7a2a7a)

![image](https://github.com/nvim-lualine/lualine.nvim/assets/44012914/fa5e47c1-e873-472f-a00a-7864261f86da)

**Comment by whxcode** [comment]
I found another way to do it with "lualine" combination

**Comment by NikD0T** [comment]
> I found another way to do it with "lualine" combination

Can you share?

**Comment by winston0410** [comment]
@whxcode What integration did you find at the end?
