### ISSUE TITLE
Bug: bad interaction with another plugin that provides its own statusline

### ISSUE THREAD

**Issue by jyscao** [nvim-lualine/lualine.nvim#1117]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in existing issues or PRs.

### How to reproduce the problem

I rely on this plugin called [vim-ctrlspace](https://github.com/vim-ctrlspace/vim-ctrlspace) to manage my buffers, files, tabs & sessions. This plugin provides its own statusline, which displays its own submodes and other relevant info; for example, the following is the ctrlspace statusline (and its buffer content) showing that it is in its file mode (indicated by the open circle symobl),  the tab number along with number of buffers in the tab (1<sup>3</sup>), and the current buffer (`[keymaps.lua]`):

<img width="1436" alt="image" src="https://github.com/nvim-lualine/lualine.nvim/assets/12605746/e741d4be-dc60-4940-945c-4ec6b163dd26">

I defined the following custom extension and added it to the lualine's `extensions` table with the following blocks:

```lua
local ctrlspace_statusline = {
  sections = { lualine_a = { vim.fn["ctrlspace#util#SetStatusline"]} },
  filetypes = {'ctrlspace'},
}
```
```lua
  extensions = {
    ctrlspace_statusline,
}
```

This does seem to allow lualine to pass control of the statusline rendering to ctrlspace when in the ctrlspace buffer is active. But some unexpected interactions and errors occur.

### Expected behaviour

For ctrlspace to render its own statusline when its activated. Then for lualine to take back control of the statusline when ctrlspace is deactivated.

#### a) not using the extension or disabling lualine for `ctrlspace` filetype

First let me add that not using the custom extension, or simply adding the `ctrlspace` filetype to the `disabled_filetypes` list does not produce the desired behavior either, because in those cases, lualine simply takes over the statusline rendering completely, and gives me something like the following:
<img width="1436" alt="image" src="https://github.com/nvim-lualine/lualine.nvim/assets/12605746/968cd2e0-61f3-4003-9d24-6f7c2a3e26ad">

Where lualine correctly picks up the filetype as `ctrlspace`, with the rest of the statusline providing information about this unmodifiable buffer as if it were an ordinary buffer (editor mode, git branch, text encoding, progress & location), which are not really relevant to ctrlspace.

#### b) using the custom extension shown in the first section (How to reproduce the problem)

On the first invocation of the `CtrlSpace` command, either through the command line or via a mapping like `<C-Space>`, the statusline rendering gets passed to the [`ctrlspace#util#SetStatusline` function](https://github.com/vim-ctrlspace/vim-ctrlspace/blob/38266fba90e5bcc5db026522f5ade0e0e0a9a17f/autoload/ctrlspace/util.vim#L142). But if I try to change ctrlspace's submode then a series of errors occur, with the the following error message block:

```
Error detected while processing ModeChanged Autocommands for "*":
E5108: Error executing lua ...scao/.local/share/nvim/lazy/lualine.nvim/lua/lualine.lua:432: Vim:E5100: Cannot convert given lua table: table should either hav
e a sequence of positive integer keys or contain only string keys
stack traceback:
        [C]: in function 'nvim_win_call'
        ...scao/.local/share/nvim/lazy/lualine.nvim/lua/lualine.lua:432: in function <...scao/.local/share/nvim/lazy/lualine.nvim/lua/lualine.lua:321>
```

being produced multiple times in fact, like so:
<img width="1436" alt="image" src="https://github.com/nvim-lualine/lualine.nvim/assets/12605746/2255e028-c609-4f6d-92f9-4c3a2212c99f">

Once I press `ENTER` enough times and go through all the errors, additional invocations of `CtrlSpace` renders its statusline correctly and as works as expected, including when switching between different submodes. However the problem is the lualine statusline is no longer set at all, with just a completely blank bar being displayed:
<img width="1436" alt="image" src="https://github.com/nvim-lualine/lualine.nvim/assets/12605746/c691c9f0-86a7-44c8-9476-2e138456f939">

`:set statusline?` echos back `  statusline=%#lualine_c_normal#%=`; running `:lua require('lualine').refresh()` can force lualine to reappear, but at this point, it no longer appears to respond correctly to its refresh events, since opening a new split and going to it will cause lualine to disappear again.

lualine after `.refresh()`:
<img width="1436" alt="image" src="https://github.com/nvim-lualine/lualine.nvim/assets/12605746/caf75163-0554-4e3f-ae51-90cbb9ef4f99">

lualine after `.refresh()`, opening new vsplit, and going to the new split:
<img width="1436" alt="image" src="https://github.com/nvim-lualine/lualine.nvim/assets/12605746/fe0eaa42-2372-4767-a99a-2f4ad095e409">

### Minimal config to reproduce the issue

I installed Neovim in a VM, cloned the 2 plugins (& a 3rd colorscheme plugin for better viewing) under `/tmp/nvim-plugins`, then opened Neovim with the following `init.lua`:

```lua
vim.opt.rtp:prepend('/tmp/nvim-plugins/lualine.nvim')
vim.opt.rtp:prepend('/tmp/nvim-plugins/vim-ctrlspace')

-- completely optional: a colorscheme provides better contrast to help see the statusline
vim.opt.rtp:prepend('/tmp/nvim-plugins/onedark.nvim')
require('onedark').load()

require('lualine').setup()
local ctrlspace_statusline = {
  sections = { lualine_a = { vim.fn["ctrlspace#util#SetStatusline"]} },
  filetypes = {'ctrlspace'},
}
require('lualine').setup({extensions = {ctrlspace_statusline}})

vim.g.CtrlSpaceDefaultMappingKey = "<C-space> "         -- sets main CtrlSpace mapping
```

The above is able to fully reproduce the bug reported in this issue.

### Additional information

I understand that this is a somewhat big ask, to help fix an issue related to lualine's interaction with another plugin. Part of me is considering just digging into and trying to fix this myself. But I wanted to see if perhaps the cause of the bug and/or fix might just jump out at you, and if so, if you could even just point me in the right direction on where to dig further, that would likely save me a lot of time and effort.

**Comment by shadmansaleh** [comment]
you can do something like this

```lua
local ctrlspace_statusline = {
 sections = { lualine_c = {'ctrlspace#api#Statusline'} },
 filetypes = {'ctrlspace'},
}
require('lualine').setup({extensions = {ctrlspace_statusline}})
```
actually it's better to get the info you want to display from ctrl-space and display it on lualine. handing over statusline to two different plugins wouldn't work without specific integration on both plugins side.

if you still want something like that you can try hiding lualine on ctrl-space filetye. like set buf enter and exit auto command for crtl-space buffered and hide  and unhide lualine on those events

https://github.com/nvim-lualine/lualine.nvim#disabling-lualine

**Comment by jyscao** [comment]
Your first suggestion works well enough in practice. The only minor inconsistency is that the ctrlspace info doesn't end up being displayed across the whole statusline and gets truncated a bit after the mid-point like this:
<img width="1436" alt="image" src="https://github.com/nvim-lualine/lualine.nvim/assets/12605746/4bd233a8-c999-4863-b1a1-e655146784d0">

And if I use `lualine_x = {'ctrlspace#api#Statusline'}` instead of `lualine_c`, then the same cut-off effect is still present, but occurs on the left side instead, like so:
<img width="1436" alt="image" src="https://github.com/nvim-lualine/lualine.nvim/assets/12605746/e24eb140-301e-4f13-88b2-9b3bb6c288a0">

My wild guess was this might be related to the `always_divide_middle = true` option, so I tried setting that to `false` in the `ctrlspace_statusline` extension, but that doesn't appear to help. Nor does explicitly setting all the other sections (a, b, x, y, z) to empty tables.

Do you know of an easy workaround for that? I'm not looking to have ctrlspace also manage the statusline anymore, since it's really its info that I need, which this approach works plenty well for. If this can't be done easily, then I can totally live with the current display style.

**Comment by jyscao** [comment]
Actually I think I have it figured out. I needed to obtain the ctrlspace statusline segments separately, instead of as a single unit:
```lua
  sections = {
    lualine_c = {'ctrlspace#api#StatuslineModeSegment'},
    lualine_x = {'ctrlspace#api#StatuslineTabSegment'},
  },
```

Would you like me to create a PR and add it to lualine's extensions list? It's not a super popular plugin, but it does have some fairly loyal users.
