### ISSUE TITLE
Diff component not update when I use `<cmd>noa w!<cr>` to save file.

### ISSUE THREAD

**Issue by shy-robin** [nvim-lualine/lualine.nvim#1120]
1. When I use `<cmd>wq<cr>` to save files, the diff component of lualine will update as expect.
2. However, when I use `<cmd>noa w!<cr>` to save files ( this command will prevent auto formatting after saving files), the diff component will not update unless reopen buffer.

**Comment by shadmansaleh** [comment]
Do you know what `noa` does? It's short for `noautocmd` .

It prevents all auto commands from running on the event. Basically neovim doesn't fire the file written event. How is lualine supposed to know you've written the file ¯\_(ツ)_/¯ . Implementing git isn't primary objective of lualine. diff component provides a good basic support for diff if you aren't using any other specific plugin to draw data from. If you have other git based plugins keeping track of git status I recommend using that as source of info for git component. You can checkout the example here https://github.com/nvim-lualine/lualine.nvim/wiki/Component-snippets#using-external-source-for-diff

**Comment by shy-robin** [comment]
@shadmansaleh Thanks for your reply! Using gitsigns for diff helps me, it can update diff component immediately even though I have not saved files.
