### ISSUE TITLE
Bug: require('lualine').hide() doesn't hide winbar with Goyo

### ISSUE THREAD

**Issue by cprn** [nvim-lualine/lualine.nvim#1122]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in existing issues or PRs.

### How to reproduce the problem

I apologize, it's not an isolated issue - it only happens when I use Goyo with Lualine but I'm asking for help because I can't put my finger on it. I tried to make it as easy to analyze as possible.

1. use provided `init.lua`
1. open any plain text file and call `:Goyo`.

### Expected behaviour
Both statusline and winbar gone.

### Actual behaviour
Only statusline gone.

### Minimal config to reproduce the issue

```lua
-- { 1. install some add-on manager (I'm using Lazy):
local lazypath = vim.fn.stdpath 'data' .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system {
        'git',
        'clone',
        '--filter=blob:none',
        'https://github.com/folke/lazy.nvim.git',
        '--branch=stable',
        lazypath,
    }
end
vim.opt.rtp:prepend(lazypath)
-- }

-- { 2. install Goyo, Limeligth, Lualine and configure some winbar
require('lazy').setup({
    {'junegunn/limelight.vim'},
    {'junegunn/goyo.vim'},
    {'nvim-lualine/lualine.nvim', dependencies = {'nvim-tree/nvim-web-devicons', 'SmiteshP/nvim-navic'}, opts = {
        options = {theme = 'onedark', disabled_filetypes = {statusline = {'NvimTree'}}},
        winbar = {lualine_c = {{'filetype', icon_only = true}, 'navic'}}
    }},
}, {})
-- }

-- { 3. add Goyo config to autohide lualine
local goyo_group = vim.api.nvim_create_augroup('GoyoGroup', {clear = true})
vim.api.nvim_create_autocmd('User', {
    desc = 'Enable LimeLight on GoYo enter',
    group = goyo_group,
    pattern = 'GoyoEnter',
    command = 'Limelight|lua require("lualine").hide()',
})
vim.api.nvim_create_autocmd('User', {
    desc = 'Disable LimeLight on GoYo leave',
    group = goyo_group,
    pattern = 'GoyoLeave',
    command = 'Limelight!|lua require("lualine").hide {unhide=true}',
})
-- }
```

### Additional information
Again, sorry it's not an isolated case - I'll totally get it if you just close it. I'm having trouble isolating what's the root cause. I'm guessing it has something to do with Goyo using two extra vertical buffers to center the main buffer but I can't figure it out.

Screenshot:
![image](https://github.com/nvim-lualine/lualine.nvim/assets/6132708/8aa010dc-7eeb-4c99-ba47-b46f5a0b5296)

**Comment by Sam-programs** [comment]
you also need to set winbar to nothing with goyo for some reason?
```lua
         vim.api.nvim_create_autocmd('User', {
            desc = 'Enable LimeLight on GoYo enter',
            group = goyo_group,
            pattern = 'GoyoEnter',
            callback = function()
               require("lualine").hide()
               vim.o.winbar = ''
               -- also hide tabline
               -- vim.o.showtabline = 0
               vim.cmd('Limelight')
            end,
         })
         vim.api.nvim_create_autocmd('User', {
            desc = 'Disable LimeLight on GoYo leave',
            group = goyo_group,
            pattern = 'GoyoLeave',
            callback = function()
               -- reshow tabline
               -- vim.o.showtabline = 2
               require("lualine").hide({unhide = true})
               vim.cmd('Limelight!')
            end,
         })
```

**Comment by cprn** [comment]
Yup, when I unset `vim.o.winbar` it works - thank you very much!

My issue is solved but can you tell if it's a bug in Lualine or Goyo? Should I leave the ticket open?

**Comment by Sam-programs** [comment]
I think it might be intended in Goyo to allow a winbar, because it might help with locating scopes with something like [novic](https://github.com/SmiteshP/nvim-navic).
U can ask if it's intended there in an issue if u want.

I am also not really sure why lualine doesn't unset winbar.

**Comment by Sam-programs** [comment]
I think i found the issue lualine doesn't reset an option,if it didn't set it before.
And the global winbar option is set implicitly whenever lualine sets the local option.

If i understand what is happening correctly:
The global winbar stays in goyo's new tab.
lualine doesn't reset the global winbar because it doesn't know that set it before by setting the window local option in the other tab.

**Comment by shadmansaleh** [comment]
We are resetting the options that we set when lualine is instructed to hide itself. I don't think we should be touching options that we haven't set. This issue should probably be fixed on goyos side. I'm  also not really sure why it's happening though.

**Comment by cprn** [comment]
Not reopening this, because I solved it with autocommand long time ago, but I think my issue was misunderstood. The core of the problem was:

1. Lualine handles `winbar` content, if configured to do so
1. `require('lualine').hide()` stops updating `winbar` content, as it should
1. but it doesn't clean it, so winbar remains visible with whatever it showed last
