### ISSUE TITLE
NvimTree disable filetype do not work

### ISSUE THREAD

**Issue by zrchx** [nvim-lualine/lualine.nvim#1128]
###  THIS IS NOT A ISSUE IS A SOLUTION FOR A SPECIFIC ONE

Well i use LuaLine and Neovim lasted version in Arch Linux and i dont wanna see the buffer of NvimTree so i tried and search around the wiki and issues but nothing work so there is my solution for people whit the same problem

this work in the filename fmt option so you might need to adapt to the other modules

```lua
function ()
  local filename = vim.fn.fnamemodify(vim.api.nvim_buf_get_name(0), ":.")
  if filename == "NvimTree_1" then return "" end
  return filename
end
```

**Comment by whoop-t** [comment]
Bump I can seem to get this working either

```
        options = {
          disabled_filetypes = {
            statusline = {
              "dashboard",
              "aerial",
              "dapui_.",
              "neo%-tree",
              "NvimTree",
            },
          },
...
        },

```
