### ISSUE TITLE
Feat: Custom filename function for `buffers` component

### ISSUE THREAD

**Issue by cpmsmith** [nvim-lualine/lualine.nvim#1132]
### Requested feature

Add an option to the `buffers` component's configuration which allows the user to provide a function which gets used in [`Buffer:name()`](https://github.com/nvim-lualine/lualine.nvim/blob/2248ef254d0a1488a72041cfb45ca9caada6d994/lua/lualine/components/buffers/buffer.lua#L141), allowing for arbitrary customization of how buffers' names are displayed.

### Motivation

The thing I actually want is something resembling [`airline#extensions#tabline#formatter`'s `unique_tail_improved`](https://github.com/vim-airline/vim-airline/blob/3b9e149e19ed58dee66e4842626751e329e1bd96/doc/airline.txt#L1282) option. For instance, if I'm working on a JavaScript project and I have two buffers open to files named `index.js`, I want to include the names of their directories so I can tell them apart. However, there are already two options for customizing the display of buffer filenames (`show_filename_only` and `hide_filename_extension`), and the number of options in Airline's version suggests that people may have some very detailed opinions about how to do this. A custom function option would make it possible for me to set up my special snowflake version of things without lualine needing to actively support it.

**Comment by Sam-programs** [comment]
every component has an fmt option.
in this case fmt takes the buffer name without any symbols.
and the symbols get appened to the return value of fmt.

**Comment by cpmsmith** [comment]
Oh, well, that's pretty much exactly what I wanted. Thanks @Sam-programs! I wonder if the docs should be a little more explicit about that behaviour, since I managed not to notice it, and even looking at the docs for the general `fmt` option I'm not sure I would've put it together on my own. Still, closing!

**Comment by Sam-programs** [comment]
i think the most confusing part is fmt being in [component-options](https://github.com/nvim-lualine/lualine.nvim#component-options) but not [global-options](https://github.com/nvim-lualine/lualine.nvim#global-options)
