### ISSUE TITLE
Feat: Wiki update

### ISSUE THREAD

**Issue by AndreM222** [nvim-lualine/lualine.nvim#1167]
### Requested feature

I just created my first plugin which is meant to add status icons for copilot.lua
Its [copilot-lualine](https://github.com/AndreM222/copilot-lualine)

### Motivation

While I was trying to setup copilot in my nvim I struggled with knowing the current status of copilot.
I created this plugin mostly for me but if anyone else wants to use it I want to keep it available for everyone.

**Comment by shadmansaleh** [comment]
Wiki updated https://github.com/nvim-lualine/lualine.nvim/wiki/Plugins
