### ISSUE TITLE
Feat: Merging one of the PRs that add support for base16-vim colorschemes

### ISSUE THREAD

**Issue by titaniumtraveler** [nvim-lualine/lualine.nvim#1187]
Since around April last year there have been two PRs to add [base16-vim](https://github.com/tinted-theming/base16-vim) support to lualine.

One by @JamyGolden (#1006) and one by me (#1081) in reaction to this issue #859. \
(I didn't think to look for another PR solving the issue at that time.)

I'm currently using a custom colorscheme to add the same functionality to my config, (which basically contains the same code as my PR), but it would still be nice if lualine had builtin support for it.

Both PRs contain basically the same functionality, so it doesn't really matter, which one is merged.

**Comment by AntoinePrv** [comment]
I'm also writing https://github.com/nvim-lualine/lualine.nvim/pull/1194 in this Context, since passing the cterm code from outside does change the values.
