### ISSUE TITLE
Bug: Two status lines appear when using nvim -p[x] and switching tabs

### ISSUE THREAD

**Issue by lioil987** [nvim-lualine/lualine.nvim#1200]
### Self Checks

- [x] I'm using the latest lualine.
- [X] I didn't find the issue in existing issues or PRs.

**Comment by lioil987** [comment]
![Screenshot from 2024-02-29 22-17-09](https://github.com/nvim-lualine/lualine.nvim/assets/137775894/395a4520-5daf-429f-8ff1-85c4f1e25aee)

**Comment by lioil987** [comment]
i found this problem with other plugin too   but i like lualine so ... i am saying the issue here  excuse me XD

**Comment by ParisTheProgrammer** [comment]
I have this exact same issue. Just switched to Lazy Vim since Lunar Vim maintainer vanished. Thought it was an issue with LazyVim default config but it doesn’t appear that’s the case

**Comment by ParisTheProgrammer** [comment]
@lioil987 are you using LazyVim by any chance? If you are, are you using the Noice plugin?

**Comment by jerrykan** [comment]
@ParisTheProgrammer I don't use LazyVim, but I do have noice installed. I tried disabling noice and the problem went away. I also tried disabling lualine and re-enabling noice and the problem came back. So it seems like the problem is with noice and not lualine.

**Comment by lioil987** [comment]
Thank you for your attention. It seems the issue lies in the noice, i removed that for preventing me from fully reading the message. However, I've retained this page. but I'm grateful for your assistance.

**Comment by lioil987** [comment]
sorry i am new in git , if i close or open or...   something is not intentional

**Comment by lioil987** [comment]
and please see my projects and say your opinion
