### ISSUE TITLE
Bug: (suggestion): remove default filename in command bar when there is one displayed in lualine

### ISSUE THREAD

**Issue by qbnil** [nvim-lualine/lualine.nvim#1205]
It's rather a suggestion than a bug, i didn't really figure this out, i displayed the file name in the lualine like that but there is also a default one: 
![image](https://github.com/nvim-lualine/lualine.nvim/assets/130576530/cdd3dc4d-3e30-451d-bbb8-93e8dbbc49d5)
i need to just leave the one i added, i tried doing vim.opt.statusline = "" to hide it completely, but this didn't work...

**Comment by qbnil** [comment]
Fixed this

**Comment by franckrasolo** [comment]
@qbnil How did you fix it?

**Comment by franckrasolo** [comment]
I noticed this while tweaking lualine as a LazyVim user, however I'm unsure this is an issue specific to to how LazyVim configures lualine [by default](https://www.lazyvim.org/plugins/ui#lualinenvim).

For posterity, I'll share that I fixed it by removing the last element of section 'c' table in my configuration of lualine:
```
  config = function(_, opts)
    table.remove(opts.sections.lualine_c)
    require("lualine").setup(opts)
  end
```

Hope this helps other folks out there! ❤️
