### ISSUE TITLE
docs: typo on wiki

### ISSUE THREAD

**Issue by mikesmithgh** [nvim-lualine/lualine.nvim#1224]
I noticed a couple of typos on the Wiki page: https://github.com/nvim-lualine/lualine.nvim/wiki/Plugins

`peovide` should be replaced with `provide`

![typos](https://github.com/nvim-lualine/lualine.nvim/assets/10135646/356f3cab-2653-4a07-a66a-363d8e2c8cfa)

**Comment by shadmansaleh** [comment]
Fixed. Thanks for pointing out.
