### ISSUE TITLE
Feat: Optimize counting of diagnostics with new `vim.diagnostic.count()` (nvim 0.10+) 

### ISSUE THREAD

**Issue by camoz** [nvim-lualine/lualine.nvim#1239]
### Requested feature

Optimize counting of diagnostics with new function [`vim.diagnostic.count()`](https://neovim.io/doc/user/diagnostic.html#vim.diagnostic.count()) (nvim 0.10+) where possible.

This is more efficient and thus preferred over using `vim.diagnostic.get()` for counting diagnostics manually (as it is currently done in lualine), according to https://neovim.io/doc/user/news-0.10.html

### Motivation

Performance improvement.

**Comment by shadmansaleh** [comment]
resolved in https://github.com/nvim-lualine/lualine.nvim/pull/1268
