### ISSUE TITLE
Feat: branch to show string instead of disabling

### ISSUE THREAD

**Issue by daUnknownCoder** [nvim-lualine/lualine.nvim#1257]
### Requested feature

if im not in a git repo, the branch is just disabled

i came with this workaround:

```lua
        lualine_b = {
          {
            function()
               local is_git = vim.fn.system("git rev-parse --is-inside-work-tree")
               if is_git and vim.v.shell_error == 0 then
                 return vim.fn.system("git branch --show-current | tr -d '\n'")
               end
               return "ungit"
            end,
            icon = icons.git.Branch,
            padding = { left = 2, right = 1 },
          },
        },
```

which gets me the `branch name` or `ungit` but it take too much time to update, like around a few secs after neovim startup which i do not want...

or if the `git branch` is taking too much time, is there any way to `return` the component `branch` from a function?

**Comment by shadmansaleh** [comment]
You can use `fmt` option to overwrite result of the component based on component output

```lua
      {'branch', fmt=function(str) return str ~= '' and str or 'ungit' end},
```

this should pretty much do what you want.

**Comment by daUnknownCoder** [comment]
> You can use `fmt` option to overwrite result of the component based on component output
> 
> ```lua
>       {'branch', fmt=function(str) return str ~= '' and str or 'ungit' end},
> ```
> 
> this should pretty much do what you want.

hi thanks for this, i was racking my brains too hard not to see a simple solution like this, CHEERS! 🥂
