### ISSUE TITLE
Feat:  statusline showing a straight line

### ISSUE THREAD

**Issue by epheien** [nvim-lualine/lualine.nvim#1258]
<img width="822" alt="Xnip2024-06-11_21-56-15" src="https://github.com/nvim-lualine/lualine.nvim/assets/3406908/581ede90-589b-473c-ad52-ab3152aee2eb">

### Requested feature

Can we implement a statusline like the one in the picture?
Such a statusline makes it easy to distinguish the boundaries of different windows

I am currently using incline+lightline to implement it, but it would be better if lualine.nvim could implement it.

### Motivation

When using multiple windows, the inactive statusline cannot be used as a clear window boundary, especially when some windows have `cursorline` enabled.

**Comment by shadmansaleh** [comment]
Can you tell me how you're implementing it with lightline and incline?

**Comment by epheien** [comment]
> Can you tell me how you're implementing it with lightline and incline?

I found solution: `set fillchars+=stl:─,stlnc:─`

**Comment by shadmansaleh** [comment]
> > Can you tell me how you're implementing it with lightline and incline?
> 
> I found solution: `set fillchars+=stl:─,stlnc:─`

Nice. I was just writing about those :]
