### ISSUE TITLE
Feat: support `max_length` in `branch` component

### ISSUE THREAD

**Issue by AntonNiklasson** [nvim-lualine/lualine.nvim#1269]
### Requested feature

Some of my branches have really long names, but I only care about parts of it in that case. I'd like to set a max length and have the branch name be cut off if longer than that.

**Comment by shadmansaleh** [comment]
You can use the `fmt` option to do this. We allow you to run you custom formatter on top of component outputs before they get displayed. With that you can achieve this kind of truncation on any component you want not just branch.


https://github.com/nvim-lualine/lualine.nvim?tab=readme-ov-file#general-component-options

**Comment by AntonNiklasson** [comment]
Perfect, thank you!

**Comment by bnlokash** [comment]
If anyone finds this, here's a snippet that worked for me:
```
        lualine_b = {
          {
            'branch',
            fmt = function(display_string, context)
              if #display_string > 20 then
                return display_string:sub(1, 20) .. '...'
              else
                return display_string
              end
            end,
          }
        },

```
