### ISSUE TITLE
Bug: How to make winbar always visible?

### ISSUE THREAD

**Issue by xuanhung1509** [nvim-lualine/lualine.nvim#1271]
I'm migrating from `barbecue.nvim` to use native `lualine`'s winbar support. So far, I'm quite happy with it after integrating with 'nvim-navic". The only issue that annoys me is that the winbar line disappears if I open a window from a plugin (Lazy/Mason...), making the editor shift up one line.

https://github.com/nvim-lualine/lualine.nvim/assets/89293664/f3356836-9fae-4e23-ac76-80c4fab3c8b2

### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in existing issues or PRs.

### How to reproduce the problem

- Add winbar component to lualine (see below config)
- Open Lazy/Mason/Telescope

### Expected behaviour
Winbar line stays even if no content.

### Actual behaviour
Winbar line disappears, making the editor shift up one line.

### Minimal config to reproduce the issue
- Use `kickstart.nvim` as starter template
- Add the plugin:
```lua
-- You can add your own plugins here or in other files in this directory!
--  I promise not to create any merge conflicts in this directory :)
--
-- See the kickstart.nvim README for more information
return {
  {
    'nvim-lualine/lualine.nvim',
    config = function()
      local lualine = require 'lualine'

      local function filepath()
        local path = vim.fn.expand '%'
        path = path:gsub('/', ' > ')
        return path
      end

      lualine.setup {
        winbar = {
          lualine_a = {
            { filepath },
          },
        },
      }
    end,
    event = 'VeryLazy',
  },
}
```

**Comment by shadmansaleh** [comment]
As you can see in the [docs](https://github.com/nvim-lualine/lualine.nvim#winbar) there are to configuration items `winbar` and `inactive_winbar` which sets winbar for active and inactive windows respectively.

because you never set `inactive_winbar` lualine doesn't show winbars on inactive_windows.

```lua
 lualine.setup {
        winbar = {
          lualine_a = {
            { filepath },
          },
        },
        inactive_winbar = {
          lualine_a = {
            { filepath },
          },
        },
      }
 ```
 
if you want just the line to be shown in in active window you can just put a whitespace component in inactive_winbar
 
 ```lua
   inactive_winbar = {
    lualine_a = {
      function() return " " end
    }
  },
```

**Comment by xuanhung1509** [comment]
Nice, I could not understand what the inactive_<stuff> does until now. Thank you!
