### ISSUE TITLE
Bug: Not able to enable lualine with Lazy and using custom path for data dir to store installation files

### ISSUE THREAD

**Issue by vivekvpandya** [nvim-lualine/lualine.nvim#1273]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in existing issues or PRs.

### How to reproduce the problem
Installed Lua line and enabled it in init.lua
### Expected behaviour
lualine should work like any other plugin.

### Actual behaviour
Error detected while processing /local/mnt/workspace/users/vpandya/nvim/init.lua:
E5113: Error while calling lua chunk: /local/mnt/workspace/users/vpandya/nvim/init.lua:122: module 'lualine' not found:
        no field package.preload['lualine']
        no file './lualine.lua'
        no file '/usr/share/luajit-2.1.0-beta3/lualine.lua'
        no file '/usr/local/share/lua/5.1/lualine.lua'
        no file '/usr/local/share/lua/5.1/lualine/init.lua'
        no file '/usr/share/lua/5.1/lualine.lua'
        no file '/usr/share/lua/5.1/lualine/init.lua'
        no file './lualine.so'
        no file '/usr/local/lib/lua/5.1/lualine.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/lualine.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /local/mnt/workspace/users/vpandya/nvim/init.lua:122: in main chunk

**Comment by shadmansaleh** [comment]
Did you use the proper configuration on lazy?

https://github.com/nvim-lualine/lualine.nvim#lazynvim

It seems lualine is just not loaded `rtp` . It's not a lualine issue. likely miss configuration of lazy.

**Comment by vivekvpandya** [comment]
if you are referring to following rtp setting its there in my lazy config.

![image](https://github.com/nvim-lualine/lualine.nvim/assets/5086212/a43f03b4-e2f6-4ae6-862d-e3a38aa74ca4)

**Comment by vivekvpandya** [comment]
![Screenshot 2024-07-08 102452](https://github.com/nvim-lualine/lualine.nvim/assets/5086212/035aacc2-b5eb-4fd0-9bef-1731e0209ae6)
lualine is installed at this location.

**Comment by shadmansaleh** [comment]
> if you are referring to following rtp setting its there in my lazy config.
> 
> ![image](https://private-user-images.githubusercontent.com/5086212/346432523-a43f03b4-e2f6-4ae6-862d-e3a38aa74ca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MTU0NjMsIm5iZiI6MTcyMDQxNTE2MywicGF0aCI6Ii81MDg2MjEyLzM0NjQzMjUyMy1hNDNmMDNiNC1lMmY2LTRhZTYtODYyZC1lM2EzOGFhNzRjYTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDhUMDUwNjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2EzNGE0NmM4ZGI5NDAxMzFhOWE2MWIzNzBkMWI3MWZjYmRmMTAyY2JkMzhkYTgzNWRlMjExNjkxNzQ4ZmYxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7CKLwzydJ6uqtxc8-bwPmJgXX-T2llFzuLelrQQbP1U)

Not that, Basically for any plugin to be loaded on neovim it's directory needs to be added to `rtp`. and few other things. Plugin managers handle these. Here you're loading the lazy onto neovim. Then lazy is supposed to load other plugins including lualine based on your configuration. If lualine isn't getting added to rtp that's plugin managers issue not lualines. Considering lazy is pretty stable, I feel like it might be a configuration issue instead.

**Comment by vivekvpandya** [comment]
I have other plugins installed and enabled they work just fine. Also, for plugins that works I don't see any specific config which specifies above directory path.

**Comment by shadmansaleh** [comment]
Can you give a minimal config that can reproduce it?

**Comment by shadmansaleh** [comment]
> I have other plugins installed and enabled they work just fine. Also, for plugins that works I don't see any specific config which specifies above directory path.

what directory path are you talking about? like I said only plugin managers are concerned about maintaining `rtp` other plugins are not.
