### ISSUE TITLE
Bug: showtabline is affected by seemingly irrelevant options

### ISSUE THREAD

**Issue by neeshy** [nvim-lualine/lualine.nvim#1294]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in existing issues or PRs.

### How to reproduce the problem
I have a configuration that conditionally shows the tabline based on the number of open buffers. This is accomplished with auto commands that set the `showtabline` option. I would prefer to use lualine's builtin `cond` option, but even when no conditions are satisfied on any tabline segments, the tabline itself doesn't become hidden.

I noticed that the value of `background` will influence the behavior of the tabline on startup. If `background` is set to `dark`, `showtabline` will eventually be set to `2`. This is despite `showtabline` being set to `1` after lualine's setup and through the end of the configuration.

### Expected behaviour
The value of `background` shouldn't affect `showtabline`.

### Actual behaviour
When `background=light`, `showtabline` isn't modified. If `background=dark` (the default), sometime after startup `showtabline=2`.

### Minimal config to reproduce the issue

```lua
vim.opt.showtabline = 1 -- default
vim.opt.background = 'light' -- commenting this out will cause showtabline to be set to '2' sometime after startup

require('lualine').setup {
  tabline = {
    lualine_a = { { 'buffers' } },
  },
}

-- Don't allow lualine to modify 'showtabline'. From this point on it should be set to 1.
require('lualine.utils.nvim_opts').restore('showtabline', { global = true })

-- This should print '1' irrespective of the value of vim.opt.background
print(vim.opt.showtabline:get())
```

**Comment by ferdinandrau** [comment]
This is really annoying. While it makes sense for the plugin to modify `showtabline` initially to always show the tabline, it should respect the option being set back to `1`. The PR https://github.com/nvim-lualine/lualine.nvim/pull/1013 solves this, but is being ignored.

**Comment by neeshy** [comment]
Removing the following autocmds:

https://github.com/nvim-lualine/lualine.nvim/blob/b431d228b7bbcdaea818bdc3e25b8cdbe861f056/lua/lualine.lua#L267-L268

fixes the issue for me.

```lua
vim.cmd.autocmd { 'lualine ColorScheme', bang = true }
vim.cmd.autocmd { 'lualine OptionSet background', bang = true }
```

**Comment by shadmansaleh** [comment]
fixed with #1013 

use `always_show_tabline = false` in config.

**Comment by neeshy** [comment]
An alternative is to set `showtabline` within a relevant `cond` function:

```lua
require('lualine').setup {
  tabline = {
    lualine_a = {
      {
        'buffers',
        cond = function()
          local cond = #vim.fn.getbufinfo { buflisted = 1 } > 1
          if cond then vim.opt.showtabline = 2 end
          return cond
        end,
      },
    },
  },
}
```

**Comment by neeshy** [comment]
WTF, https://github.com/nvim-lualine/lualine.nvim/issues/1294#issuecomment-2487409554 triggers this bug: #1141

**Comment by neeshy** [comment]
I guess you could do something like this:
```lua
require('lualine').setup {
  tabline = {
    lualine_a = {
      {
        'buffers',
        cond = function()
          if #vim.fn.getbufinfo { buflisted = 1 } > 1 then
            if vim.opt.showtabline:get() ~= 2 then
              vim.opt.showtabline = 2
            end
            return true
          else
            if vim.opt.showtabline:get() ~= 1 then
              vim.opt.showtabline = 1
            end
            return false
          end
        end,
      },
    },
  },
}
```

But the solotion in https://github.com/nvim-lualine/lualine.nvim/issues/1294#issuecomment-2487409554 works fine at least on commit e9b935ccd6bdc95fb7a8b3718aa268659aa3965a (I haven't done a full bisect).

**Comment by neeshy** [comment]
@shadmansaleh
In light of https://github.com/nvim-lualine/lualine.nvim/issues/1294#issuecomment-2487371371 can you reopen this issue?
