### ISSUE TITLE
Bug: Please rename the `refactor/nvim_get|set_option_value` branch

### ISSUE THREAD

**Issue by jpt13653903** [nvim-lualine/lualine.nvim#1318]
Git works by creating a file in the `.git` folder with the same name as the branch name, but the pipe character is illegal on Windows, so all the git commands fail, meaning that `PackerSync` fails to update lualine:

```
 ✗ Failed to update nvim-lualine\lualine.nvim
  Errors:
    error: cannot lock ref 'refs/remotes/origin/refactor/nvim_get|set_option_value': Unable to create 'C:/Users/jpt13/AppData/Local/nvim-data/site/pack/packer/start/lualine.nvim/.git/refs/remotes/origin/refactor/nvim_get|set_option_value.lock': Invalid argument
    From https://github.com/nvim-lualine/lualine.nvim
     ! [new branch]      refactor/nvim_get|set_option_value -> origin/refactor/nvim_get|set_option_value  (unable to update local ref)
    640260d
```

So, please could you rename the branch with a `/` instead of a `|`?

I can of course go into the lualine clone and manually do a fetch and forced branch pointer move, but I would prefer to use PackerSync for that purpose.

**Comment by comiluv** [comment]
Same error using lazy.nvim

**Comment by shadmansaleh** [comment]
Wait whattt. It's a dev branch. Name of devbranch causing failure in updates has too be one of the strangest thing I've heard today. Why are they even following non master brach anyway.

I'll rename the branch.

**Comment by jpt13653903** [comment]
Awesome - thank you!

I'm not following the branch.  `git pull` on master fetches all branches, including the dev branches, and then the pull fails when it cannot create the branch.
