### ISSUE TITLE
Bug: A noticeably slow reaction while jumping between windows

### ISSUE THREAD

**Issue by greyHairChooseLife** [nvim-lualine/lualine.nvim#1328]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in existing issues or PRs.

### How to reproduce the problem

It's happened  from the commit "2024-11-07 0978a6c Fixup: fix flickering in lualine (#1316)"

### Expected behaviour

A seamless speed of responding followed by user window focusing.

### Actual behaviour

A noticeably slow speed of responding around 1 second.

### Minimal config to reproduce the issue

Nothing but if only I checkout out somewhere after 640260d, it happens.

I've checked with a CPU like i9 or so. That was not the case though.

**Comment by Antony-AXS** [comment]
yes i have noticed the same issue, its now really slow
![ezgif-2-152026ddf3](https://github.com/user-attachments/assets/01fa1e47-400b-4714-b950-9e6d5b3fa218)
as you can see when I'm jumping form one window to another there is a delay in status line getting updated.
this issue was not there before the recent update came

**Comment by iohan** [comment]
I have the same issue, lulines lag while everything else is super fast.
![Lualine (3)](https://github.com/user-attachments/assets/5d32cb9e-55dd-4d3b-96d6-880ad168811c)




NVIM v0.10.2
Lualine commit 2a5bae9
Latest Macbook Pro M4 Pro

**Comment by gmmyung** [comment]
Yes, this is a huge issue for me too. I feel like it has gotten worse over subsequent updates.

*With lualine*

https://github.com/user-attachments/assets/134c6e38-2e69-4e67-9a08-edc036aa03a1

*Without lualine*

https://github.com/user-attachments/assets/8ae0a60d-9dc2-4ec7-ac75-71c834ece8b9

**Comment by rodneykeeling** [comment]
I was having the same problem, but it turned out it was just the default 1000ms value for the refresh rate. I updated [these](https://github.com/nvim-lualine/lualine.nvim/wiki/FAQ#my-statuslinetablinewinbar-updates-infrequently) to 100ms instead, and it's noticeably more responsive now.

**Comment by gmmyung** [comment]
I guess that‘s a mistake? It says the default value is 100ms in Readme.md.

**Comment by gmmyung** [comment]
https://github.com/nvim-lualine/lualine.nvim/blob/2a5bae925481f999263d6f5ed8361baef8df4f83/lua/lualine/config.lua#L24
Hmm…

**Comment by greyHairChooseLife** [comment]
@rodneykeeling 

This solved the problem for me as well. 
My old one was also set to 1000, and changing it to 100 or less resolved the issue.

With closing this issue, I recommend reviewing commit 0978a6c carefully, or

<details>
<summary>Here’s a bit of additional context that I discovered:</summary>

1. My old config was set on 2023-05-08. 
2. At that time, I referred to the public README, which was saying 1000 ms for the option.
    (* 2023-05-04 05d78e9 fixup: fix tests)
3. Recently(2 weeks ago), there was commit as follow:
    - commit 0978a6c8a862d999baf51366926c7b56eb9cf3d1
    - Author: Shadman <13149513+shadmansaleh@users.noreply.github.com>
    - Date:   Thu Nov 7 20:46:25 2024 +0600

    file change sayging,

   ```markdown
   # README.md
    refresh = {
      statusline = 100,
      tabline = 100,
      winbar = 100,
    }
   ```

    commit message saying,
 
   `Instead now lualine will only refresh on timer. To make lualine
    resoponsive as before refresh time has been reduced to 100ms from 1s.
    Means now lualine would refresh 10 times per second by default.`

</details>

---

PS: It might have been helpful if the commit header included a `!` mark to indicate breaking(?) changes. I should also make a habit of reading commit messages more carefully—or perhaps improving my English further!

Regardless, I love this product and deeply appreciate every single contributor.

Sincerely,
