### ISSUE TITLE
Feat: provide configs for users

### ISSUE THREAD

**Issue by hoob3rt** [nvim-lualine/lualine.nvim#173]
### Requested feature

Provide multiple default configs (some simple and some complex like evil_lualine) & enable users to extend them. 

Would be nice to also make complex statuslines like evil_lualine theme aware.

something like
```lua
require('lualine').setup {
  config = 'evilline',
  options = {theme = 'powerline'},
  sections = {
    lualine_a = {{'mode', lower = true}}, -- change the section completely
    -- append/ prepend section to existing config (this is a js-like table extension snippet just to show how it should work)
    lualine_b = {[...evilline.lualine_b, 'filename']} 
  }
}
```

### Motivation

Enables users to have complex statuslines with minimal personal config.

**Comment by shadmansaleh** [comment]
I'm not entirely sure if it's possible to do for custom configs like evil_lualine . It was written in same manner as galaxyline configs are written . Basically I've treated lualine as an API and kept as much control needed to config.

> evil_lualine theme aware

Oh no . Every component uses it's specific color I don't even know what theme'll do there . Also in there I've only used lualine_c and lualine_x section . I was actually looking at galaxyline's example and realised lualine could be treated as a super set of galaxyline . You can checkout the example config I've linked to have a clear sight of how it was made.

We could probably add more custom statusline like evil_lualine with config and let users take inspiration from them if they are interested in creating a custom look.

Though if you've an idea on how to implement this feature . Please go ahead it'll definatly be amazing if it's added :)

**Comment by shadmansaleh** [comment]
I think we should provide config examples like we do with bubble line & evilline so users can expand from there.

It's already possible to get current config with `require'lualine'.get_config()` and tweak that table and apply changes by calling `require'lualine'.setup()`.
