### ISSUE TITLE
Feat: Add option for viewing filetype icon WITHOUT text

### ISSUE THREAD

**Issue by shaunsingh** [nvim-lualine/lualine.nvim#233]
### Requested feature
It would be nice to have the option to just have the filetype icon without having to have the name for it. 

### Motivation
My lualine is based off of doom-modeline, which has the icon as follows: 

<img width="543" alt="image" src="https://user-images.githubusercontent.com/71196912/117876871-d9cbe900-b271-11eb-8af7-66818e8bb26e.png">

I personally think having just the icon without the filetype looks quite clean, and that if you have text after the icon its redundant since you have the filename afterwards

**Comment by hoob3rt** [comment]
I will try exposing the function to get icon globally, this way you will be able to do
```lua
lualine_ a = {{'filename', icon = get_icon()}}
```

For now you can try
```lua
lualine_a = {{'filetype', format = function() return " " end, right_padding=0}}
```
Although it will return an additonal separator if you have `component_separators` set

**Comment by hoob3rt** [comment]
> Thank you, works as expect. Would you like me to close the issue as a pr is in place?

the issue will close itself when it's done :smile:
