### ISSUE TITLE
Feat: Add keymap component

### ISSUE THREAD

**Issue by Snagovskiy-Denis** [nvim-lualine/lualine.nvim#368]
### Requested feature
Add status line component what shows short name of current keymap (:help keymap)

### Motivation
I wrote a custom component, but it isn't dynamic enough:
```lua
vim.opt.keymap =  'russian-jcukenwin'

-- show current keymap if it is not english
local function keymap ()
    local current_keymap = vim.opt.iminsert._value
    if current_keymap == 1 then return '⌨ RU' else return '' end
end

require 'lualine'.setup {
    sections = {
        lualine_a = { 'mode', keymap },
    },
}
```

Many of vim users will write the same function, so it would be logical to include something like that in lualine.

**Comment by gerazov** [comment]
This is exactly what I was missing :love_you_gesture:  I modified it a bit to reduce the text length and to keep one for English:
```lua
    local function keymap ()
      if vim.opt.iminsert:get() > 0 and vim.b.keymap_name then
        if vim.b.keymap_name == 'macedonian-UTF-8' then
          return '⌨ mk'
        else
          return '⌨ ' .. vim.b.keymap_name
        end
      else
        return '⌨ en'
      end
    end
```

**Comment by ruffe972** [comment]
@shadmansaleh , hello. Where can I vote for this feature to work out of the box in lualine?

Layout indicator works out of the box in plain neovim without any plugins, so I'll disable lualine for now in my config.

By the way, wiki link is broken.

**Comment by fcsm1922** [comment]
> Это именно то, чего мне не хватало 🤟 Я немного изменил его, чтобы уменьшить длину текста и сохранить его для английского:
> 
>     local function keymap ()
>       if vim.opt.iminsert:get() > 0 and vim.b.keymap_name then
>         if vim.b.keymap_name == 'macedonian-UTF-8' then
>           return '⌨ mk'
>         else
>           return '⌨ ' .. vim.b.keymap_name
>         end
>       else
>         return '⌨ en'
>       end
>     end

Can you tell me where to insert this in the lualine.lua file?

**Comment by gerazov** [comment]
Sure here's my whole config:
```lua
return {
  'nvim-lualine/lualine.nvim', -- Fancier statusline
  lazy = true,
  event = 'VeryLazy',
  config = function ()
    local function line_total()
      return " " .. vim.api.nvim_buf_line_count(
        vim.fn.winbufnr(vim.g.statusline_winid)
      )
    end
    local function keymap ()
      if vim.opt.iminsert:get() > 0 and vim.b.keymap_name then
        if vim.b.keymap_name == 'macedonian-UTF-8' then
          return '⌨ mk'
        else
          return '⌨ ' .. vim.b.keymap_name
        end
      else
        return '⌨ en'
      end
    end
    require('lualine').setup {
      options = {
        icons_enabled = true,
        -- theme = 'auto',
        theme = 'catppuccin',
        -- component_separators = { left = '', right = ''},
        -- section_separators = { left = '', right = ''},
        section_separators = { left = '', right = '' },
        -- component_separators = { left = '', right = '' },
        component_separators = { left = '│', right = '│' },
        -- border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
        disabled_filetypes = {},
        always_divide_middle = true,
        globalstatus = true,
      },
      sections = {
        lualine_a = {'mode'},
        lualine_b = {'branch', 'diff', 'diagnostics'},
        lualine_c = {'filename'},
        -- lualine_x = {'encoding', 'fileformat', 'filetype'},
        lualine_x = {'filetype'},
        -- lualine_y = {'progress'},
        lualine_y = {keymap},
        lualine_z = {'location', 'progress', line_total},
      },
      inactive_sections = {
        lualine_a = {},
        lualine_b = {},
        lualine_c = {'filename'},
        lualine_x = {'location'},
        lualine_y = {},
        lualine_z = {},
      },
      tabline = {},
      extensions = {},
    }
  end
}
```

**Comment by fcsm1922** [comment]
> Конечно, вот весь мой конфигурация:
> 
```
>     require('lualine').setup {

> ``` 

nvim write...is not work...
```
Failed to run `config` for lualine.nvim

/home/xxx/.config/nvim/lua/plugins/lualine.lua:22: attempt to call field 'setup' (a nil value)

# stacktrace:
  - .config/nvim/lua/plugins/lualine.lua:22 _in_ **config**
```
What is the error? and how to solve it?

**Comment by gerazov** [comment]
Try deleting `~/.local/share/nvim/lazy/` and reinstall the plugins via Lazy.

**Comment by fcsm1922** [comment]
> Попробуйте удалить `~/.local/share/nvim/lazy/` и переустановить плагины через ленивые.

thanks!
But it doesn't work for me, when I change the keyboard layout (I use Russian + English layout) in lualine as it was “en” and still is.... nothing changes..... maybe I'm doing something wrong?
I am using archlinux with hyprland (in it by the way I have customized keyboard switching)...
I use Nvim in full screen ( without bars, and I would like to have the current keyboard layout always visible in front of my eyes).

**Comment by gerazov** [comment]
What did you put instead of `'macedonian-UTF-8'`? 

It should match what prints out when you are in Russian and run `lua print(vim.b.keymap_name)`

**Comment by fcsm1922** [comment]
Write script. all work! thank!

**Comment by uralets** [comment]
An example of the disconnect between the vendor and the userbase.

Lualine comes with a *clock* enabled by default (does it really need to?), yet for anyone who's not using exclusively only the Latin layout i.e. uses at least one alternative language, keymap/iminsert feature is the most natural workflow since the Vim days. Yet the author deemed this to be something no-one would ever need (how are we supposed to use (neo)Vim commands without it while needing to type in a non-Latin layout?)

**Comment by uralets** [comment]
Obviously this should be shipped by default - this won't even show up for those who don't use keymap/iminsert but is essential for those who do.
