### ISSUE TITLE
Feat: Add filename option to not shorten path segments

### ISSUE THREAD

**Issue by itmecho** [nvim-lualine/lualine.nvim#389]
### Requested feature
Add option to the filename component to disable path shortening

### Motivation
It would be nice to have the option to disable filename path shortening as that information is really useful, especially when I'm on a wide screen that has more than enough room.

**Example:**
![image](https://user-images.githubusercontent.com/8384983/129334752-3f86e5b7-402f-4b3a-a766-d2ac341abd8e.png)

```lua
lualine_c = {
    {"filename", path = 1}
},
```

**Comment by sthendev** [comment]
`padding`? In the same sense as CSS. Slightly different in this context in that it causes shortening of the path but it was the first thing that came to mind when seeing this.
