### ISSUE TITLE
Bug: gruvbox theme not working

### ISSUE THREAD

**Issue by isaif** [nvim-lualine/lualine.nvim#397]
*Gruvbox* and *gruvbox_dark* theme's colors not working.

Gruvbox and gruvbox_dark looks the same but as it should look, i.e. colors are not right:
![image](https://user-images.githubusercontent.com/11773308/138553889-caa1116f-3b00-454c-8694-e7e15ac208b1.png)

Themes like *horizon* and *iceberg_dark* does work. The colors looks as it is in the [THEMES.md](https://github.com/nvim-lualine/lualine.nvim/blob/master/THEMES.md)
Horizon:
![image](https://user-images.githubusercontent.com/11773308/138553942-4d4da6ad-1d74-4a96-890b-686d72b53155.png)

Iceberg_dark:
![image](https://user-images.githubusercontent.com/11773308/138554011-a72764a6-5418-43ff-ac00-30cb0c476aa9.png)

Codedark:
![image](https://user-images.githubusercontent.com/11773308/138554065-fb3c44d4-d416-4419-8f32-a5540ccf81c1.png)

neovim version:
```
NVIM v0.6.0-dev+467-g30af69509
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by root@linux
```
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

```
require('lualine').setup{
  options = {theme = 'gruvbox_dark'}
}

```
init.vim
```
let g:gruvbox_contrast_dark="hard"
colorscheme gruvbox
set cursorline
set t_Co=256
```

### Expected behaviour
Gruvbox theme colors
![image](https://user-images.githubusercontent.com/11773308/138554277-fec66b48-3c03-48e4-9a11-59be07c175dc.png)
![image](https://user-images.githubusercontent.com/11773308/138554288-2930a557-2c85-472c-8d6d-b088327340aa.png)
![image](https://user-images.githubusercontent.com/11773308/138554223-aa16d11b-a773-4a09-9d79-33c69d03df84.png)
![image](https://user-images.githubusercontent.com/11773308/138554304-f4f1d67f-be76-4f45-bf12-d2f44153c139.png)

### Actual behaviour
Gruvbox theme colors which I am getting
![image](https://user-images.githubusercontent.com/11773308/138554321-72e540bd-0f7a-49c4-aeba-0a8ff20333b8.png)
![image](https://user-images.githubusercontent.com/11773308/138554333-078f8205-838c-4810-938b-020e79a41299.png)
![image](https://user-images.githubusercontent.com/11773308/138554347-85e20309-4ffb-4d7e-abe8-d062be150282.png)
![image](https://user-images.githubusercontent.com/11773308/138554355-6b19252b-c882-49f5-a3fb-6185bdccef58.png)

<details>
<summary>Config</summary>

</details>

**Comment by botsunny** [comment]
I had quite a strange experience. After adding `set termguicolors` in my init.vim, literally every theme works for me except Nord, which is exactly the theme that I want to use. When I went over to the source code for the Nord theme, copied it, created a new .lua file in the themes directory, pasted in it, and set my lualine config to that new .lua file, it worked fine.

**Comment by shadmansaleh** [comment]
@botsunny I'll take a guess you're using e nord colorscheme that provided nord theme for lualine too . If such the case lualine will load the theme from colorscheme not the one in this repo .

**Comment by botsunny** [comment]
You're right. Looks like that's the case.
