### ISSUE TITLE
Bug: Diagnostics color issues

### ISSUE THREAD

**Issue by tristan957** [nvim-lualine/lualine.nvim#402]
* `diagnostics_color` has no effect when each is set to nil.
* Background color of `diagnostics` doesn't change when modes change unless `colored=false`.

### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

```lua
require("lualine").setup({
	options = {
		icons_enabled = false,
		theme = "powerline",
		component_separators = { left = "|", right = "|" },
		section_separators = { left = "", right = "" },
	},
	sections = {
		lualine_b = {
			"branch",
			"diff",
		},
		lualine_c = {
			{
				"diagnostics",
				sources = { "nvim_lsp", "coc" },
				sections = { "error", "warn", "info", "hint" },
				diagnostics_color = {
					error = false,
					warn = false,
					info = false,
					hint = false,
				},
				symbols = { error = "E", warn = "W", info = "I", hint = "H" },
				always_visible = true,
				update_in_insert = false,
				color = nil,
			},
			"filename",
			require("lsp-status").status,
		},
	},
})
```

### Expected behaviour

`diagnostics_color` should have an effect when set to nil, meaning unset the color. The background color of the diagnostics should follow the theme when switching modes.

### Actual behaviour

`diagnostics_color` members don't get unset when set to nil. Background color doesn't update with theme when switching modes.

**Comment by tristan957** [comment]
@shadmansaleh seeing the following issue:

![image](https://user-images.githubusercontent.com/11936772/147378157-fce50142-8a8b-49b5-afb6-21f0e3b19b7d.png)

Here is my current setup:

```lua
require("lualine").setup({
	options = {
		icons_enabled = false,
		theme = "powerline",
		component_separators = { left = "|", right = "|" },
		section_separators = { left = "", right = "" },
	},
	sections = {
		lualine_b = {
			"branch",
			"diff",
		},
		lualine_c = {
			"filename",
			{
				"diagnostics",
				sources = { "nvim_diagnostic" },
				diagnostics_color = {
					error = "DiagnosticError",
					warn = "DiagnosticWarn",
					info = "DiagnosticInfo",
					hint = "DiagnosticHint",
				},
				sections = { "error", "warn", "info", "hint" },
				symbols = { error = "E", warn = "W", info = "I", hint = "H" },
				always_visible = false,
				update_in_insert = false,
			},
			require("lsp-status").status(),
		},
	},
})
```

This seems very much like the the original issue if I remember. I would have expected the background color of the diagnostics section to be the same as the rest of the theme.

**Comment by imjasonmiller** [comment]
@tristan957 I'm experiencing the same for what it's worth, practically the same configuration, but using `gruvbox` for now, also expected it to default to the background of e.g. `diff` to the left of it.

![Lualine diagnostics component having a different background color to other components](https://user-images.githubusercontent.com/12190184/147392879-2dc57d76-abb3-4ca3-89b2-889ccb3dbd8a.png)

---

The plugin is amazing so far @shadmansaleh, thank you!

**Comment by tristan957** [comment]
So I found the issue: 
![image](https://user-images.githubusercontent.com/11936772/147885215-0c47fd4f-afcf-4134-8644-a19463539bf4.png)

You can see that there is not bg defined, just this "links to" thing

**Comment by tristan957** [comment]
I think using linking here is incorrect. We need to apply the currently linked color as the foreground and apply the background as necessary. @shadmansaleh any thoughts? Would probably help to re-open this.

**Comment by tristan957** [comment]
To evaluate a highlight group, use the following:

```lua
vim.fn.synIDattr(vim.fn.hlID("DiagnosticError"), "fg", "gui" | "cterm" ))
```

Once lualine has done this, it can use the necessary background color after applying the foreground without "links".

**Comment by shadmansaleh** [comment]
Sorry for late response . As you figured when Hl_goup is provided in color option lualine links to that group. Here lualine relies of user providing the correct group because hl_group can contain both foreground & background colors and lualine can't know if user want's fg/bg or  both from that hl_group . To avoid this you xan set color as table containing fg,bg.... keys . You can use something like [extract_highlight_colors](https://github.com/nvim-lualine/lualine.nvim/blob/b18b7ee8acf877a603c21b28b9a4d9c08bbd9594/lua/lualine/utils/utils.lua#L11-L28) to get color from hl_group .

For example:
```lua
local get_color = require'lualine.utils.utils'.extract_highlight_colors
require("lualine").setup({
  lualine_c = {
    {"diagnostics",
	diagnostics_color = {
          error = {fg = get_color("DiagnosticError", "fg")},
	  warn = {fg = get_color("DiagnosticWarn", "fg")},
	  info = {fg = get_color("DiagnosticInfo", "fg")},
	  hint = {fg = get_color("DiagnosticHint", "fg")},
	},			
  },
}
```

**Comment by tristan957** [comment]
@shadmansaleh thanks for the background on the issue. Is this information available in the README? If not, I wouldn't mind sending a PR, so others don't fall into the same trap.

**Comment by shadmansaleh** [comment]
You can put it in the [FAQ](https://github.com/nvim-lualine/lualine.nvim/wiki/FAQ) if you want to.

**Comment by tristan957** [comment]
I'll look into that. Never submitted to a wiki on github before.

**Comment by saurabhchardereal** [comment]
> You can put it in [FAQ](https://github.com/nvim-lualine/lualine.nvim/wiki/FAQ) if you want to.

I faced the exact same issue and was looking for docs related to the same but it wasn't mentioned in docs nor in the README. After some searching I stumbled upon here.

It'll be easy for those who face this issue to have the "fix" mentioned somewhere. I tried to edit docs but the Wiki has restricted edit permissions I guess.

**Comment by h0adp0re** [comment]
I'll cast another vote here. I had the same problem and eventually searched for "background" in the issues. It would be nice if it'd be mentioned somewhere in the docs, though.
