### ISSUE TITLE
Feat: show the method/function name

### ISSUE THREAD

**Issue by dcy** [nvim-lualine/lualine.nvim#409]
Can i show the method/function name in airline?
Like [this](https://github.com/liuchengxu/vista.vim#show-the-nearest-methodfunction-in-the-statusline)

**Comment by janwaldmann** [comment]
lualine + [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter#statusline-indicator):
```lua
local treesitter = require('nvim-treesitter')
local function treelocation()
  return treesitter.statusline({
    indicator_size = 70,
    type_patterns = {'class', 'function', 'method'},
    separator = ' -> '
  })
end

require('lualine').setup{
  sections = {
    -- [...]
    lualine_c = {{treelocation}}
  }
}
```

**Comment by shadmansaleh** [comment]
@janwaldmann That looks nice . You can put it in the [wiki](https://github.com/nvim-lualine/lualine.nvim/wiki/Component-snippets) if you want to so others can find it easily .

There's also [nvim-gps](https://github.com/nvim-lualine/lualine.nvim/wiki/Component-snippets) and also I think there's a function in nvim-lsp that provides current function name too .
