### ISSUE TITLE
Bug: `disabled_filetypes` doesn't seem to work

### ISSUE THREAD

**Issue by mkeeter** [nvim-lualine/lualine.nvim#412]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
Using the minimal config, add `disabled_files = {'vim'}` to setup, then open `init.vim`.

(this is also reproducible with other filetypes, but using `vim` was easiest with the isolated config)

### Expected behaviour
`lualine` doesn't appear

### Actual behaviour
`lualine` shows up as usual

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

```vim
call plug#begin("/Users/mkeeter/lualine-debug/.local/share/nvim/plugged")
" Your plugins go here like
Plug 'nvim-lualine/lualine.nvim'


call plug#end()

" Your Viml part of config goes here
" colorscheme onedark


lua << END
-- Your lua part of config goes here
require'lualine'.setup {
  disabled_filetypes = {'vim'},
}


END
```

</details>

### Additional information
I'm using `nvim 0.5.0`, and `lualine` is otherwise great!

**Comment by mkeeter** [comment]
Never mind, this parameter needs to be in the `options` map, e.g.
```
require'lualine'.setup {
  options {
    disabled_filetypes = {'vim'}
  }
}
```

**Comment by rbhanot4739** [comment]
I am having exact same issue with latest version of lualine. Here is the minimal config

```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
  if vim.v.shell_error ~= 0 then
    error("Error cloning lazy.nvim:\n" .. out)
  end
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

require("lazy").setup({
  spec = {
    {
      {
        "nvim-lualine/lualine.nvim",
        opts = {
          disabled_filetypes = { "python" },
          tabline = {
            lualine_a = {},
            lualine_b = { "branch" },
            lualine_c = { "filename" },
            lualine_x = {},
            lualine_y = {},
            lualine_z = {},
          },
        },
      },
    },
  },
})

```

The filetype `python` here is just for example, I actually want to disable both `tabline` and `statusline` for buffers like `neo-tree` etc, however the option  `disabled_filetypes ` does not seem to work and lualine still shows up as usual.

**Comment by teto** [comment]
I had the same issue but once I moved `disabled_filetypes` under  the  `options = { disabled_filetypes = ... }` it fixed it
