### ISSUE TITLE
Bug: `'buffers'` and `'tabs'` padding not applied per element

### ISSUE THREAD

**Issue by ourigen** [nvim-lualine/lualine.nvim#414]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Using config provided in minimal config section

### Expected behaviour
Each buffer element would have padding applied on both side. For example, when there's one buffer/tab, left and right sides are equally padded

![](https://user-images.githubusercontent.com/79729735/139593548-7e121488-418a-444b-8c26-3912ede95467.png)

### Actual behaviour
I'm not sure if this is by design but setting `padding = n`  adds padding on the extremities of the section, rather than per buffer/tab elements

![](https://user-images.githubusercontent.com/79729735/139593530-b5c1c98e-3b73-47a4-9471-a62f5045817d.png)

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

```
require('lualine').setup{
  options = {
    component_separators = { left = '', right = '' },
    section_separators = { left = '', right = '' },
  },
  tabline = {
    lualine_a = {
      { 'buffers', padding = 5 }
    },
    lualine_b = {},
    lualine_c = {},
    lualine_x = {},
    lualine_y = {},
    lualine_z = {
     { 'tabs', padding = 5 }
    }
  },
}
```

</details>

### Aditional information

If this is by design, could there be an option added to allow per element padding?

**Comment by shadmansaleh** [comment]
You're right currently padding isn't [handled](https://github.com/nvim-lualine/lualine.nvim/blob/7eff9bbeb4e3ff93381f8f631536c59f1b65ffc9/lua/lualine/components/tabs/tab.lua#L54) per buffer/tab basis .

Currently I don't have time . It'll probably take a while for me to get hands on it . You're welcome to send a pr it should be farely easy :)
