### ISSUE TITLE
Feat: indent/trailing whitespace

### ISSUE THREAD

**Issue by eeeXun** [nvim-lualine/lualine.nvim#417]
### Requested feature
Extension for showing indent/trailing whitespace like [vim-airline](https://github.com/vim-airline/vim-airline/blob/21e47ca5b37ed418c4b9c105e14f53df200c8838/autoload/airline/extensions/whitespace.vim).
![image](https://user-images.githubusercontent.com/58657914/140401913-128cef64-d931-4af5-adbe-423171818fac.png)

### Motivation
When using vim-airline, I find it is really useful when checking undeleted whitespace.

**Comment by shadmansaleh** [comment]
You can adapt [the example](https://github.com/nvim-lualine/lualine.nvim/wiki/Component-snippets#mixed-indent) to your needs.

**Comment by eeeXun** [comment]
I want to show which line is trailing/mixed. I modify the code in trailing part
```lua
function()
    local space = vim.fn.search([[\s\+$]], 'nw')
    return  space ~= 0 and "[" .. space .. "]" .. "TW" or ""
end
```
But I don't know how to show the line in mixed

**Comment by shadmansaleh** [comment]
Updated mixed indent & trailing whitespace [snippets](https://github.com/nvim-lualine/lualine.nvim/wiki/Component-snippets#mixed-indent) check them out.
