### ISSUE TITLE
Bug: bubbles examples config not working

### ISSUE THREAD

**Issue by yanisdb** [nvim-lualine/lualine.nvim#420]
### Self Checks

- [ X] I'm using the latest lualine.
- [ X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
I copy pasted the bubbles config but it did not produce the expected result.

### Expected behaviou
I would like to make the sides round also as in the bubbles screenshot.

### Actual behaviour
The sides are not round
![Screenshot - Thu November 22-16-17](https://user-images.githubusercontent.com/17860659/140421331-1bc8e62a-5a60-430c-9794-beb1ea9a3d88.png)

### Minimal config to reproduce the issue
I tried to modify a little bit the given config according to what I found in the documentation but this did not work either.
```lua
require'lualine'.setup {
    options = {
        icons_enabled = true,
        section_separators = { left = '', right = ''},
        component_separators = { left = '|', right = '|'},
        disabled_filetypes = {"coc-explorer"},
        always_divide_middle = false,
        },
    sections = {
        lualine_a = {{ 'mode', separator = { left = '', right = ''}, padding = {left = 1}}},
        lualine_b = {'branch', 'diff',
        {'diagnostics', sources={'nvim_lsp', 'coc'}}},
        lualine_c = {'filename'},
        lualine_x = {'encoding', 'fileformat', 'filetype'},
        lualine_y = {'progress'},
        lualine_z = {'location'}
        },
    inactive_sections = {
        lualine_a = {'filename'},
        lualine_b = {},
        lualine_c = {},
        lualine_x = {},
        lualine_y = {},
        lualine_z = {}
        },
    tabline = {},
    extensions = {}
    }
```

**Comment by yanisdb** [comment]
Hello,
 I was able to make it work using this config:
```lua
local theme = require('lualine.themes.github')

require'lualine'.setup {
    options = {
        icons_enabled = true,
        theme = theme,
        section_separators = { left = '', right = ''},
        component_separators = { left = '|', right = '|'},
        disabled_filetypes = {"coc-explorer"},
        always_divide_middle = false,
        },
    sections = {
        lualine_a = {{ 'mode', separator = { left = '', right = ''}}},
        lualine_b = {'branch', 'diff',
        {'diagnostics', sources={'nvim_lsp', 'coc'}}},
        lualine_c = {'filename'},
        lualine_x = {'encoding', 'fileformat', 'filetype'},
        lualine_y = {'progress'},
        lualine_z = {{ 'location', separator = { left = '', right = ''}}},
        },
    inactive_sections = {
        lualine_a = {'filename'},
        lualine_b = {},
        lualine_c = {},
        lualine_x = {},
        lualine_y = {},
        lualine_z = {}
        },
    tabline = {},
    extensions = {}
    }
```
I just changed the way I pass the theme.
And this is the result I got:
![image](https://user-images.githubusercontent.com/17860659/140471997-4f2a902e-e37d-48c0-83c8-9f93132dc063.png)

But is it possible to make the background of the centre section transparent while keeping the bubbles ? If I set the `c` section to transparent, I get the desired transparency, but  the transitions disappears between `b` and `c` and between `x` and `y` and I don't get the bubble effect. See the following screenshot:
![image](https://user-images.githubusercontent.com/17860659/140472364-ec6b7e3d-8c13-4d44-8e83-15f2b81a1eab.png)
Here is the line I added:
```lua
theme.normal.c.bg = colors.transparent
```

Thank you

**Comment by shadmansaleh** [comment]
Does setting `theme = 'github'` work ?

> But is it possible to make the background of the centre section transparent while keeping the bubbles

You could try
```lua
theme.normal.c.bg = require'lualine.utils.utils'.extract_highlight_colors('Normal', 'bg')
```

**Comment by botsunny** [comment]
Sorry for necroing this but I seem to have the same problem as well. I wanted the lualine_a and lualine_z sections to have a rounded left and right side respectively. I imitated the working config and it's still not working.
Current config:
```
require'lualine'.setup {
  options = {
    icons_enabled = true,
    theme = 'nord',
    component_separators = { right = '|'},
    section_separators = { left = '', right = ''},
    disabled_filetypes = {},
    always_divide_middle = false,
  },
  sections = {
    lualine_a = {{ 'mode', separator = { left = '', right = ''}}},
    lualine_b = {branch},
    lualine_c = {{'filename', file_status = true, path = 0}}, 
    lualine_x = {'fileformat', 'filetype'},
    lualine_y = {'%L'},
    lualine_z = {{ 'location', separator = { left = '', right = ''}}},
    },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = {'filename'},
    lualine_x = {'location'},
    lualine_y = {},
    lualine_z = {}
  },
  tabline = {},
  extensions = {}
}
```
Output:
![image](https://user-images.githubusercontent.com/71499037/154829522-b705ae18-2ad8-426d-87e4-0bacc045ca25.png)

I noticed the way the theme is passed is different, but doing it that way just brings up an error
`module 'lualine.themes.github' not found`
I believe this module has to be imported first somehow? I'm kinda alien to how config files work so I apologise if this is a noob mistake.

**Comment by shadmansaleh** [comment]
@botsunny  Copy pasting the config you've provided works for me .
![Screenshot](https://user-images.githubusercontent.com/13149513/154830485-db7d6003-53ba-4044-a97e-b5152a6af392.png)

I'm guessing  you've pasted this line
```lua
local theme = require('lualine.themes.github')
```
in your config too while not having github colorscheme installed . Remove that line .

**Comment by botsunny** [comment]
That's not the case, unfortunately. I removed the line before taking the screenshot. Now I'm double checking and the line is not there. So weird. I tried changing fonts but it doesn't solve the issue as well. Could it be another plugin conflicting Lualine?
My preamble and plugins are as follows:
```
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors
set number
set clipboard^=unnamed,unnamedplus
set noshowmode
set noshowcmd

call plug#begin('~/.config/nvim/plugged')
Plug 'shaunsingh/nord.nvim'
Plug 'nvim-lualine/lualine.nvim'
Plug 'kyazdani42/nvim-web-devicons'
Plug 'xiyaowong/nvim-transparent'
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'github/copilot.vim'
call plug#end()
```

**Comment by shadmansaleh** [comment]
I can't see you getting that error unless you've put a requiring that module in your config . Try creating an isolated config with https://github.com/nvim-lualine/lualine.nvim/blob/master/scripts/nvim_isolated_conf.sh . Also did you get a backtrace with the error ?

**Comment by botsunny** [comment]
Sorry, I think I've been a little unclear about that. When I include this line `local theme = require('lualine.themes.github')`, I get an error. After that I removed the line (no error) and took this screenshot:
![image](https://user-images.githubusercontent.com/71499037/154832909-971dfa04-2953-451d-ad53-8a8990c92d97.png)

Either way, the left separator for Mode and the right separator for Location aren't being displayed.

**Comment by shadmansaleh** [comment]
Try removing 'xiyaowong/nvim-transparent'

**Comment by botsunny** [comment]
> Try removing 'xiyaowong/nvim-transparent'

This worked! Thank you so much!

**Comment by shadmansaleh** [comment]
Update to 605a30f2fe7c0922c0ebc890dec546134983b7f6 . Now it should work with `nvim-transparent` too
