### ISSUE TITLE
Feat: 

### ISSUE THREAD

**Issue by 0xRZ** [nvim-lualine/lualine.nvim#422]
### Requested feature

Is it possible to get rid of that little blue symbol right before section separator?

![selection_2021-11-05-15:28:54](https://user-images.githubusercontent.com/46892933/140510528-38e89dea-1b6f-49ab-9c06-7edc30e8dfd8.png)

Is there any highlight group that corresponds to it?

```lua
local mycode = {}
local colors = {
  black        = "#262626",
  white        = '#ffffff',
  red          = '#f44747',
  green        = '#619955',
  blue         = '#A89EFF',
  lightblue    = '#5CB6F8',
  yellow       = '#ffaf00',
}
mycode.normal = {
  b = {fg = colors.blue, bg = colors.black},
  a = {fg = colors.white, bg = colors.blue, gui = 'bold'},
  c = {fg = colors.white, bg = colors.black}
}
mycode.visual = {
  a = {fg = colors.black, bg = colors.lightblue, gui = 'bold'},
  b = {fg = colors.lightblue, bg = colors.black},
}
mycode.inactive = {
  b = {fg = colors.black, bg = colors.white},
  a = {fg = colors.white, bg = colors.gray, gui = 'bold'}
}
mycode.replace = {
  b = {fg = colors.yellow, bg = colors.black},
  a = {fg = colors.black, bg = colors.yellow, gui = 'bold'},
  c = {fg = colors.white, bg = colors.black}
}
mycode.insert = {
  a = {fg = colors.black, bg = colors.yellow, gui = 'bold'},
  b = {fg = colors.yellow, bg = colors.black},
  c = {fg = colors.white, bg = colors.black}
}
require'lualine'.setup {
  options = {
    theme = mycode,
    section_separators = { left = '', right = ''},
    component_separators = '',
	disabled_filetypes = {'help'},
  },
  sections = {
    lualine_a = {'mode'},
	lualine_b = { 'branch', 'diff', {'diagnostics', sources = {'nvim_lsp'}} },
    lualine_c = {'filename'},
    lualine_x = {'encoding', 'filetype'},
    lualine_y = {'progress'},
    lualine_z = {'location'}
  },
  extensions = {'quickfix', 'nvim-tree', 'fugitive'}
}
```

**Comment by shadmansaleh** [comment]
It's not caused by lualine. It's caused by the patched font you're using. It's not filling the complete space for the character.

**Comment by 0xRZ** [comment]
@shadmansaleh I'm using JetBrainsMonoNL Nerd Font from here https://github.com/ryanoasis/nerd-fonts. Also tried Fira Code right now and still saw that blue character inside separator. Which fonts handle that character propely?

**Comment by shadmansaleh** [comment]
I don't know to be honest . You could try picking you favorite font and try patching it with right size yourself. It might be a rendering issue in your terminal too . What terminal are you using ? I think I tried fira-code in kity and worked fine there.

**Comment by 0xRZ** [comment]
@shadmansaleh im using Alacritty

**Comment by shadmansaleh** [comment]
I haven't ever used alacritty so can't tell.

Maybe  this [one](https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf) from powerlevel10k I think it worked on other terminals too for me .

**Comment by 0xRZ** [comment]
@shadmansaleh Yeah, you right, this MesloLGS font doesn't show any gap before semicircle separator from my screenshot. Guess now ill need to patch jetbrainses font to replace that uniE0B4 character with MesloLGSes one. Thank you.
