### ISSUE TITLE
Feat: Remove gruvbox-material and everforest themes

### ISSUE THREAD

**Issue by sainnhe** [nvim-lualine/lualine.nvim#423]
### Requested feature

Hello, I'm the author of [gruvbox-material](https://github.com/sainnhe/gruvbox-material) and [everforest](https://github.com/sainnhe/everforest), I've added support for lualine recently, with support for various configuration options (e.g. `&background`, `g:gruvbox_material_background`, `g:gruvbox_material_statusline_style`, etc.).

The theme files are located in my repo, which I think might be conflict with the theme files in yours, since they have the same runtime path.

Could you remove the theme files in your repo? Thanks!

**Comment by shadmansaleh** [comment]
Glad to know you added support for lualine :)

No they won't conflict. Themes are loaded with [custom loader](https://github.com/nvim-lualine/lualine.nvim/blob/3f5cdc51a08c437c7705e283eebd4cf9fbb18f80/lua/lualine/utils/loader.lua#L204-L238) . it prefers theme files from external sources.

So when your colorschemes are installed lualine will load theme from your repo and when colorschemes aren't installed theme will be loaded from this repo.

**Comment by sainnhe** [comment]
That's fine, so it's unnecessary to remove the theme files in this repo.

I'm going to close this issue.
