### ISSUE TITLE
Bug: gruvbox theme

### ISSUE THREAD

**Issue by Tloe** [nvim-lualine/lualine.nvim#424]
I have been using lightline and https://github.com/shinchu/lightline-gruvbox.vim

The grey background for normal mode in lualine looks like its faded/disabled. This might just be me though. Can I change individual colors on the colortheme for lualine from my lua config?

**Comment by shadmansaleh** [comment]
Yes you can check out [customizing themes](https://github.com/nvim-lualine/lualine.nvim#setting-a-theme)

Also make sure you have true color support enabled (`termguicolors`)

**Comment by Tloe** [comment]
Ah I didn't see that fold. Thanks

**Comment by Tloe** [comment]
I tried setting a different bg color, but getting a green line in between the section and the seperator.
`theme.normal.a.bg = "#b8bb26"`

![lualine](https://user-images.githubusercontent.com/114614/140546940-1c75c23b-7029-46be-8e7e-52c99f4b606e.png)

**Comment by Tloe** [comment]
Actually thats there with any color. I've tried different fonts too..

**Comment by Tloe** [comment]
I'll close this and create a issue for that instead.
