### ISSUE TITLE
Bug: Line between section and separators

### ISSUE THREAD

**Issue by Tloe** [nvim-lualine/lualine.nvim#425]
Theres a line between the section and separators.

Running nvim 0.5.1 and latest version lualine
I use nerdfont SF Mono, but I have tried with normal fonts and other nerdfonts too and see the same issue.

![screenshot](https://user-images.githubusercontent.com/114614/140555287-aae22aaf-64eb-4db7-b68f-58589f9c9854.png)

**Comment by shadmansaleh** [comment]
duplicate #422 see https://github.com/nvim-lualine/lualine.nvim/issues/422#issuecomment-961888885
