### ISSUE TITLE
Nvim-tree plugin

### ISSUE THREAD

**Issue by bryant-the-coder** [nvim-lualine/lualine.nvim#427]
Hi, it's me again. Sorry to bother you again, how can i disable lualine in nvim-tree (plugin)?

**Comment by shadmansaleh** [comment]
Checkout [disabling lualine](https://github.com/nvim-lualine/lualine.nvim#disabling-lualine) . You can also try [nvim-tree extension](https://github.com/nvim-lualine/lualine.nvim#extensions)

Please read the docs before opening issues.

**Comment by bryant-the-coder** [comment]
Sorry again
