### ISSUE TITLE
Bug: Icons don't show 

### ISSUE THREAD

**Issue by ducdiepco** [nvim-lualine/lualine.nvim#430]
### Self Checks

- [x ] I'm using the latest lualine.
- [ ] I didn't find the issue in exsisting issues or prs.
Follow the instruction but the icons don't show. I'm not sure how can I fix this issue. thanks

![image](https://user-images.githubusercontent.com/3271568/140859918-2848daed-1c4a-4042-920e-d9235e338a98.png)

**Comment by shadmansaleh** [comment]
You need a nerd patched font.
