### ISSUE TITLE
Feat: would be nice to have a lsp status indicator

### ISSUE THREAD

**Issue by snaggen** [nvim-lualine/lualine.nvim#431]
### Requested feature
It would be nice to have a lsp status icon in the lsp diagnotics secition, that would indicate that lsp support is enabled, with different state for lsp doing work or being idle. 

### Motivation
I love that lualine have support for lsp indicators (err, warn, aso) out of the box. However, when opening a java file there are some status text being shown below lualine, but for a rust file (using rust-tools) there are no indication if things are working for a few seconds before the inlay hints are shown if you have them enabled. But for other files, like lua and json, there is no indication that you have lsp support enabled, until you get and error or warning. So things are quite inconsistent. Also it is not clear from the UI when the LSP is invoked and updated. So having a simple lsp status indicator would improve the user experience a lot.

**Comment by shadmansaleh** [comment]
duplicate #367 

see https://github.com/nvim-lualine/lualine.nvim/issues/367#issuecomment-938756266
