### ISSUE TITLE
Bug: Lualine not working with NerdTree 

### ISSUE THREAD

**Issue by Sakaar19** [nvim-lualine/lualine.nvim#437]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

</details>

**Comment by Sakaar19** [comment]
When i run nerdtree, lualine disappears
and when i close it, lualine appears again

**Comment by clason** [comment]
You skipped most of the template, which is there for a reason, so it's impossible to act on.

But are you sure "lualine disappears", and you are not just seeing the `inactive` form (since the nerdtree window becomes active and hence your original buffer is inactive)?

**Comment by Sakaar19** [comment]
I m seeing active but it lualine doesn't appear

**Comment by shadmansaleh** [comment]
Nerdtree has it's own [statusline](https://github.com/preservim/nerdtree/blob/eed488b1cd1867bd25f19f90e10440c5cc7d6424/doc/NERDTree.txt#L1117-L1128) . You're seeing that.

To disable nerdtrees statusline use
```vim
  let g:NERDTreeStatusline = -1
```
as part of your nerdtree config.

**Comment by Sakaar19** [comment]
Thanks
