### ISSUE TITLE
Bug: Tabline with No Name or plugin one

### ISSUE THREAD

**Issue by Mte90** [nvim-lualine/lualine.nvim#452]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
![immagine](https://user-images.githubusercontent.com/403283/143463546-005ecf3d-1f6c-48e5-9f7b-f6f19e406171.png)
![immagine](https://user-images.githubusercontent.com/403283/143463652-1d4ff73e-b062-409b-a0ce-bc05fdad48b0.png)

I have Chadtree or symbols-outline, they open up a sidebar and when I switch the focus the tab name changes. I would like that is kept the filename in the tab.

My settings
```
require('lualine').setup{
    options = {
        theme = 'papercolor_light',
        icons_enabled = true,
        disabled_filetypes = {'alpha', 'Outline', 'plugins','CHADTree'},
    },
    sections = {
        lualine_a = { { 'mode', fmt = string.upper } },
        lualine_b = {  },
        lualine_c = { { 'diff', icon = ''}, {
            'lsp_progress',
            display_components = {'lsp_client_name', 'spinner', { 'title', 'percentage', 'message' }},
            spinner_symbols = {'⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'},
          }
        },
        lualine_x = {},
        lualine_y = {  },
        lualine_z = { { 'diagnostics', sources = {'nvim_lsp', 'ale'}, sections = {'error', 'warn', 'info'} } }
    },
    tabline = {
        lualine_a = {{'tabs',
            max_length = vim.o.columns / 3,
            mode = 2
        }},
        lualine_b = {'filename', 'filetype'},
        lualine_c = {},
        lualine_x = {},
        lualine_y = {{ 'branch', icon = '' }},
        lualine_z = {{ 'nofixme#amount'}}
    },
    extensions = { 'fzf', 'chadtree', 'fugitive', 'quickfix' }
} 
```

**Comment by shadmansaleh** [comment]
>  I would like that is kept the filename in the tab.

what's filename in the tab? how do you define that ? How about when there are multiple windows with different files in a tab ? How do lualine know what names you want to be shown or not?

To me current behavior is expected behavior. It's suppose to show name of active buffer.

You can always write a function or a custom component for your desired behavior.

**Comment by Mte90** [comment]
> But it seemed you want filename component not to change when you jump to chadtree....

Yes basically this is the idea, in this way it is kept the filename also on switching tabs. I don't know what is the right way but maybe check the number of buffers in that window and took the central one or do a parameter where you define the filetype to ignore. With the last one basically if the buffer name is `OUTLINE` don't change the tab text.

**Comment by shadmansaleh** [comment]
> maybe check the number of buffers in that window and took the central one

An window is just a view into buffer, multiple windows can contain same buffer . Also when you open a vertical split like opening chadtree one window is in left and other on right visually but there's no way to retrieve that layout info as I know of and center makes no sense there anyway.

> do a parameter where you define the filetype to ignore. With the last one basically if the buffer name is OUTLINE don't change the tab text

This ignoring doesn't make sense on statusline you'd only want that behavior in tabline .

To me this adds a lot of complexity for niche usecase so lualine won't be supporting it out of the box. You can implement it in you config as function or custom component.

for example as custom component you can do something like:
```lua
local tab_fname = require('lualine.components.filename'):extend()
function tab_fname:update_status(is_focused)
  if not vim.tbl_contains(self.options.disabled_filetypes, vim.bo.ft) then
    self.last_fname = self.super.update_status(self, is_focused)
  end
  return self.last_fname or ''
end
```

then use it in your tabline
```lua
tabline = {
   lualine_b = {tab_fname},
}
```

**Comment by Mte90** [comment]
Seems a good solution, I am trying to understand how to extend the tabs module to achieve it.
I am not a Lua expert and this code doesn't work:
```
local tab_fname = require('lualine.components.tabs.init'):extend()
function tab_fname:Tab:label(is_focused)
  if not vim.tbl_contains(self.options.disabled_filetypes, vim.bo.ft) then
    self.last_fname = self.super.update_status(self, is_focused)
  end
  return self.last_fname or ''
end
```

**Comment by shadmansaleh** [comment]
Overwrite the label function.
```lua
local old_tab_label = require('lualine.components.tabs.tab').label
_G.lualine_tabs_last_fname = {}
require('lualine.components.tabs.tab').label = function(self)
  if not vim.tbl_contains(self.options.disabled_filetypes, vim.bo.ft) then
    _G.lualine_tabs_last_fname[self.tabnr] = old_tab_label(self)
  end
  return _G.lualine_tabs_last_fname[self.tabnr] or ''
end
``

**Comment by Mte90** [comment]
It is not clear how to add it in the settings:

```
    tabline = {
        lualine_a = {{tab,
            max_length = vim.o.columns / 3,
            mode = 2
        }},
```
I get this 
![immagine](https://user-images.githubusercontent.com/403283/143851394-9988e924-3a00-4bc5-b58f-ea25916b1409.png)

If I use:

```
    tabline = {
        lualine_a = {{'tabs',
            max_length = vim.o.columns / 3,
            mode = 2
        }},
```
I think that the new code is not executed.

**Comment by Mte90** [comment]
Any help for this?
I am not a Lua expert but I think that there is something wrong here.

**Comment by shadmansaleh** [comment]
> Any help for this?
I am not a Lua expert but I think that there is something wrong here.

what's wrong? I'm not sure what you're trying to do [here](https://github.com/nvim-lualine/lualine.nvim/issues/452#issuecomment-981502071)

**Comment by Mte90** [comment]
I am trying to use your code for tabs. It isn't needed to specify the function in the lualiane parameters as before?

**Comment by shadmansaleh** [comment]
> It isn't needed to specify the function in the lualiane parameters as before?

No just put it before your lualine setup call and have `'tabs'` in your tabline config.

**Comment by Mte90** [comment]
Yes in that works, I think that Lua hate me 😆
