### ISSUE TITLE
Feat: different colors for tabline active, modified, hidden, inactive buffers

### ISSUE THREAD

**Issue by petobens** [nvim-lualine/lualine.nvim#467]
Now that  lualine has native tabline support I was wondering whether it's possible to have theme settings (i.e different colors) for selected, modified, hidden, inactive buffers shown on the tabline. airline-vim has something like this and be customized as per: https://github.com/petobens/colorish/blob/master/autoload/airline/themes/onedarkish.vim#L68

**Comment by shadmansaleh** [comment]
lualine already has support for selected/active & inactive ( See the [buffers_color](https://github.com/nvim-lualine/lualine.nvim#buffers-component-options) option). Modified status is is shown through a symbol .

Airline has different colors for every component based on buffers modified status. Lualine doesn't do that.

Is it useful to show hidden buffers in buffers ? Actually what buffers are usually hidden buffers ? I don't think I've ever hidden a file-buffer that I was using.

**Comment by petobens** [comment]
> lualine already has support for selected/active & inactive ( See the buffers_color option). Modified status is is shown through a symbol .

Can you introduce an option to have a different color for a modified buffer (rather than icon)?

> Is it useful to show hidden buffers in buffers 

I meant non-visible ones. Generally I want to distinguish between buffers that are currently visible from those that aren't.

**Comment by shadmansaleh** [comment]
> Can you introduce an option to have a different color for a modified buffer (rather than icon)?

No . I'll not . I've already been asked about it for filename component.

> I meant non-visible ones. Generally I want to distinguish between buffers that are currently visible from those that aren't.

Do you mean buffers that are attached to no window or attached to window in different tabpage ?

Actually buffers & tabs components are meant to provide basic tabline support. I'd still advocate buffer/tabline plugins like [nvim-bufferline](https://github.com/akinsho/nvim-bufferline.lua) for more advanced use cases . Tabline isn't main focus of lualine.

**Comment by petobens** [comment]
> Do you mean buffers that are attached to no window or attached to window in different tabpage ?

I guess the next imagine can clarify a bit: basically a want to be able to have a different highlight for the `non-visible.lua` buffer (which is open but not visible in any split)
![image](https://user-images.githubusercontent.com/2583971/145082048-e0c0f4ea-0b32-47c6-9f3a-c5611db6d96d.png)

> No . I'll not . I've already been asked about it for filename component.

I'm asking this for i) a matter of consistency/symmetry: if we have buffer colors for `active` and `inactive` buffers we might as well have one for `modified` rather than introducing an icon and ii) i believe changing colors give a better/clear indicator that a buffer has been modified (rather than a small icon). If you can reconsider the request that will be greatly appreciated.

**Comment by shadmansaleh** [comment]
Ok you can overwrite the [render](https://github.com/nvim-lualine/lualine.nvim/blob/d68631d2c02bd31d937349d739c625cc81dd9ac1/lua/lualine/components/buffers/buffer.lua#L49-85) in your config and have those color changing effects .
```lua
require 'lualine.components.buffers.buffer'render = function(self)
  -- your implementation
end
```

I'll not be providing these out of the box. Like I said tabs&buffers components are for basic support for more advanced uses users should use buffer/tabline specific plugins.

> a matter of consistency/symmetry: if we have buffer colors for active and inactive buffers we might as well have one for modified rather than introducing an icon

active and inactive is there because the default built-in taline has different color for active and inactive tabs it doesn't have different color for modified . If you can convince bram that built-in tabline should have it to make it more consistent/symmetric then I'll add it 😆 . Different color for modified buffer is something airline does . Being one two one with airline isn't a goal instead keeping feature creep out is (where airline failed terribly imo) .

> i believe changing colors give a better/clear indicator that a buffer has been modified

Like I said it's something that has been proposed before . But I don't like it. IMO it's distracting if something just keeps changing color while you type .

**Comment by petobens** [comment]
> Ok you can overwrite the render in your config and have those color changing effects . 

Thanks! Using the following in my config:
```lua
local function hl_buffer_state(bufnr)
    local hl_group = ''
    local buffers = vim.fn.tabpagebuflist(vim.fn.tabpagenr())
    local mod_buf = (vim.fn.getbufvar(bufnr, '&modified') ~= 0)
    local cur_buf = vim.fn.bufnr('%')

    if cur_buf == bufnr then
        if mod_buf then
            hl_group = 'tabmod'
        else
            hl_group = 'tabsel'
        end
    else
        if mod_buf then
            hl_group = 'tabmod_unsel'
        elseif vim.fn.index(buffers, bufnr) > -1 then
            hl_group = 'tabvis'
        else
            hl_group = 'tabhid'
        end
    end
    hl_group = 'lualine_' .. hl_group .. '_tabline'
    return '%#' .. hl_group .. '#'
end

-- Override tabline function
require('lualine.components.buffers.buffer').render = function(self)
    local apply_padding = require('lualine.components.buffers.buffer').apply_padding

    local name = self:name()
    if self.ellipse then
        name = '...'
    else
        name = string.format('%s %s %s', self.bufnr, name, self.icon)
    end
    name = apply_padding(name, self.options.padding)
    self.len = vim.fn.strchars(name)

    local line = string.format('%%%s@LualineSwitchBuffer@%s%%T', self.bufnr, name)
    local buf_hl_group = hl_buffer_state(self.bufnr)
    line = buf_hl_group .. line

    if not self.first then
        local sep_before = self:separator_before()
        line = sep_before .. line
        self.len = self.len + vim.fn.strchars(sep_before)
    end
    return line
end
```
and the next lines in my theme:
```lua
onedarkish.tabline = {
	tabsel = {fg = c.bg, bg = c.light_blue, gui = 'bold'},
	tabmod = {fg = c.bg, bg = c.red, gui = 'bold'},
    tabvis = {fg = c.white, bg = c.special_grey},
	tabhid = {fg = c.gray, bg = c.cursor_grey},
    tabmod_unsel = {fg = c.bg, bg = c.orange, gui = 'bold'},
}
```
I mostly get what I want with one slight issue:

![image](https://user-images.githubusercontent.com/2583971/145591501-fc88acdb-6568-49a1-b7cd-8e0644eea0d5.png)

How can I make the separator color blend naturally between the different segments? Help/advice is greatly appreciated!

> support for more advanced uses users should use buffer/tabline specific plugins.

I actually tried barbar and bufferline but there is no easy way to change the look and feel of those plugins to match lualine "powerline" look.

**Comment by shadmansaleh** [comment]
> How can I make the separator color blend naturally between the different segments? Help/advice is greatly appreciated!

You'll have to use section seperator likes symbols between two different colors . Those symbols cover half of the space so you can set one color as fg and other as bg to create smooth transition . The color management is handled by lualine if you use %s{sep} & %S{sep} like patterns . Look [here](https://github.com/nvim-lualine/lualine.nvim/blob/3a17e2dbca8accbd3733b4fb076f01e00a456ba4/lua/lualine/components/buffers/buffer.lua#L87-L105) to see how builtin tabline handles color transition .

**Comment by petobens** [comment]
Can you give me some extra pointers? I can't quite figure out how to implement it. Thanks (and sorry for the bothering)

**Comment by shadmansaleh** [comment]
You need to make sure when a hidden buffer and a non-hidden buffer is next to each other `self:separator_before()` returns `%S{}` . And when two hidden or two non-hidden buffers are next to each other `self:separator_before()` returns ``

In builtin case color change only occurs for active_buffer . So we  mark the active buffer and the buffers sorrounding that to switch seperators.

https://github.com/nvim-lualine/lualine.nvim/blob/5596c2a25a49ca235613c804169b9063e20b05f5/lua/lualine/components/buffers/init.lua#L83

**Comment by petobens** [comment]
Hi @shadmansaleh I eventually managed to get this working with your pointers but unfortunately with the recent highlight changes I'm getting the following error:
```
E5108: Error executing lua ...pack/packer/start/lualine.nvim/lua/lualine/highlight.lua:310: invalid value (nil) at index 2 in table for 'concat'
stack traceback:
        [C]: in function 'concat'
        ...pack/packer/start/lualine.nvim/lua/lualine/highlight.lua:310: in function 'create_component_highlight_group'
        ...pack/packer/start/lualine.nvim/lua/lualine/highlight.lua:209: in function 'create_highlight_groups'
        ...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:251: in function 'setup_theme'
        ...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:285: in function 'reset_lualine'
        ...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:304: in function <...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:300>
```
I guess this is because I defined a custom highlight group like this: https://github.com/petobens/dotfiles/blob/1aac09bc49b60abd18fdb9914a93cb89a01acd9b/nvim/lua/lualine/components/buffertab/buffer.lua#L44-L63 which I then configure in my theme like: https://github.com/petobens/dotfiles/blob/1aac09bc49b60abd18fdb9914a93cb89a01acd9b/nvim/lua/lualine/themes/onedarkish.lua#L48-L54

Any advice on how to get things working again? Thanks in advance

**Comment by shadmansaleh** [comment]
See if  https://github.com/nvim-lualine/lualine.nvim/commit/21fdf7b9faf4e62cd27c60574f3e48ad640dc5fc fixed it.

I'll reconsider this feature . If you want you can open a pr . Though the colors should be taken in buffers_color option and if hidden / modified color isn't set by user it should act like current buffers component .

**Comment by petobens** [comment]
> See if 21fdf7b fixed it.

It does! Thank you :)
