### ISSUE TITLE
How can I fix the gap at the begging and the end of splits

### ISSUE THREAD

**Issue by rzksobhy78** [nvim-lualine/lualine.nvim#469]
![Mon Dec  6 17:27:50 EET 2021](https://user-images.githubusercontent.com/94202082/144873817-e570ecb9-3d57-4ab5-8665-2bf611057e9b.png)

Why there is a gap at the begging and the end of each split

**Comment by shadmansaleh** [comment]
I think it's a vim & neovim limitation and no way to fix from plugin.

Try opening nvim with `nvim --clean`
then run the following commands
```vim
:hi test_hl ctermbg=red
:set stl=%#test_hl#
:vsp
```

Notice there's that gap between splits.
So I don't think it can be fixed from lualines side.

**Comment by rzksobhy78** [comment]
I know but is there is any solution

**Comment by shadmansaleh** [comment]
I thought you got it resolved https://www.reddit.com/r/neovim/comments/ra7cbn/comment/hniav0d/ .

Wasn't the reddit post from you ?

**Comment by rzksobhy78** [comment]
that fixed barbar but didn't fix lualine

![Tue Dec  7 14:11:10 EET 2021](https://user-images.githubusercontent.com/94202082/145026815-a7f5c6d1-771a-4af4-b9f9-a20042b3bd4f.png)

**Comment by rzksobhy78** [comment]
I think the problem with lualine is different there is a gap between splits
![Tue Dec  7 14:14:19 EET 2021](https://user-images.githubusercontent.com/94202082/145027212-e6efdbb4-ee15-4362-946c-adb5f77dc6bd.png)

**Comment by shadmansaleh** [comment]
> that fixed barbar but didn't fix lualine

Then my older reply still applies. Lualine doesn't control how splits are drawn neovim/vim does. And I'm not aware of any fix for this.

**Comment by rzksobhy78** [comment]
ok thanks for answering anyway
