### ISSUE TITLE
Bug: Displays the linux icon when on MacPro M1

### ISSUE THREAD

**Issue by EdmundsEcho** [nvim-lualine/lualine.nvim#472]
NVIM v0.7.0-dev+653-g7229afcd6
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by edmund@Edmunds-MacBook-Pro.local

### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### Expected behaviour

Display the macOS icon

### Actual behaviour

Displays the linux penguin

**Comment by shadmansaleh** [comment]
I believe you're talking about `fileformat` component . It doesn't show which os you're using rather how lines end (with \\n or \\r or \\r\\n) in the buffer you're using . See `:h 'fileformat'`
