### ISSUE TITLE
Feat: Icons per file type

### ISSUE THREAD

**Issue by bryant-the-coder** [nvim-lualine/lualine.nvim#475]
Is it possible to add like when i open a lua file... then there will be a lua icon. Html file with html icon. Is it possible?

**Comment by shadmansaleh** [comment]
`filetype` component already supports icons by default .
You need to install [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons) for that to work.

If you want just the icon you can use [icon_only option](https://github.com/nvim-lualine/lualine.nvim#filetype-component-options)

**Comment by bryant-the-coder** [comment]
I mean beside filename...

**Comment by shadmansaleh** [comment]
> I mean beside filename...

No filename component doesn't have icons out of the box . But you can create a custom filename component with that functionality .

**Comment by bryant-the-coder** [comment]
like how?

**Comment by shadmansaleh** [comment]
> like how?

You can just reuse the `apply_icon` method from filetype component in your custom filename component to easily get icons with filename.

```lua
local my_filename = require('lualine.components.filename'):extend()
my_filename.apply_icon = require('lualine.components.filetype').apply_icon

require'lualine'.setup {
  lualine_c = {{my_filename, colored = true}},
}
```

**Comment by bryant-the-coder** [comment]
thanks

**Comment by dave-kennedy** [comment]
You also need to set `my_filename.icon_hl_cache = {}` or remove `colored = true` from options.
