### ISSUE TITLE
Can I call nvim colors in lualine?

### ISSUE THREAD

**Issue by der-zonk** [nvim-lualine/lualine.nvim#477]
Please excuse my dumbness I am just a hobby nerd!

So while I had no problem installing lualine I hit an insurmountable obstacle.
I'm trying to customize the colors.
The readme makes it look quite simple to at least have colors in hex value set, but I'd like to get my colors from nvim.

But firstly, I can't even seem to get a custom theme set.
My init.lua looks like this
```
local custom_pywal = require'lualine.themes.pywal'
custom_pywal.normal.c.bg = '#282828'

require'lualine'.setup {
  options = {
    -- theme = 'auto',
    theme = 'custom_pywal',
    icons_enabled = true,
    component_separators = { left = '', right = ''},
    section_separators = { left = '', right = ''},
    disabled_filetypes = {},
    always_divide_middle = true,
  },
  sections = {
    lualine_a = {'mode'},
    lualine_b = {'branch', 'diff',
                  {'diagnostics', sources={'nvim_diagnostic', 'coc'}}},
    lualine_c = {'filename'},
    lualine_x = {'encoding', 'fileformat', 'filetype'},
    lualine_y = {'progress'},
    lualine_z = {'location'}
  },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = {'filename'},
    lualine_x = {'location'},
    lualine_y = {},
    lualine_z = {}
  },
  tabline = {},
  extensions = {}
}
```

LuaLineNotices tells me

> Theme `custom_pywal` not found, falling back to `auto`. Check if spelling is right.

I tried setting the colors with highlight
`hi  lualine_c_normal ctermbg=1`
which works in command mode but it does not work when set in an init.lua no matter at what position it sits

> Theme structure is available here

leads to how to contribute and nothing about theme structure.

I figured I could go into sections and do something like color = {bg = 1} but there has to be an easier way..
But I just have no clue how to troubleshoot here because I'm not a dev by any means..
I'd like something like for custom_pywal.normal.c.bg use ctermcolor or something..
If I over-read something obvious please keep in mind 90% of the stuff here is new stuff to me..

**Comment by shadmansaleh** [comment]
Custom themes are table not string. The rest you're doing fine .
```diff
- theme = 'custom_pywal',
+ theme = custom_pywal,
```
> leads to how to contribute and nothing about theme structure.

Right. Those were moved to wiki but the link wasn't updated.
https://github.com/nvim-lualine/lualine.nvim/wiki/Writting-a-theme#theme-example

**Comment by der-zonk** [comment]
Wow.. thanks.. auto was also in single quote so I just did the same.. thanks..
I figured now I can also just use cterm_colors there.. Wish I knew that earlier.. :D
