### ISSUE TITLE
Bug: 'vim.lsp.diagnostic.get_count()' is deprecated

### ISSUE THREAD

**Issue by da-moon** [nvim-lualine/lualine.nvim#479]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

- install neovim `v0.7.0-dev` .
- Open any file.

### Expected behaviour

No warnings should be shown

### Actual behaviour

![image](https://user-images.githubusercontent.com/17126777/145571297-342ed4bc-0cb8-4f4a-a79e-be1d79a56094.png)

**Comment by da-moon** [comment]
@shadmansaleh I took the liberty to address this in a minor PR  #480

**Comment by shadmansaleh** [comment]
> @shadmansaleh I took the liberty to address this in a minor PR #480

Thanks appreciate it, but this issue has already been resolved
in 4231b63196a0dcc94e62e914d2b768ef31b5beb7 . Update lualine and change your diagnostics source to `nvim_diagnostic` and the warning should be gone.

**Comment by da-moon** [comment]
Got it
