### ISSUE TITLE
Icons not working in windows

### ISSUE THREAD

**Issue by andreadev-it** [nvim-lualine/lualine.nvim#482]
### Self Checks

- [x] I'm using the latest lualine.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

I've installed nvim v. 0.6.0, and I used a very minimal installation of lualine, here it is my init.vim file:
```
call plug#begin('~/AppData/Local/nvim-data/plugins')
Plug 'nvim-lualine/lualine.nvim'
Plug 'kyazdani42/nvim-web-devicons'
Plug 'EdenEast/nightfox.nvim'
call plug#end()

" Plugins configuration
lua << END
require'lualine'.setup()
END

" Editor configuration
colorscheme nightfox
```
### Expected behaviour
It should show the icons in the line

### Actual behaviour
![nvim-lualine](https://user-images.githubusercontent.com/68549121/145612767-9083dfbd-2289-4515-a5d7-49ddfd3d8009.png)

As you can see, all icons are replaced with blank boxes. I think that it might be missing a font or something like that, but I couldn't find any help to get this fixed on windows, and don't know where to begin.

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>
  I've installed neovim through chocolatey:

```choco install neovim```

  Then installed vim-plug using the documentation on their github pages and lualines using the docs in the README.
  I'm using Windows Terminal as the terminal emulator on Windows.
</details>

**Comment by shadmansaleh** [comment]
You need nerd-patched fonts for icons to work . But I'm not a windows user so sorry can't help how to set them up in windows.

**Comment by andreadev-it** [comment]
Thank you for your help!
With the info you gave I was able to fix it in this way:
- I went to the nerd fonts github project (https://github.com/ryanoasis/nerd-fonts)
- Downloaded the font I wanted from the "patched fonts" folder (FiraCode Mono in my case) in both regular, medium and bold
- Right clicked on the otf files and choose "install"
- Went into the Windows Terminal settings and changed the font for all profiles
Now everything shows fine 🙂

![nvim-lualine](https://user-images.githubusercontent.com/68549121/145673918-ffe69d16-68be-4c8c-be0e-a7a40d9e2751.png)

**Comment by shadmansaleh** [comment]
Glad you got it fixed :)

**Comment by nzbart** [comment]
@andreadev-it thanks for coming back and posting detailed instructions - they saved me a lot of time!
