### ISSUE TITLE
Feat: Support for spell checking

### ISSUE THREAD

**Issue by AndreaDiPietro92** [nvim-lualine/lualine.nvim#487]
Could be useful the support for the "Spell checking" of NeoVim. In the others status line, when the spell checking is active the status bar has the format

```
Hello.txt [text][utf8][unix][en_US.utf8]
```
The last part (` [en_US.utf8] `) appears only when the checking is on.

**Comment by shadmansaleh** [comment]
I think this can be easily done with a [function component](https://github.com/nvim-lualine/lualine.nvim#lua-functions-as-lualine-component) in config .

**Comment by AndreaDiPietro92** [comment]
I've tried adding `lualine_c = {'%{&spell}'}` but obtain only 0 a 1 (for inactive and active). 
I'm sorry but I'm not familiar with lua programming.

**Comment by shadmansaleh** [comment]
You can try something like

```lua
lualine_c = {function()
    if vim.bo.spell == 1 then
       return '[en_US.utf8]'  -- Probably should return based on which spell file being used not hardcoded value.
    end
    return ''
  end
}
```

This would work too but not recomended
```lua
lualine_c = {"%{&spell?'[en_US.utf8]' : '[NoSpell]'}"}
```

**Comment by reverseila** [comment]
@shadmansaleh Probably this:

```lua
local function spell()
  if vim.wo.spell == true then -- Note that spell is a window option, so: 'wo'
    return 'spell [' .. vim.bo.spelllang .. ']'
  end
  return ''
end

-- ~~~
    lualine_x = { spell, 'encoding', 'fileformat', 'filetype' },
-- ~~~            ^^^^^
```
