### ISSUE TITLE
How to add ObsessionStatus from `tpope/vim-obsession`?

### ISSUE THREAD

**Issue by nyngwang** [nvim-lualine/lualine.nvim#489]
I want to add [`tpope/vim-obsession`](https://github.com/tpope/vim-obsession) status to a section by this plugin, but I don't know how to do so.

In `help obsession-status` it says:

> Add `%{ObsessionStatus()}` to `'statusline'`, `'tabline'`, or `'titlestring'` to get an indicator when Obsession is active or paused.

then I tried with the following settings but it doesn't work.

```
use {
  'nvim-lualine/lualine.nvim',
  requires = {
    'kyazdani42/nvim-web-devicons'
  },
  config = function()
    require'lualine'.setup {
      options = {
        theme = 'palenight', -- Purple
        disabled_filetypes = {
          "NvimTree"
        },
      },
      sections = {
        lualine_z = {'v:lua.ObsessionStatus()'}
      }
    }
  end
}
```

**Comment by shadmansaleh** [comment]
Did you try puttimg just `ObsessionStatus` ?

like
```lua
lualine_z = {'ObsessionStatus'}
```

**Comment by nyngwang** [comment]
> Did you try puttimg just ObsessionStatus ? [...]

Yes, I did try that while it doesn't work. I've resolved this problem with this config (and some frustration :/ ):

```
sections = {
  lualine_z = { "vim.fn.ObsessionStatus('Ob', 'X')" }
}
```

I hope this will help other people, too.

Preview the result:

<img src="https://user-images.githubusercontent.com/24765272/145811044-0cb8b2fb-51a8-4d5c-b704-27bf6da4d3cd.png" width="400">

**Comment by shadmansaleh** [comment]
Can you try with type set to `vim_fun` ?

```lua
  lualine_z = {{'ObsessionStatus', type='vim_fun'}}
```

**Comment by shadmansaleh** [comment]
I just downloaded Obsession and it works fine just with

```lua
lualine_z = {'ObsessionStatus'}
```

It shows [$] on statusline when obsession is active and [S] on satusline when it's not . Is it suppose to do anything different ?

**Comment by nyngwang** [comment]
> I just downloaded Obsession and it works fine just with
> 
> ```lua
> lualine_z = {'ObsessionStatus'}
> ```
> 
> It shows [$] on statusline when obsession is active and [S] on satusline when it's not . Is it suppose to do anything different ?

But in this way how can I provide parameters?

**Comment by shadmansaleh** [comment]
> But in this way how can I provide parameters?

You can't in that way . The input is being unterpreted a viml function name, So no args there .

I'd recommend you use a lua function that handles it instead 

```lua
sections = {
  lualine_z = { function() return vim.fn.ObsessionStatus('Ob', 'X') end }
}
```

Do we consider this issue resolved ?

**Comment by nyngwang** [comment]
Thanks! Let me close this issue.
