### ISSUE TITLE
When working in a non git dir, please ignore git branch error.

### ISSUE THREAD

**Issue by jackhub** [nvim-lualine/lualine.nvim#490]
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua ...ualine.nvim/lua/lualine/components/branch/git_branch.lua:82: attempt to index local 'git_dir' (a nil value)
stack traceback:
        ...ualine.nvim/lua/lualine/components/branch/git_branch.lua:82: in function 'find_git_dir'
        [string ":lua"]:1: in main chunk
E5108: Error executing lua ...ualine.nvim/lua/lualine/components/branch/git_branch.lua:82: attempt to index local 'git_dir' (a nil value)

**Comment by shadmansaleh** [comment]
Do you have a .git file in the folder / one of parent folder ? If so why ?

**Comment by jackhub** [comment]
> 

Sometime I need to work with some test codebases, I don't use git in those cases.

**Comment by shadmansaleh** [comment]
> Sometime I need to work with some test codebases, I don't use git in those cases.

But why do you have a `.git` file if not using git ?

**Comment by tristan957** [comment]
Use `git rev-parse` to check if currently in a repo. Looking for a .git folder isn't the best way.
