### ISSUE TITLE
Bug:  Diagnostics default HL groups are not applied to status line

### ISSUE THREAD

**Issue by cpkio** [nvim-lualine/lualine.nvim#499]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in exsisting issues or prs.

I'm using nvim 0.5.1 in terminal 16 colors mode (using `cterm=` variables).

## Actual

This config does not catch up with the colors.

```
    lualine_b = { { 'branch' }, { 'diagnostics',
      sources = { 'nvim_lsp' },
      colored = true,
      symbols = { error = 'E:', warn = 'W:', info = 'I:', hint = 'H:' },
    } },
```

HL groups `LspDiagnosticsDefaultHint`, `LspDiagnosticsDefaultError`, `LspDiagnosticsDefaultWarning` and `LspDiagnosticsDefaultInformation` are defined like
`LspDiagnosticsDefaultError xxx ctermfg=9 guifg=#e06c75` (no bg).

Lualine highlights are like `lualine_b_diagnostics_error_normal xxx ctermfg=131 guifg=#be5046` (`LspDiagnosticsDefaultError` not applied obviously).

## Expected

Highlight groups applied to status line as is.

**Comment by shadmansaleh** [comment]
`DiagnosticError` is actually preferred over `LspDiagnosticsDefaultError` see [here](
https://github.com/nvim-lualine/lualine.nvim/blob/3a17c8f05aae1f148b8af595b46fea18b74d0573/lua/lualine/components/diagnostics/config.lua#L27) . You have `DiagnosticError` hl group defined that's why lualine highlights are based on that.

**Comment by cpkio** [comment]
`Diagnostic*` is not defined:
![2021-12-19_200248](https://user-images.githubusercontent.com/1917113/146683899-75fb4fe7-355e-431f-b133-f7eafe541fa3.png)

**Comment by shadmansaleh** [comment]
You're on neovim-5.1 release right ?

Those hl groups are defined in neovim . Diagnostic* hl groups are defined within neovim from 0.5.1. So even if your colorscheme doesn't define it you should still have them . I can't understand how you can not have them 🤷‍♂️ as builtin hl groups are not possible to delete as far as I know 😑

**Comment by cpkio** [comment]
I've added an extra `)` to the last line of yours.
```
DiagnosticError= nil
LspDiagnosticsDefaultError= #be5046
DiffDelete= #be5046
ExtractList= #be5046
```

**Comment by shadmansaleh** [comment]
Also run following

```vim
:hi LspDiagnosticsDefaultError
:lua print(vim.inspect(vim.api.nvim_get_hl_by_name('LspDiagnosticsDefaultError', true)))
:lua print(vim.inspect(vim.api.nvim_get_hl_by_name('LspDiagnosticsDefaultError', false)))
```

> The thing is I'd like ctermfg, not hex colors.

lualine doesn't directly handle cterm colors . Instead all colors are handled as hex colors . When termguicolors are disabled cterm colors are generated from hex colors by [color_utils](https://github.com/nvim-lualine/lualine.nvim/blob/master/lua/lualine/utils/color_utils.lua) module .

**Comment by cpkio** [comment]
`LspDiagnosticsDefaultError xxx ctermfg=9 guifg=#e06c75` which is defined by me in my color scheme.

```
{
  foreground = 14707829
}
```
```
{               
  foreground = 9
}
```

**Comment by shadmansaleh** [comment]
```vim
:lua print(string.format('#%06x', 14707829))
```

**Comment by cpkio** [comment]
`#e06c75`

**Comment by shadmansaleh** [comment]
Unless luajit went nuts I can't see how you can get '#be5046' from 
 [extract_highlight_colors](https://github.com/nvim-lualine/lualine.nvim/blob/3a17c8f05aae1f148b8af595b46fea18b74d0573/lua/lualine/utils/utils.lua#L11-L28) . As you can see it's just calling nvim_get_hl_by_name + the string conversion I gave you earlier that resulted in #e06c75 .

**Comment by shadmansaleh** [comment]
> which is defined by me in my color scheme.

Is it possible lualine is getting initialized before your colorscheme ?

**Comment by cpkio** [comment]
Ah, shit. You're right :( Worth noting in the readme possibly.

**Comment by shadmansaleh** [comment]
> Worth noting in the readme possibly.

Usually it shouldn't mater as lualine [refreshes](https://github.com/nvim-lualine/lualine.nvim/blob/3a17c8f05aae1f148b8af595b46fea18b74d0573/lua/lualine.lua#L252) it self on `ColorScheme` event .
But I assume you aren't using `:colorscheme` command to enable your colorscheme .
