### ISSUE TITLE
Feat: avoid splitting statusbar

### ISSUE THREAD

**Issue by grimgort** [nvim-lualine/lualine.nvim#504]
Hello,

I would like to know if there is a way or an option to avoid that the statusbar is split in 2 pieces.  With a split, it becomes unreadable. I would need one that does the whole screen all the time.
Avoid:
![image](https://user-images.githubusercontent.com/44238325/147088090-89b25c1e-23d2-44fd-9845-6028085641d2.png)
wanted : 
![image](https://user-images.githubusercontent.com/44238325/147088159-e0361e72-c4f2-4858-8b0b-dbe6bf807916.png)

**Comment by shadmansaleh** [comment]
It's not fixable by lualine . This is how neovim draws statusline . See https://github.com/neovim/neovim/issues/9342

You can use [floatline.nvim](https://github.com/nvim-pack/floatline.nvim) as workarround.

**Comment by grimgort** [comment]
Ok, thanks a lot.

i have migrated to : https://github.com/windwp/windline.nvim

**Comment by rodhash** [comment]
> It's not fixable by lualine . This is how neovim draws statusline . See [neovim/neovim#9342](https://github.com/neovim/neovim/issues/9342)
> 
> You can use [floatline.nvim](https://github.com/nvim-pack/floatline.nvim) as workarround. For example install floatline add the following after your lualine config.
> 
> ```lua
> function _G.LualineStatusLine()
>   local ok, stl = pcall(require('lualine').statusline)
>   if not ok then
>     vim.opt.stl = '%f%=%l,%v         %p%% '
>     error(stl)
>   end
>   return stl
> end
> 
> require('floatline').setup {
>   status = function()
>     return [=[%{%&stl == "%!v:lua.RStatusline()" ? luaeval("_G.LualineStatusLine()") : &stl%}]=]
>   end,
> }
> 
> vim.cmd [[
>   hi RStatusActive guifg=#51a0cf
>   hi RStatusInActive guifg=#266269
> ]]
> _G.RStatusline = function()
>   local stl_content = vim.fn.pathshorten(vim.fn.expand '%:~:.')
>   local num_of_dash = vim.fn.winwidth(0) - vim.fn.strdisplaywidth(stl_content)
>   stl_content = string.rep('_', num_of_dash / 2) .. stl_content .. string.rep('_', num_of_dash - num_of_dash / 2)
>   if tonumber(vim.g.actual_curwin) == vim.fn.win_getid() then
>     return '%#RStatusActive#' .. stl_content
>   end
>   return '%#RStatusInActive#' .. stl_content
> end
> vim.go.stl = '%!v:lua.RStatusline()'
> ```

Thank you!

**Comment by nyngwang** [comment]
For future readers: The global statusline feature had been merged one year ago: https://github.com/neovim/neovim/pull/17266, which closed the aforementioned upstream issue https://github.com/neovim/neovim/issues/9342
