### ISSUE TITLE
Bug: Tabs separator is incorrectly applied

### ISSUE THREAD

**Issue by lambda0xff** [nvim-lualine/lualine.nvim#512]
![Screenshot 2021-12-27 at 10 27 31](https://user-images.githubusercontent.com/38687176/147457956-ee65eb5e-fcfe-4a49-a0c4-f0090e3d86af.png)
![Screenshot 2021-12-27 at 10 29 43](https://user-images.githubusercontent.com/38687176/147457968-0cf8a76d-65a6-46a5-9ab6-9ba23a142321.png)
![Screenshot 2021-12-27 at 10 29 55](https://user-images.githubusercontent.com/38687176/147457985-751c9787-a1d6-4796-b0d0-ca5625e7ce14.png)

With three tabs, red background is currently active one.
Looks like the index number applied for displaying the separator (chevron) is off by 1 ?

**Comment by shadmansaleh** [comment]
No it's suppose to show transitional separator there. I assume you have `section_separators` turned off ?

Also I'll not be attending bug reports that ignore issue template . You were suppose to provide a minimal config that can reproduce this but you ignored it and cleared the template. With that I could tell what's wrong but now I can't :|

**Comment by lambda0xff** [comment]
> I assume you have section_separators turned off ?
Correct

Sorry about not providing a minimal config., won't do it again ;)
Thanks for this great plugin
Cheers

**Comment by shadmansaleh** [comment]
> Correct

If you don't want section separators in you statusline just on tabline.
You can just set the section separator option on tabs/buffers component and it will only be enabled there.

For example:
```lua
tabline = {
  lualine_a = {
    {
      'tabs',
      section_separators = {left = '', right = ''},
      },
    }
  }
}
```
