### ISSUE TITLE
always_divide_middle doesn't affect tabs

### ISSUE THREAD

**Issue by SimonMandlik** [nvim-lualine/lualine.nvim#514]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

`init.vim`:
```
" Specify a directory for plugins
call plug#begin(stdpath('data') . '/plugged')

Plug 'nvim-lualine/lualine.nvim'

" Initialize plugin system
call plug#end()

lua << EOF
require('lualine').setup {
    options = {
        always_divide_middle = false,
        },
    tabline = {
        lualine_b = { {'tabs', separator ={left='', right=''}, max_length=99, mode=2}}

        }
    }
EOF
```

### Expected behaviour

(taken from vanilla nvim)

![image](https://user-images.githubusercontent.com/16707112/147494401-57aa7fa5-e3d6-490e-902a-071f7e13072a.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/16707112/147494450-0cb664e7-a852-40ef-8946-e8f3570a2c41.png)

**Comment by shadmansaleh** [comment]
Can't reproduce .

Is this the only call to `lualine.setup` in your config ?

**Comment by SimonMandlik** [comment]
yes, it is..

I run it with `nvim -u init.vim` and then spam `:tabnew init.vim`. With `max_length` removed, the issue still persists.

I have found out that changing width of the terminal window hides/shows some tabs.

![image](https://user-images.githubusercontent.com/16707112/147498628-b5c347ab-5671-4289-b383-1b73f52360ac.png)

![image](https://user-images.githubusercontent.com/16707112/147498640-1522170c-8106-4968-84b1-378e7b5144f7.png)

![image](https://user-images.githubusercontent.com/16707112/147498663-05fe1c2e-40c5-4e71-803c-caa1b949de36.png)

Still, large portion of the screen remains unused.

**Comment by shadmansaleh** [comment]
Oh right max width, forgot about that .

Try this then
```lua
require('lualine').setup {
    options = {
        always_divide_middle = false,
        },
    tabline = {
        lualine_b = { {'tabs',
            separator ={left='', right=''},
            max_length=function() return vim.go.columns end,
            mode=2}}
        }
    }
```

**Comment by SimonMandlik** [comment]
That works, thanks!
