### ISSUE TITLE
Feat: Port Kanagawa Colorscheme

### ISSUE THREAD

**Issue by SuperCuber** [nvim-lualine/lualine.nvim#516]
### Requested feature
Would be nice if the theme [kanagawa](https://github.com/rebelot/kanagawa.nvim) was an option

### Motivation
It's a pretty popular recently created theme :)

**Comment by shadmansaleh** [comment]
Looks like kanagawa does support lualine .

https://github.com/rebelot/kanagawa.nvim#plugin-support

You should just be able to set your lualine theme to that 
```lua
require'lualine'.setup {
    options = {
        theme = 'kanagawa',
    },
}
```
Or if you use `auto` theme it'll pick up the theme from colorscheme.

**Comment by SuperCuber** [comment]
Ah I see :)
