### ISSUE TITLE
Bug: Custom Hex Color are not exactly correct

### ISSUE THREAD

**Issue by budimanjojo** [nvim-lualine/lualine.nvim#530]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

I use custom color for a theme and the rendered color is not exactly the color I put in. I put `#3971ED` and the resulted color become `#5F5FFF`, and `#198844` become `#00875F`. Look at screenshots, the TMUX bar below is real `#3971ED` while lualine bar is displayed as `#5F5FFF` according to GIMP. The color difference is huge.
![Screenshot from 2022-01-04 14-19-33](https://user-images.githubusercontent.com/13085918/148023583-5e211886-d135-4432-bbfc-4169e0973e91.png)

![Screenshot from 2022-01-04 14-20-00](https://user-images.githubusercontent.com/13085918/148023588-29d387b1-dcc6-415f-9f5c-7a456ee5fa5f.png)

### Minimal config to reproduce the issue
```
local custom_material = require('lualine.themes.material')

custom_material.normal.a.bg = '#3971ED'
custom_material.insert.a.bg = '#198844'
custom_material.visual.a.bg = '#A36AC7'
custom_material.replace.a.bg = '#CC342B'

require('lualine').setup {
  options = {
    icons_enabled = true,
    theme = custom_material
  },

```

**Comment by shadmansaleh** [comment]
Does your terminal true_color support & have `termguicolors` enabled ?

Try
```vim
:set termguicolors
```

**Comment by budimanjojo** [comment]
> 

I don't know about terminal true_color support but I have termguicolors enabled

**Comment by shadmansaleh** [comment]
Can you check what colors the hl groups are set with ?
```vim
:hi lualine_a_normal
:hi lualine_a_insert
:hi lualine_a_visual
:hi lualine_a_replace
```

**Comment by budimanjojo** [comment]
> Can you check what colors the hl groups are set with ?

```
lualine_a_normal xxx cterm=bold gui=bold guifg=#263238 guibg=#3971ED
lualine_a_insert xxx cterm=bold gui=bold guifg=#263238 guibg=#198844
lualine_a_visual xxx cterm=bold gui=bold guifg=#263238 guibg=#A36AC7
lualine_a_replace xxx cterm=bold gui=bold guifg=#263238 guibg=#CC342B
```


> try putting these two lines in your tmux conf if it's not already there

Done, nothing changed though.


> Does other stuff in nvim or other applications appear with correct color ?

My current fish shell is displaying right though. But I don't set hex code instead I use `blue` `green` etc in fish.

**Comment by shadmansaleh** [comment]
> ```
>lualine_a_normal xxx cterm=bold gui=bold guifg=#263238 guibg=#3971ED
>lualine_a_insert xxx cterm=bold gui=bold guifg=#263238 guibg=#198844
>lualine_a_visual xxx cterm=bold gui=bold guifg=#263238 guibg=#A36AC7
>lualine_a_replace xxx cterm=bold gui=bold guifg=#263238 guibg=#CC342B
```

The highlight groups are set up correctly . I do think it's an issue with the terminal as terminal is what does all the rendering . Basically lualine tells neovim what highlight group to use & neovim tells terminal what color to use . And terminals suppose to render qith that color.

You still haven't said what terminal you're using ?

> Done, nothing changed though.

Still you should see if the same issue occurs without tmux . Without tmux at lest one layer of translation gone .

**Comment by budimanjojo** [comment]
> Still you should see if the same issue occurs without tmux . Without tmux at lest one layer of translation gone .

I just tried without tmux and the color is displaying right. So I should close this issue now. Thanks for the help
