### ISSUE TITLE
Bug: Invalid buffer id error occurs when call Telescope window

### ISSUE THREAD

**Issue by hexh250786313** [nvim-lualine/lualine.nvim#532]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

1. Start nvim
2. Call a [nvim-telescope](https://github.com/nvim-telescope/telescope.nvim) window
3. Error messages like this:
![image](https://user-images.githubusercontent.com/26080416/148090520-8a046a4c-db63-4e78-bf56-0d969820f4ce.png)

### Expected behaviour

No error.

### Actual behaviour

1. Prints error messages
2. Lualine tabline does not work after the error occurs

### Minimal config to reproduce the issue

```lua
local status, lualine = pcall(require, "lualine")
if (not status) then return end

lualine.setup {
  tabline = {
    lualine_a = {
      {
        'buffers',
        show_filename_only = true,
        mode = 2,
        max_length = vim.o.columns * 1 / 2,
      }
    },
    lualine_b = {},
    lualine_c = {},
    lualine_x = {},
    lualine_y = {
      {
        'filename',
        path = 1
      },
    },
    lualine_z = {'tabs'}
  }
}
```

**Comment by aitvann** [comment]
I have similar problem with [startify](https://github.com/mhinz/vim-startify)

![image](https://user-images.githubusercontent.com/58750865/148094892-381cadb6-d1fa-4f2e-8e56-e5eacba08091.png)

minimal config:
``` lua
vim.cmd [[
call plug#begin('~/.nvim/plugins')
Plug 'nvim-lualine/lualine.nvim'
Plug 'mhinz/vim-startify'
call plug#end()
]]

require('lualine').setup {
    tabline = {
        lualine_b = { 'buffers' },
    },
}
```

**Comment by shadmansaleh** [comment]
Thanks for the report . See if it's fixed now .

**Comment by Spo0on** [comment]
I have same problem with Noice plugin.
<img width="1152" alt="Schermata 2022-12-16 alle 16 31 37" src="https://user-images.githubusercontent.com/63358357/208132915-20a7417a-b511-43cc-a3da-a2ed4b991585.png">
That errors only occurs when the `globalstatus` option is enabled.
