### ISSUE TITLE
Bug: Improper handling of relative paths with spaces

### ISSUE THREAD

**Issue by SimonMandlik** [nvim-lualine/lualine.nvim#533]
I'm using a `'filename', path=1, symbols = { unnamed = '' }` section in the following scenario

```
❯ tree ~/With\ Space/
/Users/simon.mandlik/With\ Space/
└── test.txt

0 directories, 1 file
```

If I `cd` into the `"With Space"` dir and open `test.txt`, the following is shown in lualine:

![image](https://user-images.githubusercontent.com/16707112/148188303-ce066325-fa5c-4f74-b3f5-168b2e07e5c5.png)

`:pwd` in neovim returns `/Users/simon.mandlik/With Space`

**Comment by shadmansaleh** [comment]
I'm unable to reproduce it . It shows just `test.txt` if I cd into `With Space` and if I open it out of `With Sapace` it's showing `With Space/test.txt` . Can you try to reproduce it without any other plugins just with neovim & lualine ? [nvim_isolated_conf.sh](https://github.com/nvim-lualine/lualine.nvim/blob/master/scripts/nvim_isolated_conf.sh) can help to get an isolated nvim config.

Also check what's the output of following command
```vim
:echo vim.fn.expand('%:.')
```

Lualine doesn't really provide the relative path instead relative path received from neovim is just displayed in statusline .

**Comment by SimonMandlik** [comment]
Sorry, the problem indeed is somewhere else: https://github.com/nvim-telescope/telescope.nvim/issues/1662#issuecomment-1007421272
