### ISSUE TITLE
Bug: tabline background changed after select with `vib`, and can't change back when visual mode exited

### ISSUE THREAD

**Issue by GPN211314** [nvim-lualine/lualine.nvim#541]
### Self Checks

- [ x] I'm using the latest lualine.
- [ x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

type `vib` to select text and exit visual mode
### Expected behaviour
tabline background change back
<img width="1407" alt="截屏2022-01-10 上午11 31 45" src="https://user-images.githubusercontent.com/38633718/148715808-c49253a8-3e32-45c7-a134-1a30bbc8f598.png">

### Actual behaviour
<img width="1362" alt="截屏2022-01-10 上午11 09 10" src="https://user-images.githubusercontent.com/38633718/148715388-71d2e7ad-6e3b-438e-84a8-4144d0ca708c.png">

### Minimal config to reproduce the issue
``` vimscript
lua << END
-- Your lua part of config goes here
require'lualine'.setup {
    options = {
        theme = 'gruvbox_light',
    },
    tabline = {
        lualine_a = {
            {
                'buffers',
                mode = 2, -- 0 shows buffer name
                          -- 1 buffer index (bufnr)
                          -- 2 shows buffer name + buffer index (bufnr)
                max_length = vim.o.columns * 5 / 6,
            }
        },
        lualine_b = {},
        lualine_c = {},
        lualine_x = {},
        lualine_y = {},
        lualine_z = {
            {
                'tabs',
                max_length = vim.o.columns * 1 / 6,
            }
        }
    },
    sections = {
        lualine_x = {'lsp_progress', 'encoding', 'fileformat', 'filetype'},
    },
    extensions = {
        'quickfix',
        'fugitive'
    }
}
require('lualine').statusline()
require('lualine').tabline()
END

```

<details>
<summary>Config</summary>

</details>

**Comment by shadmansaleh** [comment]
Cam you try running `:redrawtabline` when it happens and see if that fixes the issue ?

**Comment by GPN211314** [comment]
> Cam you try running `:redrawtabline` when it happens and see if that fixes the issue ?

it works, the background color change back after `:redrawtabline`

**Comment by shadmansaleh** [comment]
Then this also falls under tabline being too lazy on redraw . vim/neovim just redraws tabline way too rarely .

You can try the solution in [FAQ](https://github.com/nvim-lualine/lualine.nvim/wiki/FAQ#my-tabline-updates-infrequently) . That should make tabline redraw more regularly and fix this .

**Comment by GPN211314** [comment]
> Then this also falls under tabline being too lazy on redraw . vim/neovim just redraws tabline way too rarely .
> 
> You can try the solution in [FAQ](https://github.com/nvim-lualine/lualine.nvim/wiki/FAQ#my-tabline-updates-infrequently) . That should make tabline redraw more regularly and fix this .
> 
> Can you confirm this ?

1. statusline will be redraw correctly when exit visual mode, why tabline has problem to redraw?
2. I think tabline no need to change background color when enther visual mode(like airline)
3. as a temprorary solution, I add a autocmd in configuration, `vim.cmd 'autocmd ModeChanged v:n redrawtabline'`, now it seems fine

**Comment by GPN211314** [comment]
thx
