### ISSUE TITLE
Bug: Custom settings not taking affect

### ISSUE THREAD

**Issue by Rimann91** [nvim-lualine/lualine.nvim#547]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### Expected behaviour
Using the default configurations as a template, I should be able to edit the values in place and see them change on nvim restart

### Actual behaviour
When copying the default settings directlly from the readme, I change the seperator Icons, but icons do not change on nvim restart and remain set to default seperators.

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

```
source /home/$USER/.config/nvim/vim-plug/plugins.vim

call plug#begin('~/.config/nvim/autoload/plugged')
Plug 'nvim-lualine/lualine.nvim'
call plug#end()

lua << EOF
require('lualine').setup({
  options = {
    icons_enabled = true,
    theme = 'auto',
    component_separators = { left = '', right = ''},
    section_seperators = {left = '', right = ''},
    disabled_filetypes = {},
    always_divide_middle = true,
  },
  sections = {
    lualine_a = {'mode'},
    lualine_b = {'branch', 'diff', 'diagnostics'},
    lualine_c = {'filename'},
    lualine_x = {'encoding', 'fileformat', 'filetype'},
    lualine_y = {'progress'},
    lualine_z = {'location'}
  },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = {'filename'},
    lualine_x = {'location'},
    lualine_y = {},
    lualine_z = {}
  },
  tabline = {},
  extensions = {}
})
EOF
```

</details>

### Aditional information

The above config is an exact copy of the default configuration from the README, the only thing I changed was the section separator icons

**Comment by shadmansaleh** [comment]
> the only thing I changed was the section separator icons

You've changed one more thing, you've written `separators` as `seperators` .

**Comment by Rimann91** [comment]
crazy that one small typo can prevent the entire thing from working. You can remove this bug. I'm new to nlua (recent convert from vim8), do you have any suggestions on how I can get more verbose output when I have a problem so that I can catch something like this? Nothing happened other than it simply not doing anything and it's not the first time I have had that problem.
