### ISSUE TITLE
Bug: depracated call to vim.lsp.diagnostic.get_count

### ISSUE THREAD

**Issue by sandrotaje** [nvim-lualine/lualine.nvim#548]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
Just install lualine with nvim 0.6.1

### Expected behaviour
It works without a depracated warning

### Actual behaviour
It shows the deprecated warning
![image](https://user-images.githubusercontent.com/23263209/149156101-1b885711-0bb5-457d-afb6-c855d1ea661a.png)

### Aditional information

I think it's [here](https://github.com/nvim-lualine/lualine.nvim/blob/bc5c2f5658821f98e55013eb3bec9d540c420470/lua/lualine/components/diagnostics/sources.lua#L8) the problem

from `:h deprecated`

![image](https://user-images.githubusercontent.com/23263209/149156731-6de0af05-e8e9-44df-b46d-bfaa3b3393ab.png)

**Comment by shadmansaleh** [comment]
duplicate #473

`nvim-lsp` diagnoatics source is deprecated in nvim0.6+ use `nvim_diagnostic` as source.
