### ISSUE TITLE
Bug: Lualine not following window width

### ISSUE THREAD

**Issue by augustocdias** [nvim-lualine/lualine.nvim#550]
When I have multiple windows, lualine is not self dimensioning to the same width of the window. If you check the screenshot bellow you'll notice the border of the window after the end of the status line. 

![image](https://user-images.githubusercontent.com/1080789/149490601-bb4418de-0c45-4ce8-a9f7-6ed75be6a4a2.png)

**Comment by shadmansaleh** [comment]
That's how vim/neovim draws statusline . It's not upto lualine. That blank spot is part of window border.

You can reproduce this with following simple example :
```
:hi a ctermbg=1 guibg=#ee5522
:set stl=%#a#
:vsp
```
