### ISSUE TITLE
question about using the theme evil_lualine

### ISSUE THREAD

**Issue by sogens** [nvim-lualine/lualine.nvim#551]
noob question:

I want to use the theme 'evil_lualine' but im not sure how I moved the file to "~/.vim/plugged/lualine.nvim/lua/lualine/themes/" but its not working properly can you please tell me how to use it ?

or how I can get the dracula theme (or any default theme) to show my active LSP in lualine like the evil_lualine theme does

sorry if this doesnt belong here

**Comment by shadmansaleh** [comment]
evil_line isn't a theme it's a example of user config. If you want to use it as it is you can copy it's contents as you lualine config . Also Discussions are more appropriate for such questions , issues are for tracking bugs and feature requests.
