### ISSUE TITLE
Bug: Poor legibility of `diff` in `lualine_b` with solarized theme

### ISSUE THREAD

**Issue by grtcdr** [nvim-lualine/lualine.nvim#552]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### Expected behaviour

Sufficient contrast between the foreground of the `diff` component and background of the `lualine_b` section.

### Actual behaviour

There's currently very poor contrast between the text of the `diff` component, and the background color of the `lualine_b` section. Note that this is only an issue with this specific section.

### Minimal config to reproduce the issue

```
require 'lualine'.setup({
   options = {
      section_separators = '', 
      component_separators = '',
      theme = 'solarized'
   },
   sections = {
      lualine_a = {},
      lualine_b = {'diff'},
      lualine_c = {},
      lualine_x = {},
      lualine_y = {},
      lualine_z = {}
   },
})
```

### Aditional information

Here's a screenshot to help visualize this issue:

![swappy-20220117_012724](https://user-images.githubusercontent.com/35816711/149684310-9efd382f-b3c0-4088-956a-cfab0d30a59c.png)

**Comment by shadmansaleh** [comment]
You can change the colors to your liking with [diff_color](https://github.com/nvim-lualine/lualine.nvim#diff-component-options) option .
Diff colors by default are grabbed from  GitSignsAdd/GitGutterAdd/DiffAdded/DiffAdd highlight definition . So the color usually goes well with the colorscheme but not always there's possibility o something like this happening . And it's not possible for me to make sure this always appears right on every section of every theme.  So diff_color option is exposed to customize colors.
