### ISSUE TITLE
Fileformat not show up

### ISSUE THREAD

**Issue by rickywu** [nvim-lualine/lualine.nvim#555]
- [x] I'm using the latest lualine.
- [ ] I didn't find the issue in exsisting issues or prs.
everything is OK but no fileformat
### How to reproduce the problem
use packer install lualine

### Expected behaviour
should be a fileformat icon?

### Actual behaviour
![image](https://user-images.githubusercontent.com/442398/149957189-1575ccb9-20f0-468a-8587-6bb8573d3cf5.png)

### Minimal config to reproduce the issue
    require('lualine').setup {
      options = {
        icons_enabled = true,
        theme = 'onelight',
        component_separators = { left = '', right = ''},
        section_separators = { left = '', right = ''},
        disabled_filetypes = {},
        always_divide_middle = true,
      },
      sections = {
        lualine_a = {'mode'},
        lualine_b = {'branch', 'diff', 'diagnostics'},
        lualine_c = {'filename', 'lsp_progress'},
        lualine_x = {'encoding', 'fileformat', 'filetype'},
        lualine_y = {'progress'},
        lualine_z = {'location'}
      },
      inactive_sections = {
        lualine_a = {},
        lualine_b = {},
        lualine_c = {'filename'},
        lualine_x = {'location'},
        lualine_y = {},
        lualine_z = {}
      },
      tabline = {},
      extensions = {}
    }

**Comment by shadmansaleh** [comment]
I think the font you're using doesn't have those icons . Can you see if icons here https://github.com/nvim-lualine/lualine.nvim/blob/70691ae350fdbe1f15758e3b8e2973742a7967a9/lua/lualine/components/fileformat.lua#L7-L9 get rendered ?

You should probably try with a different font + Also see if the component works with `icons_enabled = false`

```lua
lualine_x = {'encoding', {'fileformat', icons_enabled = false}, 'filetype'},
```

**Comment by rickywu** [comment]
Yes, it's because of font, config icons_enabled = false then shows fileformat
