### ISSUE TITLE
Feat: Lualine clock

### ISSUE THREAD

**Issue by lukstep** [nvim-lualine/lualine.nvim#557]
Hello

Is it any possible to update section on Lualine every given period? I want to add clock to my Lualine and update it every second.

![image](https://user-images.githubusercontent.com/20487002/150640779-7335af9e-3f30-45af-b6d1-e0924c4e4e2c.png)

**Comment by hoob3rt** [comment]
You can create your own component with `vim.loop`. Alternatively `os.clock()` should also work. Lmk if that's a sufficient answer for you, if not  I can provide a snippet later today :)

**Comment by shadmansaleh** [comment]
Try [this](https://github.com/nvim-lualine/lualine.nvim/wiki/FAQ#my-tabline-updates-infrequently) . You need to use `redrawstatus` for statusline.

**Comment by lukstep** [comment]
ok, thanks
