### ISSUE TITLE
Bug: evil lualine black bar after modified symbol

### ISSUE THREAD

**Issue by RitschAlex** [nvim-lualine/lualine.nvim#560]
I am using the evil luline, which works fine, except that I got a small black bar / separator right after the git modified symbol.

default style:
![113875129-4453ba00-97d8-11eb-8f21-94a9ef565db3](https://user-images.githubusercontent.com/70853152/151332704-ca488985-271e-40af-824c-e321b2f087ef.png)

code snippet:
![Jb7egKh](https://user-images.githubusercontent.com/70853152/151332579-b9c8b0d1-7621-45a5-9401-cd24f69d5dc9.png)

current behavior:
![PBFE1xj](https://user-images.githubusercontent.com/70853152/151332583-c05bce8a-a77c-42bc-a657-23c440088bfc.png)

Might be the problem the japanese language pack that is installed on the computer?

Are there any other git modified icons that I could try to use instead of the default on?

**Comment by shadmansaleh** [comment]
> Are there any other git modified icons that I could try to use instead of the default on?

You can put anything you like in symbols->modified option . Personally I just use the default (+, ~, -) symbols .

If you want you can search symbols on powerline fonts here https://www.nerdfonts.com/cheat-sheet .

Also I can't see how this is a bug in lualine.
