### ISSUE TITLE
Feat: Always displayed in one place

### ISSUE THREAD

**Issue by yasudanaoya** [nvim-lualine/lualine.nvim#562]
I tried to find it, but I couldn't find it.
However, I'm sorry if there are duplicates.

### Requested feature

When the screen is split, the status line is also split.

Is there a flag that integrates this into one so that it always shows the buffer of the window that is in focus?

![スクリーンショット 2022-01-28 11 22 59](https://user-images.githubusercontent.com/43776161/151476237-e087628c-5323-44cc-ad71-238f0700583b.png)

### Motivation

Having the mode and branch name always in one place saves you the trouble of searching through lualine for the information you want to see.

**Comment by shadmansaleh** [comment]
duplicate #504 ;)

See https://github.com/nvim-lualine/lualine.nvim/issues/504#issuecomment-999532354

**Comment by yasudanaoya** [comment]
@shadmansaleh 
thx!

**Comment by yasudanaoya** [comment]
finally!
https://github.com/neovim/neovim/pull/17266
