### ISSUE TITLE
Question / idea: support for nvim-treesitter

### ISSUE THREAD

**Issue by devth** [nvim-lualine/lualine.nvim#569]
### Requested feature

`nvim-treesitter` [exposes a statusline indicator function](https://github.com/nvim-treesitter/nvim-treesitter#statusline-indicator):

```
nvim_treesitter#statusline(90)
```

How would I use this in lualine?

I tried:

```
  sections = { lualine_c = {'nvim_treesitter#statusline(90)'} }
```

but nothing shows up:

![image](https://user-images.githubusercontent.com/86107/152220977-19598227-cc0e-4ea1-b576-addd50e14872.png)

If I `echo` the function I get the output I expect:

![image](https://user-images.githubusercontent.com/86107/152221140-e952f5cf-d139-48dc-8872-63c5eb0b79b1.png)

**Comment by gegoune** [comment]
Did not try to get that integration working but setting up `SmiteshP/nvim-gps` was very straightforward.

**Comment by shadmansaleh** [comment]
> How would I use this in lualine?

Something like this:
```lua
lualine_c = {function()
   return vim.fn['nvim_treesitter#statusline'](90)
end}
```

I don't feel like this is something lualine needs to provide specific component as It's pretty easy to use a lua function for this.

**Comment by devth** [comment]
Thanks!
