### ISSUE TITLE
Bug: Plugin interacts with DAPInstall and crashes Neovim

### ISSUE THREAD

**Issue by ByteDrummer** [nvim-lualine/lualine.nvim#570]
This issue only occurs when this plugin is loaded combined with `DAPInstall` and the other settings in the mini config below. I've opened an issue for that project's repo but it made sense to also open it here since it's clear that these plugins are interacting.

### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Call `:DIInstall jsnode` using the `DAPInstall` plugin while having `lualine` loaded.

### Expected behaviour
Should install the debug adapter as usual.

### Actual behaviour
I get the following error message and Neovim crashes:
```
:DIInstall jsnode
Do you want to install the debugger 'jsnode'?
[Y]es, (C)ancel: nvim: /home/runner/work/neovim/neovim/src/nvim/ui_compositor.c:551: ui_comp_raw_line: Assertion `attrs[i] >= 0' failed.
                                                                                                                                        [1]    55171 abort (core dumped)  nvim
```

### Minimal config to reproduce the issue

<details>

```
call plug#begin('~/.vim/plugged')

Plug 'nvim-lualine/lualine.nvim'
Plug 'mfussenegger/nvim-dap'
Plug 'Pocco81/DAPInstall.nvim'

call plug#end()

lua << EOF
local dap = require('dap')
local dap_install = require("dap-install")
require'lualine'.setup{}

dap_install.setup({
      installation_path = vim.fn.stdpath("data") .. "/dapinstall/",
})
EOF

set fileencoding=utf-8
set splitbelow
```

<summary>Config</summary>

</details>

**Comment by shadmansaleh** [comment]
You should open an issue in neovim . It seems like an upstream bug . Lualine doesn't do anything that may consern DapInstall and plugins shouldn't hit assertions as far as I'm aware .
