### ISSUE TITLE
Bug: Filenames with `%` in them are displayed incorrectly

### ISSUE THREAD

**Issue by Mootikins** [nvim-lualine/lualine.nvim#579]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Create a test file that has a `%` in the name, eg `test_%.txt`, then open.

```sh
$ touch test_%.txt
$ nvim test_%.txt
```

### Expected behaviour

Filenames are printed as they would appear in `ls`.

### Actual behaviour

The tabline and statusline will show incorrect filenames. The error in the filename will
vary based on the filename itself, which I believe to be based on `h: filename-modifiers`.
For another example, I work with `.bb` and `.bbappend` files often, which also can regularly have `%` in them. They show a number, while the `.txt` file above shows the filename with the `%` replaced with the filename of the current buffer.

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

```lua
function packer_uses(use)
	use { 'wbthomason/packer.nvim' }
	use { 'nvim-lualine/lualine.nvim',
		requires = { 'kyazdani42/nvim-web-devicons', opt = true },
		config = function()
			require('lualine').setup{
				tabline = { lualine_a = { { 'buffers' } } },
			}
		end,
	}

	if packer_bootstrap then require('packer').sync() end
end

return require('packer').startup(packer_uses)

```

</details>

**Comment by shadmansaleh** [comment]
See if you still encounter the issue.
