### ISSUE TITLE
Feat: empty theme

### ISSUE THREAD

**Issue by ioreshnikov** [nvim-lualine/lualine.nvim#582]
### Requested feature

There should be a clean way to set up an "empty" theme, i.e. the one that defines all the segment-specific highlight groups, but links them from `StatusLine` and `StatusLineNC` by default and does not override the colors when a custom colorscheme is loaded.

### Motivation

I am working on a custom theme (yet another `solarized` port) and I would like to support lualine out of the box. However, the way lualine is currently written, it overrides all the highlight groups defined by the colorscheme by the colors from the current lualine theme on every theme load and every background change.

I find this intrusive and I would prefer if there was a way to disable this behavior. Something like an empty theme, that defines all the highlight groups that link to `StatusLine` and `StatusLineNC` and that does not overwrite the colors defined by the user-selected colorscheme. I find this approach much more convenient than the currently suggested way of adding your own custom theme to lualine (even through the options).

**Comment by shadmansaleh** [comment]
Statusline & StatuslineNC is just just two hl groups . I can't see how I'll map all the colors lualine uses to just these two.

> currently suggested way of adding your own custom theme to lualine

Currently suggested way is actually not to add theme here . Rather have them with colorscheme for example like other solarized colorscheme [here](https://github.com/shaunsingh/solarized.nvim/blob/master/lua/lualine/themes/solarized.lua) .

If you want to you just use a dummy theme file that just maps lualines colors to highlight groups and define those hl groups as part of your colorscheme

For example:
```
-- file: lua/lualine/themes/solarized.lua
return {
      normal = { a = 'statusOuter', b = 'statusMiddle', c = 'statusInner' },
      insert = { a = 'statusInsert' },
      visual = { a = 'statusVisual' },
      replace = { a = 'statusReplace' },
      inactive = { a = 'statusInactive', b = 'statusInactive', c = 'statusInactive' },
}
```
Then define statusOuter, statusMiddle, statusInner, statusInsert,.... highlight groups as part of your colorscheme.
