### ISSUE TITLE
Bug: exception in lualine setup when open a file

### ISSUE THREAD

**Issue by appelgriebsch** [nvim-lualine/lualine.nvim#587]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

With recent update as soon as I open a file in Neovim I see the below error being triggered and my lualine is not configured properly.

### Expected behaviour
Lualine should show the configured sections as before.

### Actual behaviour
E5108: Error executing lua ...ker/opt/lualine.nvim/lua/lualine/components/filetype.lua:49: table index is nil
stack traceback:
        ...ker/opt/lualine.nvim/lua/lualine/components/filetype.lua:49: in function 'apply_icon'
        ...e/pack/packer/opt/lualine.nvim/lua/lualine/component.lua:218: in function 'draw'
        ...ck/packer/opt/lualine.nvim/lua/lualine/utils/section.lua:26: in function 'draw_section'
        ...e/nvim/site/pack/packer/opt/lualine.nvim/lua/lualine.lua:153: in function 'statusline'
        ...e/nvim/site/pack/packer/opt/lualine.nvim/lua/lualine.lua:319: in function <...e/nvim/site/pack/packer/opt/lualine.nvim/lua/lualine.lua:300>

### Minimal config to reproduce the issue
https://github.com/appelgriebsch/dotFiles/blob/master/neovim/lua/config/lualine.lua

<details>
<summary>Config</summary>

</details>

**Comment by shadmansaleh** [comment]
I'm unable to reproduce this even with your config . Can you provide an isolated minimal reproduction. If you're on unix https://github.com/nvim-lualine/lualine.nvim/blob/master/scripts/nvim_isolated_conf.sh can help with that .


Also try commenting out [this](https://github.com/appelgriebsch/dotFiles/blob/d048c3f77f59a54d3b03ea7f8aa263763137354c/neovim/lua/config/lualine.lua#L27) line and see if that fixes the error.
