### ISSUE TITLE
[Help needed] The status line only show up after first PackerSync

### ISSUE THREAD

**Issue by hypghzy** [nvim-lualine/lualine.nvim#593]
I'm working on building my own Lua version of configuration. I only installed very few plugins using Packer.

I use the default settings in the README instruction, but the status line only show up the initial PackerSync which install the plugin.
The status line does not show up after that. It says the function setup() of the plugin can start the status line, is that means that I have to call for that function outside of the packer's startup function?

Any instruction or suggestion will be greatly appreciated.

**Comment by shadmansaleh** [comment]
> It says the function setup() of the plugin can start the status line, is that means that I have to call for that function outside of the packer's startup function

Yes you need to call the setup function . You can call it inside packers config too.
```
use {'nvim-lualine/lualine.nvim', config=function()
    require('lualine').setup()
end}
```

**Comment by hypghzy** [comment]
> > It says the function setup() of the plugin can start the status line, is that means that I have to call for that function outside of the packer's startup function
> 
> Yes you need to call the setup function . You can call it inside packers config too.
> 
> ```lua
> use {'nvim-lualine/lualine.nvim', config=function()
>     require('lualine').setup()
> end}
> ```

I did put the setup function in the config of use in packer, but it seems that it only works after I call PackerSync, the status line will show up right after the Sync, but it doesn't show up after I exit and re-open the neovim.

**Comment by shadmansaleh** [comment]
Did you change the packers compile path ?
https://github.com/wbthomason/packer.nvim#custom-initialization

If you moved it out of `plugin/` directory you'll have to source the compiled file in your init.vim/lua .
