### ISSUE TITLE
Bug: E5108: Error executing ...highlight.lua:120: attempt to concatenate local 'foreground' (a nil value)

### ISSUE THREAD

**Issue by zeitchef** [nvim-lualine/lualine.nvim#600]
- [x ] I'm using the latest lualine.
- [x] I didn't find the issue in existing issues or prs.

For about 5 days now, I've been getting this error (see screenshot) when first interacting with Neovim (usually opening `NvimTree` or updating packages via `:PackerCompile`). 

<img width="1230" alt="Screen Shot 2022-03-07 at 08 53 11" src="https://user-images.githubusercontent.com/6670659/156990494-f2eb4ca2-5780-4427-a5d1-1a66af5d7856.png">

Any ideas what might be going on here?

**Comment by shadmansaleh** [comment]
Can you confirm https://github.com/nvim-lualine/lualine.nvim/commit/531b2f8a4b06411d303467be3698872995aa620e fixed it ?

**Comment by zeitchef** [comment]
Confirmed. Thanks!
