### ISSUE TITLE
Bug: Recent commit breaks external GitHub theme

### ISSUE THREAD

**Issue by appelgriebsch** [nvim-lualine/lualine.nvim#602]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

The most recent commit breaks GitHub theme (https://github.com/projekt0n/github-nvim-theme/blob/main/LUALINE.md).

### Expected behaviour
Up until recently the setup of lualine and Github theme resulted in this:
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/6803419/157236813-b589ec7c-d417-4651-99d4-c33effd9734a.png">

### Actual behaviour
With the most recent commit the integration of the GitHub theme is broken and it looks like so:
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/6803419/157236983-f7ce78fe-3f71-4aa7-a06e-1861a136bcc4.png">

### Minimal config to reproduce the issue
see https://github.com/projekt0n/github-nvim-theme/blob/main/LUALINE.md

<details>
<summary>Config</summary>

</details>

**Comment by uolot** [comment]
Same problem here, with the same colorscheme.

**Comment by appelgriebsch** [comment]
For me it broke with the most recent commit. I used the minimal config as shown on the GitHub theme site for the Lualine configuration via packer: https://github.com/projekt0n/github-nvim-theme/blob/main/LUALINE.md

**Comment by shadmansaleh** [comment]
>  I used the minimal config as shown on the GitHub theme site for the Lualine configuration via packer:

Like I said that's not minimal config :/ There's still too many things that can vary .

One very important question since you're using packer . Are you certain your colorscheme is loaded before lualine ?

Try adding
```lua
vim.cmd('packadd  github-nvim-theme')
```
before your call to lualine setup

**Comment by appelgriebsch** [comment]
> One very important question since you're using packer . Are you certain your colorscheme is loaded before lualine ?

That's a good hint...

On the GitHub theme site it mentions this setting:
```lua
use {
  "hoob3rt/lualine.nvim",
  config = function()
    require("lualine").setup {
      options = {
        theme = "github" -- or "auto"
        -- ... your lualine config
      }
    }
  end
}
use {
  "projekt0n/github-nvim-theme",
  after = "lualine.nvim", -- <- remove this line
  config = function()
    require("github-theme").setup({
      theme_style = "dark_default"
      -- your github config
    })
  end
}
```
which loads the theme AFTER lualine. So when turning it around to this it works:
```lua
use {
  "hoob3rt/lualine.nvim",
  after = "github-nvim-theme", -- <- add this line instead
  config = function()
    require("lualine").setup {
      options = {
        theme = "github" -- or "auto"
        -- ... your lualine config
      }
    }
  end
}
use {
  "projekt0n/github-nvim-theme",
  config = function()
    require("github-theme").setup({
      theme_style = "dark_default"
      -- your github config
    })
  end
}
```
