### ISSUE TITLE
Feat: Enumerate buffer tabs in tabline

### ISSUE THREAD

**Issue by nkakouros** [nvim-lualine/lualine.nvim#603]
### Requested feature

Similar to other buffer line extensions, it would be useful to have custom numbering for buffers in the buffer line, instead of using the internal buffer number of nvim. 

### Motivation

The buffer number increments for the life time of a vim session. This could lead to large numbers if the session is long lived. This makes it cumbersome to select the desired buffer and only really saves an `:ls` for the user. It also makes it hard to jump to the first buffer in the buffer line as you need to know the buffer number. If buffer tabs where numbered sequentially, the first tab would be `1` always.

I understand that this request is more complex than it appears, since in order to make use of these sequential numbers custom mappings will need to be provided by the plugin to select a specific buffer which will take care of the translation between sequential number and internal buffer number. But, it would greatly improve the usability.

**Comment by shadmansaleh** [comment]
This is something we can definitely add. Any one interested in making a pr with this ?

Also can you elaborate on what you mean by custom mappings ? I think providing a vim command like we currently provide for naming tabs (LualineRenameTab) would be sufficient.

**Comment by shadmansaleh** [comment]
> The tab selection mechanism will also need to be implemented

Not sure what you mean by tab selection ??

**Comment by nkakouros** [comment]
The equivalent of `:buffer X` but using the custom numbering (instead of the internal buffer number).
