### ISSUE TITLE
lualine missing theme colouring when defining nvim_diagnostic

### ISSUE THREAD

**Issue by mrkz** [nvim-lualine/lualine.nvim#604]
Hey, first of all, thanks for all the hard work and time you invest on the project! 🎉 
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
commit 88a44ad introduced a regression on theming/coloring of the lualine (when defining nvim_diagnostic on lualine, apparently)

### Expected behaviour
lualine respecting theme set for it (i.e: see image below)
![lualine-works](https://user-images.githubusercontent.com/978752/157721559-039ac1d5-f750-429d-9b08-88fa03e93f56.png)

### Actual behaviour
lualine missing theme configured (i.e: see image below)
![lualine-noworks](https://user-images.githubusercontent.com/978752/157721743-c0d109e3-88a5-4075-b52e-337f80603a55.png)

### Minimal config to reproduce the issue
lualine.lua
```lua
require'lualine'.setup {
  options = {
    icons_enabled = false,
    theme = 'powerline',
    component_separators = { left = '>', right = '<'},
    section_separators = { left = '', right = ''},
    disabled_filetypes = {},
    always_divide_middle = true,
  },
  sections = {
    lualine_a = {'mode'},
    lualine_b = {'branch',
                  {'diagnostics', sources={'nvim_diagnostic'}}},
    lualine_c = {{'filename', path = 2,}, { 'lsp_progress'}},
    lualine_x = {'encoding', 'fileformat', 'filetype'},
    lualine_y = {'progress'},
    lualine_z = {'location'}
  },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = {'filename'},
    lualine_x = {'location'},
    lualine_y = {},
    lualine_z = {}
  },
  tabline = {},
  extensions = {}
}
```

<details>

```
call plug#begin("/tmp/lualine-tmp/lualine_missing_theme/.local/share/nvim/plugged")
Plug 'nvim-lualine/lualine.nvim'
call plug#end()
require'lualine'.setup {
  options = {
    icons_enabled = false,
    theme = 'powerline',
    component_separators = { left = '>', right = '<'},
    section_separators = { left = '', right = ''},
    disabled_filetypes = {},
    always_divide_middle = true,
  },
  sections = {
    lualine_a = {'mode'},
    lualine_b = {'branch',
        {'diagnostics', sources={'nvim_diagnostic'}}},
    lualine_c = {{'filename', path = 2,}, { 'lsp_progress'}},
    lualine_x = {'encoding', 'fileformat', 'filetype'},
    lualine_y = {'progress'},
    lualine_z = {'location'}
  },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = {'filename'},
    lualine_x = {'location'},
    lualine_y = {},
    lualine_z = {}
  },
  tabline = {},
  extensions = {}

}
END
```

</details>

### Aditional information
I noticed that if I remove `                  {'diagnostics', sources={'nvim_diagnostic'}}},` from  `lualine_b`, the color is back again

**Comment by shadmansaleh** [comment]
I think it's duplicate of #601 & #602 . You're also most likely setting your colorscheme after your lualine config too . Can you check that ?

**Comment by mrkz** [comment]
Definitely a duplicate, sorry I missed those, and I apologize for wasting your time looking into this.

fwiw, that did the trick.

**Comment by tricktux** [comment]
Funny piece of info, I still cannot figure this one out for the life of me 😝

That's not so funny... the funny part is that theme is applied appropriately  under `linux`, but no under `windows`. Is there anything windows specific?

The theme is only applied if I manually perform a `colorscheme` command after entering `nvim`. I've tried putting that command all over the place but it has no effect. This has been going on for a while. Any ideas would be great.

```lua
  use {
    'nvim-lualine/lualine.nvim',
    -- List of plugins that update the lualine elements
    -- Add plugis here that use the ins_{left,right} functions
    after = {
      'neomake', 'nvim-gps', 'pomodoro.vim', 'vim-obsession', 'gitsigns.nvim',
      'papercolor-theme'
    },
    config = function() require('config.plugins.lualine'):config() end
  }
  use {
    'NLKNguyen/papercolor-theme',
    setup = function() require('config.plugins.misc'):setup_papercolor() end,
    config = function()
      require('utils.log').info('[papercolor]: Configuring...')
      vim.cmd[[colorscheme PaperColor]]
    end
  }

```

**Comment by tricktux** [comment]
@shadmansaleh thanks for the suggestions! But `wants` did not do it.

I honestly have no interest in lazy loading.

I use lazy loading to ensure the order in which plugins are loaded. I have several plugins, the ones in the `after` list that `inject` into the `lualine` configuration. If I don't control the order then `lualine.setup()` is called and the updating of my `lualine.config` is irrelevant.

Is there a better way to do this? Maybe updating my `config` and recalling `lualine.setup`?

So the main question is what's the appropriate way to update `lualine` config after calling `setup`?

And follow up question: Do you think this will help with the no `theme` issue in windows?

**Comment by shadmansaleh** [comment]
You can recall setup to update config and there's a get_config function in lualine module that gives you current config.
```lua
require('lualine').setup {
  options = {
    icons_enabled = true,
 },
  sections = {
    lualine_a = {'mode'},
    lualine_b = {'branch', 'diff', 'diagnostics'},
    lualine_c = {'filename'},
    lualine_x = {'encoding', 'fileformat', 'filetype'},
    lualine_y = {'progress'},
    lualine_z = {'location'}
  },
}

require'lualine'.setup {
   options = {theme = "changed_theme"}
}
require'lualine'.setup {
   sections = {
		lualine_a = {'component1'}
   }
}
require'lualine'.setup {
   sections = {
		lualine_b = {'component2'}
   }
}
local conf = require'lualine'.get_config()
table.insert(conf.sections.lualine_a, 'comp3')
require'lualine'.setup(conf)
```

> Do you think this will help with the no theme issue in windows?

TBH I don't see any reason for you to have no theme on windows . lualine doesn't have any windows specific behavior in that regard. I'm guessing your config/packer/neovim has some odd windows specific load order in this case.
