### ISSUE TITLE
Status bar items didn't change

### ISSUE THREAD

**Issue by testfailagain** [nvim-lualine/lualine.nvim#609]
Hi, 
I tried to use the minimal status bar, only mode, file, percentage, line number and charac count (typical n:n)
and I'm using this conf:
```
local filename = {
  {
    'filename',
    path = 1,             -- relative path
    shorting_target = 80, -- shorten long paths
    file_status = true,   -- show modified/readonly
    symbols = { modified = '[+]', readonly = '[-]' },
  },
}

statusline.setup({
  options = {
    component_separators = {left='', right=''},
    section_separators = {left='', right=''},
    disabled_filetypes = {
      'packer',
      'NvimTree',
      'fugitive',
      'fugitiveblame',
    }
  },
  sections = {
    lualine_a = {{'mode'}},
    lualine_b = filename,
  },
  inactive_sections = {
    lualine_a = {},
    lualine_b = filename,
  },
})

```
but I still can see:
NORMAL | file_path [+] | file_name [+]                     | utf-8 | penguin-icon | lua | n% | n:n
what I want:
NORMAL | file_path [+]                                                                                 | n% | n:n

what I'm doing wrong if I already remove almost all?

**Comment by shadmansaleh** [comment]
Lualine is using default config for the sections that you aren't specifying . If you want c & x section to be empty you should set them to empty table

```lua
sections = {
    lualine_a = {{'mode'}},
    lualine_b = filename,
    lualine_c = {},
    lualine_x = {},
  },
```

**Comment by testfailagain** [comment]
It works, thanks
