### ISSUE TITLE
Bug: Statusline icon is using the same background as tabline

### ISSUE THREAD

**Issue by zuqini** [nvim-lualine/lualine.nvim#610]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
1. Set the minimum config below as `~/.config/nvim/init.vim`
2. Run `nvim ~/.config/nvim/init.vim` (or open any other file with a filetype that contains an icon).

### Expected behaviour
The statusline icon should use the same background color as the statusline background, not use the background color from the tabline.

### Actual behaviour
Observe that the icon shown in tabline has the correct background color, but the icon shown in statusline is using the tabline's background color.

See top left and bottom right of the following example image.
![image](https://user-images.githubusercontent.com/5790854/158861061-c9c8b5ca-087f-4038-8fdf-f49ced64580e.png)

### Minimal config to reproduce the issue
```
call plug#begin()
        Plug 'nvim-lualine/lualine.nvim'
        " If you want to have icons in your statusline choose one of these
        Plug 'kyazdani42/nvim-web-devicons'
call plug#end()

lua << END
require('lualine').setup {
  options = {
    icons_enabled = true,
    theme = 'auto',
  },
  tabline = {
        lualine_a = { 'filetype' },
        lualine_b = {},
        lualine_c = {},
        lualine_x = {},
        lualine_y = {},
        lualine_z = {},
    },
  sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = {},
    lualine_x = { 'filetype' },
    lualine_y = {},
    lualine_z = {}
  },
}
END
```

**Comment by shadmansaleh** [comment]
Thanks for reporting . See if 7db1db3cd97079cf9c0089bc04afe71e90256a23 fixed it for you

**Comment by zuqini** [comment]
Thanks for the quick response, it fixed it!
