### ISSUE TITLE
Feat: global statusline support

### ISSUE THREAD

**Issue by goolord** [nvim-lualine/lualine.nvim#611]
### Requested feature

add configuration to allow users to use the new `laststatus = 3` https://github.com/neovim/neovim/pull/17266

**Comment by kdheepak** [comment]
I think block needs to not set `laststatus = 2`

https://github.com/nvim-lualine/lualine.nvim/blob/88a44ade818f9ee7ba730aa4096250e22b243808/lua/lualine.lua#L266-L277

These are the only two instances of `laststatus`  in the code.

**Comment by kdheepak** [comment]
Commenting those lines and adding `vim.opt.laststatus = 3` in my local configuration seems to do the trick:

![Screen Shot 2022-03-17 at 4 23 07 PM](https://user-images.githubusercontent.com/1813121/158904116-48901d82-555b-4e4c-ab9c-18b72e8c5abc.png)

I can submit a PR to remove those lines.

**Comment by shadmansaleh** [comment]
I was actually testing the pr well before it got merged. [feat/add_opt/gs](https://github.com/nvim-lualine/lualine.nvim/tree/feat/add_opt/gs) branch has support for it . It introduces a globalstatus option and sets laststatus according to that . @kdheepak I think that's a better approach then requiring users to setup laststatus by themselves .

**Comment by kdheepak** [comment]
Sounds good to me!

**Comment by kdheepak** [comment]
Works great!

**Comment by harrisoncramer** [comment]
This is not working for me on NVIM v0.7.0-dev+1269-g746a29c58, setting globalstatus to true prevents lualine from showing up at all.

**Comment by joelpalmer** [comment]
@harrisoncramer Requires  https://github.com/neovim/neovim/commit/5ab122917474b3f9e88be4ee88bc6d627980cfe0. You are just a few commits behind.

**Comment by treatybreaker** [comment]
Setting `vim.opt.laststatus=3` is not working as I anticipated with lualine. I'm on neovim `NVIM v0.7.0-dev+1275-g00effff56`. When I explicity run `:set laststatus=3` after neovim opens the global line works, but `vim.opt.laststatus` does not apply even when set *after* lualine is loaded. It's to my understanding though that I don't need to set `laststatus` at all as lualine manages that via the `globalstatus` option in the lualine config. Any pointers on what I've missed?

Here's my relevant configurations if that helps: [lualine](https://gitlab.orion-technologies.io/philler/dot-files/-/blob/Development/.config/nvim/lua/plugins/configs/statusline.lua) & [options](https://gitlab.orion-technologies.io/philler/dot-files/-/blob/Development/.config/nvim/lua/core/options.lua) (see the end of the file).

**Comment by shadmansaleh** [comment]
@treatybreaker did you update lualine ?

**Comment by treatybreaker** [comment]
Yep, on both my remote CentOS system & my local install.

**Comment by shadmansaleh** [comment]
Start neovim with `-V1` flag like this
```sh
nvim -V1
```
then check what does this command say
```vim
:set laststatus?
```

**Comment by treatybreaker** [comment]
@shadmansaleh very good advice, found my issue. Had a conflicting line in my configuration that was setting `laststatus` for dashboard incorrectly to 2 on non-dashboard files.

I have it working now; would recommend anyone else running into my issue to refer to @shadmansaleh advice above.

Thanks again @shadmansaleh :)

**Comment by tim-hilt** [comment]
Sorry to bump this issue, but I don't know if this is a bug or I just forgot a setting. This is how it looks to me when using lualine:

![image](https://user-images.githubusercontent.com/16037579/159140006-f2c43541-179c-48eb-b92b-48ffc8b3b8ad.png)

which in my opinion is wrong! The statusline should be full width on the bottom instead of on a single buffer! When I start neovim without any plugins it looks like this:

![image](https://user-images.githubusercontent.com/16037579/159140053-b9d0b1bc-ebf6-4975-a47a-20d28d6589d4.png)

which looks correct to me.

**Comment by shadmansaleh** [comment]
upgrade neovim to master, upgrade lualine to master. set globalstatus option to true.

```lua
require('lualine').setup({
  options = {globalstatus = true}
})
```
If still doesn't work follow [this](https://github.com/nvim-lualine/lualine.nvim/issues/611#issuecomment-1072312557) to figure out why you're laststation options in neovim isn't set to 3.

**Comment by tim-hilt** [comment]
Thanks! That config-parameter was the missing piece

**Comment by FugueSoft** [comment]
I've bounced off lualine in favor of mini.status line because of this issue. 
When I run `nvim -V1`, `:set laststatus?` I get:

> Se definió por última vez en ~/.local/share/nvim/lazy/lualine.nvim/lua/lualine/utils/nvim_opts.lua line 51

I have `vim.opts.laststatus=3` set and `globalstatus = true` in my config:
```lua
return {
  {
    'nvim-lualine/lualine.nvim',
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    opts = {
      tabline = {
        lualine_a = {},
        lualine_b = {},
        lualine_c = { 'filename', 'buffers' },
        lualine_x = {},
        lualine_y = {},
        lualine_z = { 'tabs' },
      },
      globalstatus = true,
      hide = true,
      restore = { 'laststatus', { global = true } },
      sections = {
        lualine_a = { 'mode' },
        lualine_b = { 'branch', 'diff', 'diagnostics' },
        lualine_c = { 'filename' },
        lualine_x = { 'encoding', 'fileformat', 'filetype' },
        lualine_y = { 'searchcount', 'progress' },
        lualine_z = { 'selectioncount', 'location' },
      },
    },
  },
}
```

**Comment by FugueSoft** [comment]
Also found this at the aforementioned location:
```lua
  setter_fn(name, val)

  --  Mitigation for https://github.com/nvim-lualine/lualine.nvim/issues/1323
  --  when redrawstatus is ran and winbar usues some eval syntax %{} for some
  --  odd reason nvim renders the winbar in statusline first then actual statusline
  --  replaces it. Also it doesn't happen on top window. Might be some bug in
  --  neovims rendering. Also it doesn't seem to happend with laststatus=2 or
  --  global status turned off in lualine. lualines rendering might be at fault
  --  too. but we should never be evaluating an externally set winbar so that
  --  doen't make much sense either.
  --  Tested: nvim v0.9.5
  --  TODO: Needs further investigation.
```
