### ISSUE TITLE
Bug: Last section of vertical split window appears active when no content present

### ISSUE THREAD

**Issue by aryzing** [nvim-lualine/lualine.nvim#615]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Set section `lualine_z = {}`

<details>
  <summary>Full config</summary>
  
```lua
lualine.setup({
	options = {
		disabled_filetypes = { "NvimTree" },
		section_separators = { left = "", right = "" },
		component_separators = { left = "", right = "" },
	},
	sections = {
		lualine_a = { "" },
		lualine_b = { "diagnostics" },
		lualine_c = { {
			"filename",
			file_status = false,
			path = 1,
		} },
		lualine_x = { "encoding", "fileformat", "filetype", "location" },
		lualine_y = { "" },
		lualine_z = {},
	},
	inactive_sections = {
		lualine_b = { "diagnostics" },
		lualine_c = { {
			"filename",
			file_status = false,
			path = 1,
		} },
		lualine_x = { "encoding", "fileformat", "filetype", "location" },
	},
	tabline = {
		lualine_z = { "tabs" },
	},
})
```

</details>

### Expected behaviour

Should be empty at all times.

### Actual behaviour

The last section appears to be one character wide when windows are split. Not sure if this is actually the "z" section or how lualine handles borders between vertically split windows.

In any case, at times the cursor can have the same color, so it's quite distracting when it appears.

![image](https://user-images.githubusercontent.com/4924405/158967767-b70bfdaa-03ff-4b8c-81ea-1937bb1c1b56.png)

### Minimal config to reproduce the issue

<details>
  <summary>Config</summary>

```
call plug#begin("/home/aryzing/workspace/repro-lualine/.local/share/nvim/plugged")
" Your plugins go here like
Plug 'nvim-lualine/lualine.nvim'
Plug 'projekt0n/github-nvim-theme'

call plug#end()

" Your Viml part of config goes here
" colorscheme onedark


lua << END
-- Your lua part of config goes here
require'lualine'.setup {
	options = {
		disabled_filetypes = { "NvimTree" },
		section_separators = { left = "", right = "" },
		component_separators = { left = "", right = "" },
	},
	sections = {
		lualine_a = { "" },
		lualine_b = { "diagnostics" },
		lualine_c = { {
			"filename",
			file_status = false,
			path = 1,
		} },
		lualine_x = { "encoding", "fileformat", "filetype", "location" },
		lualine_y = { "" },
		lualine_z = {},
	},
	inactive_sections = {
		lualine_b = { "diagnostics" },
		lualine_c = { {
			"filename",
			file_status = false,
			path = 1,
		} },
		lualine_x = { "encoding", "fileformat", "filetype", "location" },
	},
	tabline = {
		lualine_z = { "tabs" },
	},
}


require'github-theme'.setup({
	theme_style = "light",
})
END
```

</details>

**Comment by shadmansaleh** [comment]
Lualine doesn't handle separation between virtical splits neovim does . 
Change background colors of `StatusLine` & `StatusLineNC` highlight groups to match your lualine themes background color.

What theme & colorscheme are you using ?

**Comment by aryzing** [comment]
Sorry I didn't find the duplicate, I did search for it before posting.

The theme & colorscheme (it's at the very bottom of the minimal config to reproduce above),

```lua
require'github-theme'.setup({
	theme_style = "light",
})
```

**Comment by aryzing** [comment]
And forgive my ignorance, how can I change those colors in my lua config?
