### ISSUE TITLE
Bug: Filename truncation should be based on full Neovim width when using global status line

### ISSUE THREAD

**Issue by mrjones2014** [nvim-lualine/lualine.nvim#622]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

1. Enable the global status line setting (requires Neovim nightly)
2. Resize a window to be really small

### Expected behaviour

Lualine should not truncate/shorten the filename unless it actually needs to (should be based on full terminal width when using global status line)

### Actual behaviour

It truncates/shortens the filename based on the width of the split, not the width of the whole Neovim

### Minimal config to reproduce the issue

```lua
require('lualine').setup({
  options = { globalstatus = true },
  sections = { lualine_a = { 'filename' } },
})
```

### Aditional information

Screen recording:

![CleanShot-2022-03-24-at-13 04 19](https://user-images.githubusercontent.com/8648891/159971132-2e3813aa-8cc8-4d93-9624-4b0a841a37cc.gif)

**Comment by shadmansaleh** [comment]
Are you sure your lualine is upto date ? I think #617 already addressed this issue.

**Comment by mrjones2014** [comment]
I even have that commit, if I `cd` into the plugin directory 🤔  

![CleanShot-2022-03-24-at-15 07 14](https://user-images.githubusercontent.com/8648891/159992020-9c38667e-b9df-48f1-8ada-d89bc4ee84bf.png)

**Comment by shadmansaleh** [comment]
I'm still unable to reproduce it.
![Screenshot from 2022-03-25 13-42-13](https://user-images.githubusercontent.com/13149513/160132120-8268a01e-2459-4d4c-892f-d0d744df56c7.png)
![Screenshot from 2022-03-25 13-41-55](https://user-images.githubusercontent.com/13149513/160132129-6a30ba47-044f-4cb5-9eb1-6e97c05ab2dc.png)

statusline doesn't change at all if I change window width.

**Comment by mrjones2014** [comment]
Kitty terminal version 0.24.4

Neovim version:

```
NVIM v0.7.0-dev+1302-g52fe8eae0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by mat@Mats-Mini-337.lan

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-52fe8ea/share/nvim"

Run :checkhealth for more info
```

**Comment by mrjones2014** [comment]
I just uninstalled Lualine and reinstalled. Still having the issue.

**Comment by mrjones2014** [comment]
Okay I found something in my config that is responsible for this. I'm a big dummy sorry to have wasted your time 😅
