### ISSUE TITLE
Bug: Inactive section is not visible

### ISSUE THREAD

**Issue by Mariownyou** [nvim-lualine/lualine.nvim#630]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

I can't find inactive section in the end of my screen
<img width="883" alt="image" src="https://user-images.githubusercontent.com/39639000/160598195-74acb49f-9f58-4490-b092-c5c9303d13a9.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/39639000/160598219-a586308a-cc8a-444c-8413-cfac463e8203.png">

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

</details>

**Comment by shadmansaleh** [comment]
If you don't have time to follow the issue template I don't have time to look at your issue.

**Comment by Mariownyou** [comment]
Sorry, I will create better one
