### ISSUE TITLE
Bug: Filetype component left padding background issue

### ISSUE THREAD

**Issue by mehalter** [nvim-lualine/lualine.nvim#631]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

1. Add a `filetype` component with a left padding and a custom foreground color

### Expected behavior

The padding background should match the rest of the background

### Actual behavior

The background of the icon and left padding is different

### Minimal config to reproduce the issue

```lua
  require("lualine").setup {
    sections = {
      lualine_a = {},
      lualine_b = {},
      lualine_y = {},
      lualine_z = {},
      lualine_c = {
        {
          "filetype",
          color = { fg = "#FFFFFF" },
          padding = { left = 2, right = 2 },
        },
      },
      lualine_x = {},
    },
  }
```

### Additional information

This bug has come up since #566 and was not present beforehand. This only affects the `filetype` component as far as I can tell and only the left padding (the normal background and right padding are fine) so I think it has something to do with the icons that are being used. I have provided a screenshot:

#### After #566 
![2022-03-29_12:05:05_screenshot](https://user-images.githubusercontent.com/1591837/160655885-c0c126d9-39ea-4404-af03-e6bd3c26388e.png)

#### Before #566

![2022-03-29_12:06:03_screenshot](https://user-images.githubusercontent.com/1591837/160656072-9e72c072-e3af-4db6-b609-b3049d17ba48.png)

**Comment by mehalter** [comment]
I can also confirm that it's not just the padding, it all stems from the icon background. If I simply remove all the padding I still get this:
![2022-03-29_12:13:01_screenshot](https://user-images.githubusercontent.com/1591837/160657531-9085b20e-4d9f-4357-aed5-7d073af7620d.png)

**Comment by shadmansaleh** [comment]
Does it happen if you specifically set a theme ? What colorscheme are you using ? I'm not sure why but
```lua
  vim.api.nvim_get_hl_by_name('StatusLine', true)
```
doesn't seem to return color info of that highlight group for default colorscheme. Might be an upstream bug.

**Comment by mehalter** [comment]
I have tested with 5 or 6 different themes as well as the default theme all of which exhibit the same behavior @shadmansaleh

**Comment by mehalter** [comment]
catppuccin, nightfox, onedark nvim, AstroVim default theme, and a few others. I have yet to find a theme that doesn't exhibit the behavior i described

**Comment by mehalter** [comment]
Also @shadmansaleh does lualine use the `StatusLine` highlight group? I haven't looked into the implementation but I thought it had a separate theming scheme for setting colors in the `lua/lualine/themes` folder

**Comment by shadmansaleh** [comment]
> Also @shadmansaleh does lualine use the StatusLine highlight group

`auto` theme does . And it's the default value of theme option . I had initially thought this only happened on auto theme . But that doesn't seem to be the case.

See if c8e5a69085e89c2bac6bd01c74fcb98f9ffa5cdc fixed it.

**Comment by mehalter** [comment]
Yup that fixed it. Thank you!
