### ISSUE TITLE
show filename in the center of the status line

### ISSUE THREAD

**Issue by lalitmee** [nvim-lualine/lualine.nvim#633]
Do we have a middle section? to put the things in the middle?

After `laststatus=3`, it feels we have so much space and we can use it. I was just looking for this to show the filename or anything in center.

Any ideas?

**Comment by shadmansaleh** [comment]
You can use regular `%=` statusline element for this.
```lua
lualine_c = {'%=', 'filename'}
```

Also discussions section is better suited for this kind of questions and it has been asked before .

**Comment by lalitmee** [comment]
@shadmansaleh , thanks and sorry. Will try to use `discussions` next time.
