### ISSUE TITLE
Feat: Mode name configurable.

### ISSUE THREAD

**Issue by singlexyz** [nvim-lualine/lualine.nvim#639]
Probably this is useless, just for watching.
The displayed text seems can be modified in mode.lua.
https://github.com/nvim-lualine/lualine.nvim/blob/master/lua/lualine/utils/mode.lua#L25

But the highlighting has no effect when changing the mode after modifying the text (always the same as the Normal mode).

<img width="349" alt="图片" src="https://user-images.githubusercontent.com/4456413/161824066-45d00aeb-8161-4ce5-8747-a26d1451f14c.png">

**Comment by shadmansaleh** [comment]
duplicate #614

Use a custom component as shown [here](https://github.com/nvim-lualine/lualine.nvim/issues/614#issuecomment-1072275099)
