### ISSUE TITLE
Bug: Git branch not updating when switching branches

### ISSUE THREAD

**Issue by asmodeus812** [nvim-lualine/lualine.nvim#640]
### Self Checks

- [X] I'm using the latest lualine.
- [ ] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
1. configured lua line to have a git branch component
2. Open a given git repository project, on branch0
3. Use fugitive to change the branch with Git checkout branch1
4. The lualine branch remains unchanged
5. Use fugitive to change the branch with Git checkout branch2
6. Lualine still shows branch0
7. Restart nvim, lualine shows correctly branch2

Note: same behaviour is present when doing git from the command line, lualine is not updating the branch when focusing and browsing the current buffer. Even if i browse a new file (not already opened) lualine branch still shows the old one. 

### Expected behaviour
Each time git branch is changed, lualine is updated immediately.

### Actual behaviour
Lualine branch element not updated after git checkout

### Minimal config to reproduce the issue

```Lua
    options = {
        component_separators = '',
        section_separators = '',
        theme = "auto",
    },
    sections = {
      lualine_a = {'mode'},
      lualine_b = {'branch', 'diff', 'diagnostics'},
      lualine_c = {'filename'},
      lualine_x = {'encoding', 'fileformat', 'filetype'},
      lualine_y = {'progress'},
      lualine_z = {'location'}
    }
}
```

**Comment by shadmansaleh** [comment]
Can't reproduce it on linux nor on windows . Previously there was one such issue in windows but it has long been fixed.

**Comment by asmodeus812** [comment]
@shadmansaleh i am working on wsl. How is updating the branch done anyway ? Is it polling, or querying git on vim events ? I am unable to make it update the branch. Any idea ?

**Comment by shadmansaleh** [comment]
> i am working on wsl

I tried on wsl2 ubuntu20.4 couldn't reproduce this.

> How is updating the branch done anyway ? Is it polling, or querying git on vim events ?

On unix we setup a filewatch so kernel notifies us when branch changes, on windows it's done by actively polling.

> I am unable to make it update the branch. Any idea ?

No idea . I'm unable to not make it update .  Also since you have fugitive you can use fugitives branch instead of lualines branch.

```lua
lualine_b = {'FugitiveHead', 'diff', 'diagnostics'},
```
