### ISSUE TITLE
Can I enable icons for individual modes in lualine?

### ISSUE THREAD

**Issue by sahashirshendu** [nvim-lualine/lualine.nvim#653]
I have a section in lualine as 
```lua
    lualine_a = {
      {
        "mode",
        -- icon = {}
        separator = { left = "", right = "" },
        right_padding = 2
      }
```
Is it possible to show icons corresponding to individual vim modes?
Maybe, via a table like ...
```lua
    ["n"] = " NORMAL",
    ["i"] = " INSERT",
    ["v"] =  " VISUAL",
    ["c"] = " COMMAND",
    ["t"] =  " TERMINAL",
```

**Comment by shadmansaleh** [comment]
duplicate #614 #639

follow https://github.com/nvim-lualine/lualine.nvim/issues/614#issuecomment-1072275099 to create a custom mode component.
