### ISSUE TITLE
Feat: Set the background as transparent

### ISSUE THREAD

**Issue by riceset** [nvim-lualine/lualine.nvim#655]
### Requested feature
I am using lualine with [LunarVim](https://github.com/LunarVim/LunarVim) and a theme called [sonokai](https://github.com/sainnhe/sonokai) with the option to set the background as transparent enabled.
The problem is that the part of the line containing the git branch and the file name aren't getting transparent.
How can I fix it?

![スクリーンショット 2022-04-17 午前0 25 18](https://user-images.githubusercontent.com/48802655/163698961-b3226e32-ad10-42fc-ae24-2e552619686f.png)

**Comment by shadmansaleh** [comment]
The theme you're using needs to set background color to nil or None . Since your theme is provided by your colorscheme and the transparent feature is provided by your colorscheme. You should open an issue there.

**Comment by riceset** [comment]
Ah, thank you!!
I just fixed it.
