### ISSUE TITLE
help wanted: allow users define their own filetypes

### ISSUE THREAD

**Issue by stark-zhang** [nvim-lualine/lualine.nvim#661]
### Requested feature

I want to apply user-defined filetype names, and I tried following configuration but not worked:

```lua
local extend_sections = {
    lualine_a = {
        'filetype',
        filetype_names = {
            ['dapui_scopes'] = 'DAP Scopes',
        },
    },
}

require 'lualine'.setup {
    extensions = {
        {
            sections = extend_sections,
            filetypes = { 'dapui_scopes', },
        }
    }
}
```

### Motivation

I am trying add nvim-dap and nvim-dap-ui into my nvim configurations, but the windows, opened by nvim-dap-ui show its filetype in `dapui_xxxxx`, I think that's not elegant. I prefer this in fact:

![](https://user-images.githubusercontent.com/24252670/126842672-de9c6b78-eec2-4187-b48e-977686ec4080.png)

or do you have other methods as workaround?

**Comment by stark-zhang** [comment]
I find the right way to define my own filetype, see this screenshot:

![image](https://user-images.githubusercontent.com/17326718/164942679-07416d76-fc4c-4a21-a14d-587b787e5bd4.png)

But I met another problem, the default sections of active windows configuration will be applied when DAP UI window is active, how to avoid applying default sections to specified window or buffer?

**Comment by shadmansaleh** [comment]
> I want to apply user-defined filetype names, and I tried following configuration but not worked:

I don't feel like custom filetypes falls under lualines domain . Besides you can use `fmt` option or a custom component to achieve this quite easily. 

> how to avoid applying default sections to specified window or buffer?

Set the ones you don't want to empty tables
```lua
local extend_sections = {
    lualine_a = {'filetype'},
    lualine_b = {},
    lualine_c = {},
    lualine_x = {},
    lualine_y = {},
    lualine_z = {},
}
