### ISSUE TITLE
Feat: Respect user-set `laststatus` when `globalstatus` not explicitly set

### ISSUE THREAD

**Issue by d12bb** [nvim-lualine/lualine.nvim#670]
### Requested feature

With #613 a new Lualine option `globalstatus` was introduced. However, it's default overrides a user-set `laststatus`. The correct way would imo be not having a default for `globalstatus` and instead falling back to `laststatus` if `globalstatus` was not set by user.

### Motivation
1. When someone wants to have a global statusline and types it into google, they will find Neovims `laststatus=3` first, wondering why it doesn't work until finding the Lualine setting.
2. (my case) When someone has `laststatus=3` already set before discovering and starting to use Lualine, it suddenly stops working, letting the user find out why.

**Comment by mosheavni** [comment]
I second that, took me a while to understand that lualine is overriding this setting.

**Comment by shadmansaleh** [comment]
I think this is a good idea.

**Comment by eXvimmer** [comment]
This is really annoying. lualine should not override user options. I have set globalstatus to true (as well as laststatus=3), but when I change my colorscheme it overrides it to 2.
