### ISSUE TITLE
Feat: Shift Lualine when NvimTree is active

### ISSUE THREAD

**Issue by par4m** [nvim-lualine/lualine.nvim#671]
### Requested feature
Basically something like this
![image](https://user-images.githubusercontent.com/68808783/166147640-8293a2ca-ad76-42fd-a3d6-a5397a6e12eb.png)
Source: https://github.com/feline-nvim/feline.nvim/issues/154

![image](https://user-images.githubusercontent.com/68808783/166149018-3b5285c9-fb90-46a0-95a8-9b6da163be60.png)
Source: https://github.com/LunarVim/LunarVim

**Comment by shadmansaleh** [comment]
LunarVim is using lualine itself 🤨

Just add NvimTrees filetype to `disabled_filetypes` option if you want similar look. Or use nvim-tree extension for special statusline on nvimtree buffer.

**Comment by par4m** [comment]
> LunarVim is using lualine itself raised_eyebrow
> 
> Just add NvimTrees filetype to `disabled_filetypes` option if you want similar look. Or use _nvim-tree_ _extension_ for special statusline on nvimtree buffer.

Already doing that but it doesn't shift the statusline towards right when NvimTree is active, saw the LunarVim config and they're doing something different and complicated, can't seem to figure out what tho

**Comment by shadmansaleh** [comment]
Give me your config and a screenshot of how it looks with your config right now. I'm not sure what you're looking for .

**Comment by par4m** [comment]
> Give me your config and a screenshot of how it looks with your config right now. I'm not sure what you're looking for . Just setting it to disabled filetype should work. Also can you point me which part of LuanerVims lualine config you don't understand ?

lualine config:
```lua
require("lualine").setup({
	options = {
		icons_enabled = true,
		theme = custom_lualine,
		component_separators = { left = "", right = "" },
		section_separators = { left = "", right = "" },
		disabled_filetypes = { "NvimTree", "TelescopePrompt", "packer", "toggleterm" },
		always_divide_middle = true,
		globalstatus = true,
	},
	sections = {
		lualine_a = { "mode" },
		lualine_b = { "diff", "diagnostics" },
		lualine_c = { "filename" },
		lualine_x = { "encoding", "fileformat", "filetype" },
		lualine_y = { "progress" },
		lualine_z = { "location" },
	},
	inactive_sections = {
		lualine_a = {},
		lualine_b = {},
		lualine_c = { "filename" },
		lualine_x = { "location" },
		lualine_y = {},
		lualine_z = {},
	},
	tabline = {},
	-- extensions = { "nvim-tree" },
})
```
Screenshot:
![image](https://user-images.githubusercontent.com/68808783/166156327-49bd2a20-e3d2-4db7-950e-89d02cb638b7.png)

Basically what I'm wondering is how to position lualine after VertSplit like 
![image](https://user-images.githubusercontent.com/68808783/166156923-bc1a4c0d-57d1-48a8-88cc-37b924879185.png)

**Comment by shadmansaleh** [comment]
This is not possible with globalstatus . It'll work if you turn globalstatus off . globalstatus will take up entire screen width that's the point of it :)

**Comment by par4m** [comment]
> This is not possible with globalstatus . It'll work if you turn globalstatus off . globalstatus will take up entire screen width that's the point of it :)

Just set globalstatus to false and it still doesnt seem to work, not sure what im doing wrong
Neovim version v0.8.0-dev+95-g07660193a3 btw
![image](https://user-images.githubusercontent.com/68808783/166157433-fe7584ed-ac97-4f8f-af0d-72ec5d393a20.png)

**Comment by shadmansaleh** [comment]
> Just set globalstatus to false and it still doesnt seem to work, not sure what im doing wrong

start nvim with -V1  as `nvim -V1` then run what's the output of `:set laststatus?` in nvim. What does it say ?

**Comment by shadmansaleh** [comment]
Looks like there's a simple way to do this even with globalstatus . You just need to place a dummy component in that beginning that shifts the statusline to right when nvim-tree is open like this.
```lua
local nvim_tree_shift =  {
  function () return string.rep(' ', require('nvim-tree').config.view.width - 2) end,
  cond = require('nvim-tree.view').is_visible,
  color = 'Normal'
}
require'lualine'.setup {
  sections = {
     lualine_a = { nvim_tree_shift, "mode" }
  }
}
```

**Comment by par4m** [comment]
Thank you that worked perfectly

**Comment by ehlxr** [comment]
> Looks like there's a simple way to do this even with globalstatus . You just need to place a dummy component in that beginning that shifts the statusline to right when nvim-tree is open like this.
> 
> ```lua
> local nvim_tree_shift =  {
>   function ()
>     return string.rep(' ',
>                       vim.api.nvim_win_get_width(require'nvim-tree.view'.get_winnr()) - 2)
>   end,
>   cond = require('nvim-tree.view').is_visible,
>   color = 'Normal'
> }
> 
> require'lualine'.setup {
>   sections = {
>      lualine_a = { nvim_tree_shift, "mode" }
>   },
>   tabline = {  -- If you want tabline to shift too
>      lualine_a = { nvim_tree_shift, "buffers" }
>   }
> }
> ```

referring this code, it can custom a title in the middle, like this

```lua
local nvim_tree_shift = {
    function()
        len = vim.api.nvim_win_get_width(require('nvim-tree.view').get_winnr()) - 1
        title = "Nvim-Tree"
        left = (len - #title) / 2
        right = len - left - #title

        return string.rep(' ', left) .. title .. string.rep(' ', right)
    end,
    cond = require('nvim-tree.view').is_visible,
    color = 'No'
}


require'lualine'.setup {
  
  tabline = {
     lualine_a = { nvim_tree_shift, "buffers" }
  }
}
```
<img width="601" alt="image" src="https://user-images.githubusercontent.com/11313370/171787099-c11776ba-5706-43bb-b526-ade27b606386.png">
