### ISSUE TITLE
Bug: Colour for diagnostics mismatch

### ISSUE THREAD

**Issue by asmodeus812** [nvim-lualine/lualine.nvim#681]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
Install lualine with packer and call lualine.setup. 
The colors for diagnostics seem to be incorrect
![image](https://user-images.githubusercontent.com/15955811/168302053-806e084d-4e80-4642-abfc-7f621966e907.png)
![image](https://user-images.githubusercontent.com/15955811/168302123-f53a26b1-7949-4dde-bdf6-52da2be861be.png)
![image](https://user-images.githubusercontent.com/15955811/168302783-33f0415e-a121-4c99-a328-21d1c0659e56.png)

Taken from lualine source, it seems that it should respect those hi groups.
```Lua
function M.apply_default_colors(opts)
  local default_diagnostics_color = {
    error = {
      fg = utils.extract_color_from_hllist(
        'fg',
        { 'DiagnosticError', 'LspDiagnosticsDefaultError', 'DiffDelete' },
        '#e32636'
      ),
    },
    warn = { 
      fg = utils.extract_color_from_hllist(
        'fg',
        { 'DiagnosticWarn', 'LspDiagnosticsDefaultWarning', 'DiffText' },
        '#ffa500' 
      ),
    },
    info = {
      fg = utils.extract_color_from_hllist(
        'fg',
        { 'DiagnosticInfo', 'LspDiagnosticsDefaultInformation', 'Normal' },
        '#ffffff'
      ),
    },
    hint = {
      fg = utils.extract_color_from_hllist(
        'fg',
        { 'DiagnosticHint', 'LspDiagnosticsDefaultHint', 'DiffChange' },
        '#273faf'
      ),
    },
  }
  opts.diagnostics_color = vim.tbl_deep_extend('keep', opts.diagnostics_color or {}, default_diagnostics_color)
end
```

### Expected behaviour
Color should be respected

### Actual behaviour
Instead lualine renders weird dark grey.

### Minimal config to reproduce the issue
No configuration has been applied just calling lualine.setup()

### Aditional information
using everforest theme.

**Comment by shadmansaleh** [comment]
Did you set your colorscheme before calling lualine.setup ?

**Comment by asmodeus812** [comment]
@shadmansaleh yes, colorsheme is set before i call lualine, and i have added explicitly the theme property in the lualine setup function to be 'everforest'. Other colors seems to work fine i think.

**Comment by asmodeus812** [comment]
@shadmansaleh any update on that, what i noticed is changing the theme does change the highlights but for some themes it seems to be wrong. I am testing with community themes such as gruvbox (which also does not work) the highlights for diagnostics are all messed up

**Comment by shadmansaleh** [comment]
I didn't get to take a look at it yet. Can you provide a minimal config with https://github.com/nvim-lualine/lualine.nvim/blob/master/scripts/nvim_isolated_conf.sh ?

**Comment by shadmansaleh** [comment]
Does this issue still exists ? I never got this issue to reproduce and you never provided an isolated minimal config either.

**Comment by mmrzax** [comment]
I also experienced this problem only with everforest.
![20220820_01h19m28s_grim](https://user-images.githubusercontent.com/87857699/185739769-814293d8-0345-44cf-867d-faa694263f97.png)

**Comment by shadmansaleh** [comment]
Giving a screenshot won't help because I still can't reproduce it . Make an isolated minimal config that shows this bug occurs outside of your config. 

As many times as I seen this issue been reported it was because user was using wrong ordering for their colorscheme and lualine (like not setting colorscheme before setting up lualine, having strange loading order while lazy loading lualine etc)  or any other plugin or userconfig reseting highlights.

 Unless I can reproduce the issue I can't possibly fix the issue. If it's part of your config I'm not gonna go through your entire configs and plugins so If you have an issue you need to provide a config that reproduced the issue without interacting with other plugins or rest of your plugin.

**Comment by antoineco** [comment]
@asmodeus812 @mmrzax see the above PR for an explanation of the issue you're seeing, and a proposed fix in Lualine.
