### ISSUE TITLE
Bug: inactive (new) buffer(s) does not have correct sections

### ISSUE THREAD

**Issue by NullVoxPopuli** [nvim-lualine/lualine.nvim#683]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
1. open neovim
2. open a buffer
3. split / create new buffer, open new file
4. switch focus between buffers a few times
5. notice that the first buffer has the `inactive_sections`, but the second buffer does not

https://user-images.githubusercontent.com/199018/168485271-22c27870-d512-465e-9b34-1bd970897403.mp4

### Expected behaviour

inactive sections are present on all inactive buffers

### Actual behaviour

inactive sections are present only on first buffer

### Minimal config to reproduce the issue

<details><summary>Config</summary>

```lua
  use {
    'nvim-lualine/lualine.nvim',
    config = function ()

      require('lualine').setup {

        options = {
          theme = 'dracula',
        },
        extensions = { 'fzf', 'nvim-tree' },

        sections = {
          lualine_a = { {'mode', upper = true} },
          -- lualine_b = { {'branch', icon = ''} },
          lualine_b = { {'diff'} },
          lualine_c = { {'filename', file_status = false, path = 1 } },
          lualine_x = { 'filetype' },
          lualine_y = { 'progress' },
          lualine_z = { 'location'  },
        },
        inactive_sections = {
          lualine_a = {  },
          -- lualine_b = {  },
          lualine_b = { {'branch', icon = ''} },
          lualine_c = { {'filename', file_status = true, path = 1 } },
          lualine_x = {  },
          lualine_y = {  },
          lualine_z = {  }
        },
      }

    end
  }
```

</details>

**Comment by shadmansaleh** [comment]
Does this issue still happen on master. I never managed to reproduce it.
