### ISSUE TITLE
Bug: 'tabs' component -- highlight of rightmost active tab does not reset

### ISSUE THREAD

**Issue by BojanStipic** [nvim-lualine/lualine.nvim#690]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

1. Add `'tabs'` component in `lualine_a` section in `tabline`.
2. Open 2 or more tabs

### Expected behaviour

Active tab is correctly highlighted as displayed on the picture below:

![image](https://user-images.githubusercontent.com/13490088/169862777-8365ffb7-a505-4a5d-9399-fdbc5271524d.png)

Active tab should always be highlighted like this.

### Actual behaviour

But, if the active tab is the rightmost tab, then the green highlight color is not reset, and we get something like this:

![image](https://user-images.githubusercontent.com/13490088/169863319-62bdaadf-d386-4260-92e9-420f56993a60.png)

The green highlight extends to the end of the line.

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

```lua
require('lualine').setup({
    options = {
        icons_enabled = false,
        always_divide_middle = false,
        component_separators = '',
        section_separators = '',
    },
    sections = {
        lualine_x = {},
        lualine_y = { 'filetype' },
        lualine_z = { 'progress', 'location' },
    },
    tabline = {
        lualine_a = {
            {
                'tabs',
                max_length = vim.o.columns,
                mode = 2,
            },
        },
    }
})
```

</details>

**Comment by BojanStipic** [comment]
Thanks for your response. It does seem to work correctly when `always_divide_middle = true`. But I still consider it an issue because I would like to have `always_divide_middle = false`.

**Comment by shadmansaleh** [comment]
> because I would like to have always_divide_middle = false

why ?

**Comment by BojanStipic** [comment]
Because I may open a file with a very long name, and I want it to take as much space as it needs in `lualine_c` section of my statusline, instead of truncating at the middle of the screen.

Or am I completely misunderstanding what this option does? I just tried without it, and it seems to work the same either way. I dont quite understand the description in `:h lualine-Global-options`.

**Comment by shadmansaleh** [comment]
always_divide_middle  means completely different thing . when always_divide_middle is set to false and you have only left side sections a,b,c set it'll let them flow into right sections means it won't create a left, right divider with %= . You almost never want to set this to false unless you want the last component to fill tell end of statusline that's what's happening here.
