### ISSUE TITLE
Feat: Winbar support

### ISSUE THREAD

**Issue by mrjones2014** [nvim-lualine/lualine.nvim#692]
### Requested feature

Just like how Lualine supports both statusline (including global statusline) and tabline, it should also support the new `winbar`. I would love to show the buffer list in each window, with each window showing the active buffer as the buffer active in it's specific window. I currently have a fork of bufferline.nvim doing this but its jank and buggy.

### Motivation

Lualine already has a built-in `buffers` component, and already supports statusline and tabline. winbar feels like a very natural extension to that. I would love to be able to use Lualine's API to build out my `winbar` configuration.

**Comment by shadmansaleh** [comment]
See my response [here](https://github.com/nvim-lualine/lualine.nvim/pull/689#issuecomment-1133937406). Relevent discussion https://github.com/nvim-lualine/lualine.nvim/discussions/688
