### ISSUE TITLE
Is there any ways to keep my lualine still?

### ISSUE THREAD

**Issue by NEX-S** [nvim-lualine/lualine.nvim#710]
if i switch to another window like 'NvimTree', i wish to keep my lualine in my main buffer, is there any  options can reach this? If we can keep lualine switching in main buffer except some window ( NvimTree ), that could be better :D

**Comment by shadmansaleh** [comment]
When you switch to NvimTree that buffer becomes you're active buffer/window and lualine shows it's active statisline . If you don't want this differentiation you can set your section & inactive_section in the config identical . That way it'll look same always . Than you can use filetype specific extention to show different statusline for different filetypes.

**Comment by diegoulloao** [comment]
@shadmansaleh works adding:
```lua
ignore_focus = { "NvimTree" }
```

but, how I do it for telescope? I tried `telescope`, `Telescope` and `fzf` but none of those works.

**Comment by diegoulloao** [comment]
ok I found out that `globalstatus = true` inside `options` works.
