### ISSUE TITLE
Bug: lualine.nvim breaks after calling <Plug>(coc-rename)

### ISSUE THREAD

**Issue by epixinvites** [nvim-lualine/lualine.nvim#718]
### How to reproduce the problem
Run `(Plug)<coc-rename>`

### Expected behaviour
Well, rename.

### Actual behaviour
![20220626-095637](https://user-images.githubusercontent.com/54717060/175796161-ca073be2-e9bb-4d34-976e-f99f425edb59.png)

### Not-so-minimal config to reproduce the issue
[init.vim](https://termbin.com/jh9y)

[statusline-config.lua](https://termbin.com/umi6)

[coc-settings.json](https://termbin.com/x9gk)

**Comment by shadmansaleh** [comment]
Sorry but it cannot be expected of me to go through your config and find which plugin interaction causing an error. You'll have to provide a isolated minimal config (TBH I don't think coc.nvim itself can be part of any minimal config it itself is a really massive thing). Without that I can't be look into this issue.

**Comment by epixinvites** [comment]
Sorry for the late reply, here's the minimal reproducible config as promised.

![20220808-155614](https://user-images.githubusercontent.com/54717060/183372414-79980ee2-ae3e-40ec-9abd-60c0f3ffcc9f.png)

Minimal reproducible config:
coc-settings.json -> https://termbin.com/pili
init.vim -> https://termbin.com/z40l

I have located the problematic portion of code, and it's somewhere inside the custom statusline config I have attached in the init.vim.
