### ISSUE TITLE
Looks like diagnostics module's icons can't be customized

### ISSUE THREAD

**Issue by graelo** [nvim-lualine/lualine.nvim#720]
Thanks a lot from this awesome plugin.

### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in existing issues or prs.

### How to reproduce the problem
I've successfully customized other modules (such as branch and filename), but I'm failing at configuring the diagnostics icons. I tried:

```lua
{
  'diagnostics',
    icons_enabled = true,
    -- symbols = {    -- I tried with and without this wrapping
    icons = {
      error = '', -- xf659, shows up in my terminal
      warn = '',  -- xf529, idem
      info = '',  -- xf7fc, idem
      hint = '⚡',  -- xf835, idem
    }
    -- }
}
```

I checked that setting `icons_enabled = false` results in the text equivalents being shown, so I guess my config is not completely south.

I'm a lua newbie, but I suspect in this code the customized icons are always overridden by the default ones or text replacements.
https://github.com/nvim-lualine/lualine.nvim/blob/master/lua/lualine/components/diagnostics/init.lua#L25-L30

### Expected behaviour
I would expect my custom icons to be displayed instead of the default ones.

### Actual behaviour
The default icons are always displayed.

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>
Sorry, I'll first try posting this issue without doing this intimidating task. I'll do it if you really want it to solve this issue, but my guess is that the initialization code has a small issue.

</details>

**Comment by shadmansaleh** [comment]
The [docs](https://github.com/nvim-lualine/lualine.nvim#diagnostics-component-options) says 
```lua
{
  'diagnostics',
      symbols = {
      error = '', -- xf659, shows up in my terminal
      warn = '',  -- xf529, idem
      info = '',  -- xf7fc, idem
      hint = '⚡',  -- xf835, idem
    }
}
```
did you try that ? there's no `icons` tabel.

**Comment by graelo** [comment]
No, I missed this. It's working now, thanks!
