### ISSUE TITLE
Bug: lualine.lua:187: bad argument #1 to 'ipairs' (table expected, got nil)

### ISSUE THREAD

**Issue by Davincible** [nvim-lualine/lualine.nvim#725]
I'm not sure what's causing it, but something is giving me this error:

```
E5108: Error executing lua ...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:187: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
        [C]: in function 'ipairs'
        ...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:187: in function 'get_extension_sections'
        ...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:297: in function <...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:287>
```

Using evilline theme

**Comment by shadmansaleh** [comment]
Extensions table shouldn't be nil. Even if user doesn't provide it it should be filled with default value by the config system . Can you provide an isolated minimal config for reproduction. https://github.com/nvim-lualine/lualine.nvim/blob/master/scripts/nvim_isolated_conf.sh should help
