### ISSUE TITLE
Feat: Add scrollbar to status line

### ISSUE THREAD

**Issue by gerazov** [nvim-lualine/lualine.nvim#728]
Awesome plugin :sunglasses: 

### Requested feature

I'm coming from [vim-airline](https://github.com/vim-airline/vim-airline) and there is a nice feature I miss in lualine called scrollbar that shows the relative position in the buffer via a bar. 

![scrollbar_2](https://user-images.githubusercontent.com/15214418/177369234-eedada0e-899b-433a-9eed-cba8fd27c8b4.gif)

### Motivation

This a bit easier to process than reading the percentage or line number tally so it's more comfortable once you get used to it.

**Comment by shadmansaleh** [comment]
I don't feel like this needs to be a component provided by lualine . It can be easily made with a custom component. for example try following
```lua
lualine_c = {function()
    local pos = math.floor(20 * (vim.fn.line('.') / vim.fn.line('$'))) -- replace 20 with whatever length you need
    return table.concat {
              pos ~= 0 and '|' or '',
              string.rep(' ', pos - 1),
              '█',
              string.rep(' ', 20 - pos), -- same goes here
              pos ~= 20 and '|' or ''}
end}
```

**Comment by gerazov** [comment]
Looks awesome :sunglasses: - I will give it a whirl.
