### ISSUE TITLE
Help: How to get rid of space between two components?

### ISSUE THREAD

**Issue by sabah1994** [nvim-lualine/lualine.nvim#730]
Hi,

First of all, thank you for such an  amazing plugin.

I'm trying to put file_icon and file_name right next to each other but there is extra space which I don't know how to get rid of. I have  put left and right separators to empty strings but space still exists. 

My  config.

```
        lualine_c = {
            {"filetype", icon_only = true, component_separators = {left = "", right = ""}},
            {"filename", color = {gui = "bold,italic", fg = "#ebdbb2"}}
        },
```
My output currently.
![lualine](https://user-images.githubusercontent.com/73726199/178019179-f56d67e7-ac13-45b9-9b5e-9fd4968c4108.jpg)

**Comment by shadmansaleh** [comment]
use the padding option.
```lua
        lualine_c = {
            {"filetype", padding={right=0}, icon_only = true, component_separators = {left = "", right = ""}},
            {"filename", padding={left=0}, color = {gui = "bold,italic", fg = "#ebdbb2"}}
        },
```
