### ISSUE TITLE
Bug: Startup cmdline message disappears in a flash

### ISSUE THREAD

**Issue by bezlant** [nvim-lualine/lualine.nvim#733]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
This is done on an empty nvim config, I only have plenary.nvim & popup.nvim besides.
1. Add configs from below
2. Add them in init.lua (require(lualine) require(colorscheme))
3. Startup nvim
4. Here you can see a message actually appears for a milisecond
![colorscheme bug](https://user-images.githubusercontent.com/89563512/178186926-fa1dda4e-1dfa-4d3b-8b82-fdb5a8947a4e.gif)

### Expected behaviour
Lualine shows error messages on startup

### Actual behaviour
I have been debuging it for a while and finally found out that whenever I have lualine turned on error messages on startup disappear in a flash. I can still see it in `:message` but I'd like to be able to see it without disappearing.

### Minimal config to reproduce the issue
lualine.lua
```
require('lualine').setup {
    options = {
        theme = 'dracula-nvim',
        globalstatus = true,
    }
}
```
colorscheme.lua (where error occurs, I don't have the specified colorscheme)
```
local colorscheme = "newcolorscheme"

local status_ok, _ = pcall(vim.cmd, "colorscheme " .. colorscheme)
if not status_ok then
    vim.notify("colorscheme " .. colorscheme .. " not found!")
    return
end
```

**Comment by shadmansaleh** [comment]
It's not a lualine bug . You don't need lualine to reproduce this issue. just set laststatus option to 3 and it'll act the same. Simply when you enable globalstatus nvim needs to do a full screen redraw . And cmdline gets cleared on redraw. It's neovims behavior nothing lualine can do about it.

**Comment by bezlant** [comment]
@shadmansaleh I appreciate the detailed answer. Have a nice day! :)
