### ISSUE TITLE
Feat: Location: `Top` and `Bot` when at the top or bottom of the buffer

### ISSUE THREAD

**Issue by WhyNotHugo** [nvim-lualine/lualine.nvim#737]
Didn't find any issues or mentions of this.

### Requested feature

Vim itself shows `Top` and `Bot` (for `Bottom`) when one scrolls to the top or bottom of the buffer.

I'd appreciate the `location` module doing the same.

Seems that this should be done here: https://github.com/nvim-lualine/lualine.nvim/blob/ad4f4ff7515990b5b2a01bc3933346e11ebf0301/lua/lualine/components/location.lua#L3

### Motivation

Lualine is a big upgrade on the vanilla statuslines, but this is one tiny feature the vanilla one has that I'd like to retain.

I can try figuring out a patch to do this if it sounds okay.

**Comment by shadmansaleh** [comment]
You can just use the vanilla one with lualine. You just need to use %P in place of location. Checkout `:h stl` to see other builtin statusline format specifiers and read the README to know how you can customize lualine.
```lua
lualine_z = {'%P'}
```

**Comment by WhyNotHugo** [comment]
Thanks!

**Comment by WhyNotHugo** [comment]
Oh, the built-in one also render "All" when the whole file fits on screen.
