### ISSUE TITLE
Bug: Behavior of $ changes when in visual mode.(neovim Problem?)

### ISSUE THREAD

**Issue by rapan931** [nvim-lualine/lualine.nvim#741]
### Self Checks

- [x] I'm using the latest lualine. (588cf4185bf38875604d5c82efb34dd0ad2eed1f)
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
1. Place lualine.nvim(588cf4185bf38875604d5c82efb34dd0ad2eed1f) in ~/.local/share/nvim/mini/pack/p/start/
2. nvim --clean
3. :let &packpath = stdpath('data') .. '/mini/'
4. :runtime lualine.nvim
5. isome text\<Esc\>
6. 0v$
7. \<Esc\>
8. :lua require('lualine').setup({})
9. 0v$  (**behavior changes step 6**)

![Animation](https://user-images.githubusercontent.com/24415677/179119889-e17d72ff-90b8-4bb8-9ab2-6470fce10ac8.gif)

### Expected behaviour
selected `some text ` (some text + 1)

### Actual behaviour
selected `some text`

### Minimal config to reproduce the issue
- env
  - nvim --version
  NVIM v0.8.0-dev+608-g778541067
  Build type: RelWithDebInfo
  - wsl(windows 10 ubuntu)

### Aditional information
The following versions not reproduce....
  - nvim --version
    NVIM v0.7.3-dev+8-gb8da4303f
    Build type: RelWithDebInfo

**Comment by shadmansaleh** [comment]
I can reproduce it but can't think of any reason of this to happen . Since it happens only on nightly it's possible it's a neovim bug . I guess will just have to bisect nvim and figure out which commit caused it . zeertzq is porting lots of vim patches it might be from one of them. did you check if other statuslines have similar issue ?

**Comment by rapan931** [comment]
Thanks for the quick reply.
>  I guess will just have to bisect nvim and figure out which commit caused it .
I'll try it!

**Comment by shadmansaleh** [comment]
I did the bisect it seems to start from this commit [87a68b6a3ab483c6b126fa8071066a112f9386a3](https://github.com/neovim/neovim/commit/87a68b6a3ab483c6b126fa8071066a112f9386a3)

**Comment by shadmansaleh** [comment]
It's a neovim bug . You can reproduce this with just 2 lines (basically a funciton evaluating option with vim.bo* in statusline).

```lua
function stl() return vim.bo.filetype end
vim.go.stl = '%!v:lua.stl()'
vim.api.nvim_feedkeys(
  vim.api.nvim_replace_termcodes('isome text<Esc>0v$', true, false, true), 'i', false)
```

Just write this in minimal_init.lua and run
```sh
nvim --clean -u minimal_init.lua
```

**Comment by shadmansaleh** [comment]
You should still open a proper issue there . I just added a comment in the pr.

**Comment by rapan931** [comment]
OK. Created issue to neovim https://github.com/neovim/neovim/issues/19381

**Comment by shadmansaleh** [comment]
fixed upstream.

**Comment by rapan931** [comment]
I can confirm that this has been corrected in the latest neovim.
Thanks for the support!
