### ISSUE TITLE
Feat: global statusline should still displays for all filetypes, including `ignored_filetypes`

### ISSUE THREAD

**Issue by lkhphuc** [nvim-lualine/lualine.nvim#744]
### Requested feature
When global statusline is used, statusline should works for all buffer, including those in `disabled_filetypes` tables.

### Motivation

`disabled_filetypes` is used to prevent rendering a crammed statusline in overly small windows, this doesn't apply with global statusline.

- One option is just to not disabled any filetypes, but that means winbar (if it is ever officially supported #736 ) will not ignore some filetypes with small windows either.
- Another option is to have separate options, i.e `statusline_disabled_filetypes` and `winbar_disabled_filetypes` (again if it's ever supported)
- Or just ignore `ignored_filetypes` altogether when using global statusline.

**Comment by shadmansaleh** [comment]
I think I'll just let users specify which filetypes are to be ignored for winbar. That gives more control to user.
