### ISSUE TITLE
Bug: weird behavior when opening float windows like diagnostics

### ISSUE THREAD

**Issue by GustavoKatel** [nvim-lualine/lualine.nvim#751]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in existing issues or prs.

### Expected behaviour

Here's the same config running with commit 8d956c18258bb128ecf42f95411bb26efd3a5d23

https://user-images.githubusercontent.com/1891977/180610355-badf4019-dba5-4d9d-9d01-65723d8fe02f.mov

### Actual behaviour

Running with the latest commit

https://user-images.githubusercontent.com/1891977/180610371-e6f38c60-5bf7-4146-92bc-8d65788aed90.mov

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

```viml
call plug#begin("/Users/gustavokatel/dev/lualine-bug/minimal/.local/share/nvim/plugged")
" Your plugins go here like
Plug 'nvim-lualine/lualine.nvim'


call plug#end()

lua << END
-- Your lua part of config goes here
require'lualine'.setup({
	options = {
		section_separators = "",
		component_separators = "|",
	},
	sections = {
		lualine_b = {},
		lualine_c = {
			{
				"filename",
				file_status = true, -- displays file status (readonly status, modified status)
				path = 1, -- 0 = just filename, 1 = relative path, 2 = absolute path
			},
			"diagnostics",
		},
		lualine_x = { "fileformat", "filetype" },
	},
	inactive_sections = {
		lualine_c = {
			{
				"filename",
				file_status = true, -- displays file status (readonly status, modified status)
				path = 1, -- 0 = just filename, 1 = relative path, 2 = absolute path
			},
		},
		lualine_x = { "location" },
	},
	tabline = {
		lualine_a = {},
		lualine_b = { "branch" },
		lualine_c = {},
		lualine_x = {},
		lualine_y = {},
		lualine_z = {},
	},
})

vim.cmd("edit test.lua")

local bufnr = vim.api.nvim_get_current_buf()

vim.api.nvim_buf_set_lines(0, 0, 0, true, { "test text" })

vim.api.nvim_win_set_cursor(0, {1, 0})

local ns = vim.api.nvim_create_namespace("test_ns") 

vim.diagnostic.set(ns, bufnr, {
    {
            bufnr = bufnr,
            lnum = 0,
            col = 1,
            message = "test test",
    }
})

vim.keymap.set("n", "K", function()
    vim.diagnostic.open_float({
        border = "rounded",
        focusable = false,
        prefix = function(_, i)
            return i .. ". "
        end,
    })
end)


END
```

</details>

### Aditional information

Steps to reproduce:

- open the minimal config
- press `<S-k>` to open diagnostics float window

**Comment by shadmansaleh** [comment]
I think it's related to https://github.com/neovim/neovim/issues/15300.

The diagnostic float is triggering WinEnter so we refresh the stausline gets rendered in the floats context but then it doesn't trigger any other WinEnter event for returning to original window. So we need to wait for statusline timer to trigger another update which by default can take upto 1s. 

It's basically because of a bug in nvim where events aren't symatric for floats with enter false.

**Comment by hnry** [comment]
I'm experiencing this. Just switched to lualine from airline, have the default README setup. 

What can I do?
