### ISSUE TITLE
Tabline renders redundant `[No Name]` buffer

### ISSUE THREAD

**Issue by numToStr** [nvim-lualine/lualine.nvim#753]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

- Run the minimal config.
- Run `:Telescope find_files`
- And Press <kbd>Ctrl-d</kbd> and <kbd>Ctrl-u</kbd> to navigate the preview

### Expected behaviour
Tabline renders redundant `[No Name]` buffers on some actions like navigating telescope entry preview, and pasting text. _Apart from this I also noticed that there is some (initial) delay when updating tabline._

### Actual behaviour
There shouldn't be any `[No Name]` buffers. 

### Minimal config to reproduce the issue

(I am skipping LSP setup to keep the minimal init.vim concise, but I recommend it while testing)

<details>
<summary>Config</summary>

```vim
call plug#begin("/tmp/lualine-bug/.local/share/nvim/plugged")
" Your plugins go here like
Plug 'nvim-lualine/lualine.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'

call plug#end()

lua << END
local g = vim.g
local o = vim.o

o.termguicolors = true

-- Decrease update time
o.timeoutlen = 500
o.updatetime = 200

-- Number of screen lines to keep above and below the cursor
o.scrolloff = 8

-- Better editor UI
o.number = true
o.numberwidth = 6
o.relativenumber = true
o.signcolumn = 'yes'
o.cursorline = true

-- Better editing experience
o.expandtab = true
o.cindent = true
o.wrap = true
o.textwidth = 300
o.tabstop = 4
o.shiftwidth = 0
o.softtabstop = -1 -- If negative, shiftwidth value is used
o.list = true
o.listchars = 'trail:·,nbsp:◇,tab:→ ,extends:▸,precedes:◂'

-- Makes neovim and host OS clipboard play nicely with each other
o.clipboard = 'unnamedplus'

-- Case insensitive searching UNLESS /C or capital in search
o.ignorecase = true
o.smartcase = true

-- Undo and backup options
o.backup = false
o.writebackup = false
o.undofile = true
o.swapfile = false

-- Remember 50 items in commandline history
o.history = 50

-- Better buffer splitting
o.splitright = true
o.splitbelow = true

-- Preserve view while jumping
o.jumpoptions = 'view'

-- Map <leader> to space
g.mapleader = ' '
g.maplocalleader = ' '


-- Your lua part of config goes here
require('lualine').setup({
    options = {
        component_separators = '',
        section_separators = '',
        icons_enabled = true,
        globalstatus = true,
    },
    sections = {
        lualine_a = {
            { 'mode', color = { gui = 'bold' } },
        },
        lualine_b = {
            { 'branch' },
            { 'diff', colored = false },
        },
        lualine_c = {
            { 'filename', file_status = true },
            { 'diagnostics' },
        },
        lualine_x = {
            'filetype',
            'encoding',
            'fileformat',
        },
        lualine_y = { 'progress' },
        lualine_z = {
            { 'location', color = { gui = 'bold' } },
        },
    },
    tabline = {
        lualine_a = {
            {
                'buffers',
                buffers_color = { active = 'lualine_b_normal' },
            },
        },
        lualine_z = {
            {
                'tabs',
                tabs_color = { active = 'lualine_b_normal' },
            },
        },
    },
    extensions = { 'quickfix', 'nvim-tree' },
})

local actions = require('telescope.actions')

require('telescope').setup({
    defaults = {
        prompt_prefix = ' ❯ ',
        initial_mode = 'insert',
        sorting_strategy = 'ascending',
        layout_config = {
            prompt_position = 'top',
        },
        mappings = {
            i = {
                ['<ESC>'] = actions.close,
                ['<C-j>'] = actions.move_selection_next,
                ['<C-k>'] = actions.move_selection_previous,
                ['<TAB>'] = actions.toggle_selection + actions.move_selection_next,
                ['<C-s>'] = actions.send_selected_to_qflist,
                ['<C-q>'] = actions.send_to_qflist,
            },
        },
    },
})

END
```

</details>

### Aditional information

As you can see, pasting and navigating telescope previews renders `[No Name]` buffers. I can replicate this with the minimal and my personal config.

NOTE: You don't need to consider the initial `[No Name]` buffer

https://user-images.githubusercontent.com/24727447/180722886-7ff792f5-644b-4c0a-b191-e567b564a03e.mp4

Edit: After digging through the git history I suspect #736 to be the issue as there is no issue on comit 8d956c18258bb128ecf42f95411bb26efd3a5d23.

**Comment by shadmansaleh** [comment]
I think telescope preview window doesn't set a filename or filetype . So when they switch to the preview win to scroll lualine tabliine refeshes in that context. We ignore unnamed buffers unless it's current buffer in that case it's rendered as [No Name] .

I think we need to ask telescope to mark the preview buffer too as the TelescopePrompt and TelescopeResult so they can be given specific name.

**Comment by petobens** [comment]
> I think we need to ask telescope to mark the preview buffer too as the TelescopePrompt and TelescopeResult so they can be given specific name.

Hi! I'm seeing the same behaviour when scrolling the preview window  generated by cmp so I guess this is not specific to Telescope but more general?

![cmp gif](https://user-images.githubusercontent.com/2583971/181143550-189dc449-75b2-4910-8771-8019da24b836.gif)

**Comment by numToStr** [comment]
Nice catch @petobens! I can also reproduce this.

https://user-images.githubusercontent.com/24727447/181166491-f7c8ca76-035c-4ea8-9883-7c59d2dedf81.mp4

**Comment by numToStr** [comment]
This is also present in the lsp hover ie. `vim.lsp.buf.hover()`

https://user-images.githubusercontent.com/24727447/181174389-d3bc7b62-1bd5-4094-be26-6e98bd31834c.mp4
