### ISSUE TITLE
Bug:  E315: ml_get: invalid lnum when using winbar

### ISSUE THREAD

**Issue by lkhphuc** [nvim-lualine/lualine.nvim#754]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

- Install packer and lualine
- Enable winbar = {...} in setup.
- Open nvim
- Open a new buffer (`:help ...`) (OK)
- Enter insert mode / move cursor around
- Open a new buffer ( `:help ...` or floaterm ...)

### Expected behaviour
No E315 error

### Actual behaviour
- A page of E315: ml_get: invalid lnum 
![Screenshot 2022-07-25 at 12 34 17](https://user-images.githubusercontent.com/12573521/180768506-5457aaa1-a8b9-4336-b8a8-19e2dd7a5330.png)

### Minimal config to reproduce the issue
Minimal config with just packer and lualine, on neovim nightly 0.8 (the past 3-4 days all has problems).

### Aditional information
If winbar is disabled in setup `winbar = {}`, I don't get the error even if I have configured `inactive_winbar = {...}` . It's only happens with `winbar`.

The first commit that reproduce this problem for me is https://github.com/nvim-lualine/lualine.nvim/pull/736 but I don't have this problem during testing this branch before it was merged.

**Comment by lkhphuc** [comment]
Oh I just found out about this https://github.com/neovim/neovim/issues/19458 , somehow google doesn't found the latest issue but only show me old one.
Closing this to track over there.

**Comment by augustocdias** [comment]
Facing the same issue :(
When using winbar I can't execute `PackerSync` because of this error

Did anyone find a workaround?
