### ISSUE TITLE
Bug:  E539: Illegal character < > in statusline error

### ISSUE THREAD

**Issue by AngerM** [nvim-lualine/lualine.nvim#756]
### Self Checks

- [ x ] I'm using the latest lualine.
- [ x ] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
Unsure. Seems to happen randomly when using lualine

### Expected behaviour
Lualine doesn't error

### Actual behaviour
```
Error executing vim.schedule lua callback: ...er/.vim/plugged/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
...vim/plugged/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
        [C]: in function 'error'
        ...er/.vim/plugged/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Minimal config to reproduce the issue
My lualine config is rather minimal:
```
lua << END
require('lualine').setup{
  sections = { lualine_a = { 'g:coc_status', 'bo:filetype' } }
}
 END
```

```
vi --version
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.2_1/share/nvim"

Run :checkhealth for more info
```
</details>

**Comment by shadmansaleh** [comment]
I think it's related to #746  See https://github.com/nvim-lualine/lualine.nvim/issues/746#issuecomment-1192694168 .

I think coc_status has unescaped % in it's value.
So try escaping them.
```lua
require('lualine').setup{
  sections = { lualine_a = { 
    function() return vim.pesc(vim.g.coc_status or '') end,
    'bo:filetype' } }
}
```

**Comment by AngerM** [comment]
Hmm tried that, getting a slightly different error: 
```
Error executing vim.schedule lua callback: ...er/.vim/plugged/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
...vim/plugged/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character <s>
```

**Comment by shadmansaleh** [comment]
Are you sure you don't have anything else in your lualine config ?

It seems unlikely you'll be hitting this error otherwise. What's the output of `:lua =require'lualine'.get_config()` ?

**Comment by shadmansaleh** [comment]
Check if 788805771c1ca7fe2c6652c38523cf208908934c fixed it.

**Comment by AngerM** [comment]
So far so good!

**Comment by J4ckTh3R1pper** [comment]
I'm still having this issue when trying to display coc_status in statusline
