### ISSUE TITLE
Bug: ```^``` symbols appearing down the middle

### ISSUE THREAD

**Issue by marko-cerovac** [nvim-lualine/lualine.nvim#761]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Open a window split or start typing in the cmdline.

### Expected behaviour
Normal lualine behaviour

### Actual behaviour
So far, I've found two ways to produce this issue. The first is when I have more than one window open (for example when I use ```:vsplit```. As soon as I split the screen, the middle section gets filled with ```^^^^^^^``` symbols.
![split-window](https://user-images.githubusercontent.com/76592799/181284239-ee1fb52a-e4a8-4b14-8a5f-54e189dcf5c2.png)

Another way is when I enter the command mode. As soon as I start typing into the nvim cmdline, the symbols appear again.
![command-mode](https://user-images.githubusercontent.com/76592799/181284277-75bc5f08-5bd2-44fc-b806-f9624866022f.png)

This problem doesn't occur with the default neovim statusline.

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

</details>

**Comment by shadmansaleh** [comment]
Set stl in your `fillchar` option to ' ' from '^'.

**Comment by marko-cerovac** [comment]
It didn't help. The option was already set to ' '. It only gets filled with '^' when I split windows or write something in the cmdline. Also, If I set the fillchars to something other than ' ', (for example '~'), the statusline always shows '~' and it doesn't switch to '^' like in the pictures.

**Comment by shadmansaleh** [comment]
I can't reproduce the issue like you said. You'll have to provide an isolated minimal config that guarantees a reproduction .

TBH it's not a lualine issue rather a nvim/vim one. I've previously seen sometimes raw nvim/vim fills spaces in statusline with '^' or fillchar. I think this one is also same .

**Comment by marko-cerovac** [comment]
Okay, thanks. Since it's a neovim issue and not a lualine issue, i'll close this. It could be due to the fact that I am using the nightly build.

**Comment by shadmansaleh** [comment]
I'm using nightly too.

If you can reliably reproduce it and figure out what is needed to reproduce it . It'd still be useful . With that we can figure out what's causing it in the first place and fix it.

**Comment by aktersnurra** [comment]
I get this bug when setting `globalstatus = true`, `disabled_filetypes = { "NvimTree" }`, and running `:NvimTreeToggle`, on nightly.  Toggling the globalstatus off decreases the length of the fill of `^` symbol to the region of NvimTree.

**Comment by shadmansaleh** [comment]
@aktersnurra I can't reproduce with that either. Maybe try creating a isolated minimal init with https://github.com/nvim-lualine/lualine.nvim/blob/master/scripts/nvim_isolated_conf.sh

**Comment by marko-cerovac** [comment]
I didn't have time to try the minimal config, bit I did try to replace lualine with my custom statusline, and the problem still occurs. So it's definitely a neovim issue.

**Comment by shadmansaleh** [comment]
@marko-cerovac if you can reproduce it with just neovim and a simple custom statusline you can directly open an issue in neovim's repo with that and the devs will look into the issue.
