### ISSUE TITLE
Bug: Lualine dont update when visual mode is ON 

### ISSUE THREAD

**Issue by otavioschwanck** [nvim-lualine/lualine.nvim#766]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Add this function to lualine:
```lua
ins_right {
  function()
    local amount = vim.fn.strlen(vim.fn.GetVisualSelection())

    return ' ' .. amount
  end
}

```

### Expected behaviour

Update while move the cursor ou visual mode.

### Actual behaviour

The value only updates after exist visual mode

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

</details>

**Comment by shadmansaleh** [comment]
What is this `GetVisualSelection` ? Are you sure it's updating in in visual mode ? Because if I put a simple counter it shows lualine is updating in visual mode.

```lua
local n = 0
require'lualine'.setup{
  sections = {
    lualine_c = {function() n=n+1; return n; end}
  }
}
```

**Comment by otavioschwanck** [comment]
> What is this `GetVisualSelection` ? Are you sure it's updating in in visual mode ? Because if I put a simple counter it shows lualine is updating in visual mode.
> 
> ```lua
> local n = 0
> require'lualine'.setup{
>   sections = {
>     lualine_c = {function() n=n+1; return n; end}
>   }
> }
> ```

Here:
```
function! GetVisualSelection()
    let [line_start, column_start] = getpos("'<")[1:2]
    let [line_end, column_end] = getpos("'>")[1:2]
    let lines = getline(line_start, line_end)
    if len(lines) == 0
        return ''
    endif
    let lines[-1] = lines[-1][: column_end - (&selection == 'inclusive' ? 1 : 2)]
    let lines[0] = lines[0][column_start - 1:]
    return join(lines, "\n")
endfunction

```

**Comment by shadmansaleh** [comment]
`<` & `>` marks only get updated after leaving visual mode. That's why lualine is showing you the lenght after you leaving visual mode.
