### ISSUE TITLE
Bug: neovim dashboard hijacked

### ISSUE THREAD

**Issue by eeeXun** [nvim-lualine/lualine.nvim#768]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

After this https://github.com/nvim-lualine/lualine.nvim/commit/53aa3d82d9d9329880b4197f278fcb74051a6af5 update
### Expected behaviour
(when enter neovim)
![image](https://user-images.githubusercontent.com/58657914/181934771-1815ddae-e2c7-4ff3-9b2e-2804222dae2f.png)

### Actual behaviour
(when enter neovim)
![image](https://user-images.githubusercontent.com/58657914/181934792-74175b5d-a6d0-407a-9ecf-b498905271ff.png)

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

</details>

**Comment by shadmansaleh** [comment]
https://github.com/nvim-lualine/lualine.nvim/issues/259#issuecomment-1200083574
