### ISSUE TITLE
statusline for each window, always showing

### ISSUE THREAD

**Issue by otavioschwanck** [nvim-lualine/lualine.nvim#770]
Would be awesome to have this.  Sometimes i have 2 / 3 files and just forget the name of the other files.  I have to go to the file to see the lualine and see the name of the file.

**Comment by shadmansaleh** [comment]
That's the default behavior . Just turn off global status option.

**Comment by otavioschwanck** [comment]
> That's the default behavior . Just turn off global status option.
<img width="1229" alt="Captura de Tela 2022-07-31 às 15 06 26" src="https://user-images.githubusercontent.com/9551316/182030131-05a44f9b-efe6-4197-9a82-cd43bfcc6c19.png">

i already turned off, only the focused window has the bar

**Comment by shadmansaleh** [comment]
you have't configured statusline for inactive windows . configure it in inactive_sections table same as sections table
```lua
require'lualine'.setup({
  sections = { --config for active window
  },
  inactive_sections = { -- config for inactive window.
  }
})
if you want both to be same just set them to same table.

**Comment by otavioschwanck** [comment]
> you have't configured statusline for inactive windows . configure it in inactive_sections table same as sections table
> 
> ```lua
> require'lualine'.setup({
>   sections = { --config for active window
>   },
>   inactive_sections = { -- config for inactive window.
>   }
> })
> if you want both to be same just set them to same table.
> ```

worked, thanks!
