### ISSUE TITLE
base16 theme generate an error 

### ISSUE THREAD

**Issue by isingasimplesong** [nvim-lualine/lualine.nvim#771]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
use 'base16' as your lualine theme in lualine config : 

### Expected behaviour
To work fine !

### Actual behaviour
- it generate an error : "lualine : there are some issues with your config. Run :Lualinenotices for details"
- fallback to "auto" theme (nord in my case)
- :Lualinenotices doesn't give any details

### Minimal config to reproduce the issue

require('lualine').setup {
  options = {
    icons_enabled = true,
    theme = 'base16',
[...] 
}

**Comment by shadmansaleh** [comment]
Are you sure you're on latest commit of lualine branch??

**Comment by isingasimplesong** [comment]
i think so : 
```
commit 6d11f9f50817020cf634903a235628cabe0c56f8 (grafted, HEAD -> master, origin/master, or$
Author: Shadman <13149513+shadmansaleh@users.noreply.github.com>
Date:   Fri Jul 29 16:54:31 2022 +0600
```

**Comment by shadmansaleh** [comment]
Do you have [nvim-base16](https://github.com/RRethy/nvim-base16) installed ?

**Comment by shadmansaleh** [comment]
Update your lualine installation notice buffer being empty issue should be fixed with bd52d2d77ec122083ad33987107e010b3509a6be . And the notice should tell you what's wrong . If you still have issues with this let me know.

**Comment by isingasimplesong** [comment]
Yes, nvim-base16 is intalled. i'm probably missing something, but i can't find what.
here is the error i get : 
```
theme(base16): nvim-base16 is not loaded yet, you should update your configuration to load it before lualine so that the colors from your colorscheme can be used, fallback to "tomorrow-night" theme.
```

nvim-base16 is upper in my plugins list than lualine.
Also, when i try to purposely load the tomorrow-night, lualine can't find it

**Comment by shadmansaleh** [comment]
I think you didn't call nvim-base16s setup function before calling lualines setup funciton.

**Comment by isingasimplesong** [comment]
Am i calling it wrong ? : 

```
require('base16').setup()
require('lualine').setup {
  options = {
    icons_enabled = true,
    theme = 'auto',
```

**Comment by shadmansaleh** [comment]
I don't use base-16 colorschems myself . Maybe you need to provide some arguments in the setup function. Also make sure you've actually set the colorscheme with `:colorscheme` command before you call lualines setup

```lua 
vim.cmd('colorscheme base16-nord')
require('lualine').setup {
  options = {
    icons_enabled = true,
    theme = 'auto',
[...]
```

**Comment by LexSong** [comment]
Even with a minimal init.vim, the error message still shows up:
``` lua
-- Colorschemes
vim.cmd("colorscheme base16-material")
-- lualine.nvim
require("lualine").setup({
	options = {
		theme = "base16",
	},
})
```

**Comment by LexSong** [comment]
> Even with a minimal init.vim, the error message still shows up:
> 
> ```lua
> -- Colorschemes
> vim.cmd("colorscheme base16-material")
> -- lualine.nvim
> require("lualine").setup({
> 	options = {
> 		theme = "base16",
> 	},
> })
> ```

I found the correct way to solve this issue is to explicitly require base16-colorscheme with:
``` lua
require("base16-colorscheme") -- We need this line.
vim.cmd("colorscheme base16-material")
```
