### ISSUE TITLE
Proper contrast for nord theme "insert" and "visual" status items

### ISSUE THREAD

**Issue by isingasimplesong** [nvim-lualine/lualine.nvim#772]
Status lines theme should provide proper visual contrast between different mode, for readability 

lualine nord theme provide very little contrast between modes, except replace mode. 

i'd suggest to use Aurora's colors from the official nord theme to improve contrast, for example using #bf616a for insert mode and #a3be8c for visual mode would provide good contrast while maintaining theme coherence.

**Comment by shadmansaleh** [comment]
The colors are mainly upto colorschemes.  Most the themes in this repo were added by porting already existing lightline or airliine themes. And they are provided as provided as fallback the colorscheme itself doesn't provide a lualine theme. For example if you're using [nord.nvim](https://github.com/shaunsingh/nord.nvim) lualine will be using theme from the colorschemes repo not here. 

Also themes are just lua tables if you don't like some color changing them in user config is really easy [see here](https://github.com/nvim-lualine/lualine.nvim#customizing-themes).

TBH I'm just not interested in stuff like I like this color better someone else like that color better. So the idea is if you don't like a color just customize it to what you like . Hope you can understand.

**Comment by isingasimplesong** [comment]
of course, thanks for the hints
