### ISSUE TITLE
Bug: Statusline flickering when switching buffers

### ISSUE THREAD

**Issue by sgoudham** [nvim-lualine/lualine.nvim#774]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### Expected behaviour
The status line does not flicker when moving to a different buffer, no matter if it's the first time loading the buffer or going back to it

### Actual behaviour
The status line flickers when moving to a new buffer. The behaviour is less noticeable in buffers that are already open but it does happen when opening new files.

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>
While the problem doesn't seem nearly as prolonged, it still flickers when switching buffers from the command with the usage of `:e` to switch buffers. I hope you can see the flickering with this minimal configuration.

`init.lua`
```lua
local fn = vim.fn

-- Automatically install Packer
local install_path = fn.stdpath "data" .. "/site/pack/packer/start/packer.nvim"
if fn.empty(fn.glob(install_path)) > 0 then
    PACKER_BOOTSTRAP = fn.system {
        "git",
        "clone",
        "--depth",
        "1",
        "https://github.com/wbthomason/packer.nvim",
        install_path,
    }
    print "Installing Packer. Close and reopen Neovim..."
    vim.cmd([[packadd packer.nvim]])
end

-- Use a protected call so we don't error out on first use
local status_ok, packer = pcall(require, "packer")
if not status_ok then
    return
end

packer.startup(function(use)
    -- Packer can manage itself
    use 'wbthomason/packer.nvim'

    use { "nvim-lualine/lualine.nvim" }

    -- Automatically set up your configuration after cloning packer.nvim
    -- Put this at the end after all plugins
    if PACKER_BOOTSTRAP then
        require("packer").sync()
    end
end)

require("lualine").setup()
vim.opt.laststatus = 3
```

</details>

### Additional Information

**Neovim**: 0.7.2
**OS**: Windows 11

Gif of the problem (with other plugins installed, it's more noticeable. I raised this issue here as I could still see the flickering without other plugins. You can see on the first load of new files, the statusline noticeably takes longer to load.
![statusline-help](https://user-images.githubusercontent.com/58985301/182262994-e7f3a826-e925-40a5-9a98-fa4f931cff38.gif)

I understand if this problem may be caused by lualine in combination with another plugin. If so, apologies for raising this issue, but I thought to raise it here first. Thanks

**Comment by shadmansaleh** [comment]
I can't reproduce it.

See if this patch helps
```diff
diff --git a/lua/lualine.lua b/lua/lualine.lua
index f87dcf6..b1c7a09 100644
--- a/lua/lualine.lua
+++ b/lua/lualine.lua
@@ -335,7 +335,7 @@ local function refresh(opts)
     opts.trigger = 'autocmd_redired'
     vim.defer_fn(function()
       M.refresh(opts)
-    end, 50)
+    end, 0)
     return
   end
 
```

**Comment by sgoudham** [comment]
I can confirm that changing refresh value to `0` eliminates the flickering issue. However, after doing this. Suddenly, the statusline now disappears whenever there is a floating buffer (telescope, floaterm etc.). I'm not sure if that behaviour can be expected from changing this value?

**Comment by shadmansaleh** [comment]
@sgoudham check if https://github.com/nvim-lualine/lualine.nvim/commit/d2a727da9fe391f7839a81d39a6361d90146da1e fixed it.

**Comment by sgoudham** [comment]
@shadmansaleh That fixed it for me, thanks so much!
