### ISSUE TITLE
Bug: Tabline options disappear

### ISSUE THREAD

**Issue by szoradigeza** [nvim-lualine/lualine.nvim#783]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
- type something in the tabline
- use tab

### Expected behaviour
- tabline options should be visible

### Actual behaviour

https://user-images.githubusercontent.com/35313105/183126164-321c12f6-6f6b-40b4-85e2-c4dff38e5d54.mp4

### Minimal config to reproduce the issue

https://github.com/szoradigeza/nvim-config

Maybe this happens because of some plugin.
If I remove the lualine it works totally fine. 

Do you have any idea?

**Comment by shadmansaleh** [comment]
If you can't follow the issue template and think your entire neovim config is a minimal config and I should go through your entire config to figure out what issue you're having I have nothing to say. Still I'll give you a hint  . For low effort reports you'll get low effort replies.
