### ISSUE TITLE
Bug: nvim-tree pick-window not shown

### ISSUE THREAD

**Issue by xavier-balesi** [nvim-lualine/lualine.nvim#784]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

with the latests lualine (`b1042d3`) and nvim-tree (`1685484`) versions: 
- open two files in vsplit
- select a file from nvim-tree and press enter

### Expected behaviour
- the first window has a 'A' in bottom line (overriding lualine)
- the second window has a 'B' in bottom line
- 'Pick-Window:' is displayed in status line
![image](https://user-images.githubusercontent.com/68602306/183162594-b297c8f7-02e3-4a1d-aa46-b9163d5ff171.png)

### Actual behaviour
- 'Pick-Window:' is displayed in status line
- a little blue rectangle is show between the the two lines
![image](https://user-images.githubusercontent.com/68602306/183161736-3101bbd0-d1ac-4919-b49f-cd2be4d5de6f.png)

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

```
call plug#begin("/home/xbalesi/tmp/mini_nvim_conf/.local/share/nvim/plugged")
Plug 'nvim-lualine/lualine.nvim'
Plug  'kyazdani42/nvim-tree.lua'

call plug#end()

lua << END
require'lualine'.setup {}
require'nvim-tree'.setup {}
END
```

</details>

### Aditional information

With one previous commit of lualine, it works fine : `d2a727d`
It seems that the last commit make the break : `b1042d3`

**Comment by shadmansaleh** [comment]
fixed in f40db9a2240d24f7e042bfcb5b7f41a1abded973
