### ISSUE TITLE
Bug: Gap in highlight after xml web-devicon

### ISSUE THREAD

**Issue by ghillb** [nvim-lualine/lualine.nvim#790]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

- Bare neovim with only lualine installed in wsl (windows terminal)
- Open `.xml` file

### Expected behaviour
no gap in status line:
![image](https://user-images.githubusercontent.com/35503959/183309329-ac980768-ad6f-4373-b02d-7ec7b6bf3be7.png)

### Actual behaviour
gap in status line:
![image](https://user-images.githubusercontent.com/35503959/183309150-06dc0b6b-f629-41df-bb6b-e52e94613cc9.png)
The xml icon seems to be two characters wide, which could play a role in causing this.

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

</details>

**Comment by shadmansaleh** [comment]
Can't reproduce .
![Screenshot](https://user-images.githubusercontent.com/13149513/183328155-7a3fb62b-7087-4478-b1ac-7405e68394b1.png)

I think it's an issue with the font or terminal you're using . I'm using FiraCode and it's rendering fine . Try a different font.

**Comment by ghillb** [comment]
This made me curios (I'm also using FiraCode), so I tested with alacritty (windows) and kitty (linux) and it is only happening with windows-terminal. So, it's not a lualine issue.
