### ISSUE TITLE
Bug: only showing command mode right after entering command

### ISSUE THREAD

**Issue by ces42** [nvim-lualine/lualine.nvim#791]
### Self Checks

- [ X ] I'm using the latest lualine.
- [ X ] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
Enter command mode `:`.

### Expected behaviour
Mode indicator (bottom left in default config) changes to "COMMAND"

### Actual behaviour
Mode indicator stays in "NORMAL". Sometimes I can see "COMMAND" flash for a split second after hitting enter.

### Minimal config to reproduce the issue

<details>
minimal `.vimrc`

```
call plug#begin()
    Plug 'nvim-lualine/lualine.nvim'
call plug#end()
require'lualine'.setup()
```

</details>

### Aditional information
The bug does not happen with airline
`:version` gives
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
```
lualine version: latest master ([e22c7b3](https://github.com/nvim-lualine/lualine.nvim/commit/e22c7b3c9b5916b56654f8da91f4a139f3b5988f))

**Comment by shadmansaleh** [comment]
https://github.com/neovim/neovim/issues/19472

**Comment by anthony-S93** [comment]
Has the commit been merged into master? I'm still experiencing similar issues. 

![Screenshot_2022-09-02_10-27-46](https://user-images.githubusercontent.com/69449791/188045672-8093be1d-bc8e-40d8-aab0-7b664d8ee6a9.jpg)

Lualine's status didn't update while I'm typing the command. However, when I resized my terminal window, the status immediately updated: 

![Screenshot_2022-09-02_10-30-08](https://user-images.githubusercontent.com/69449791/188045905-b5e2ddd2-3dba-4db4-aaa9-215de55088fb.jpg)

**Comment by Alex-vZyl** [comment]
Also experiencing these issues.

**Comment by tp86** [comment]
I also observed that mode changes for searches, but after you enter first character to search, e.g. `/x`, it does not update on just `/`.

**Comment by jones-sam** [comment]
I also experienced the same issue, however in the nightly build it seems to work as mentioned by @tp86.

I'm experiencing another related issue, when adding new lines in insert mode, the mode in lualine will flicker to command mode and back to insert. It isn't consistent, sometimes it will flicker other times it won't.

https://asciinema.org/a/524485
(this was recorded with the default configuration on the newest build)

anyone else experiencing this?

**Comment by Alex-vZyl** [comment]
> I also experienced the same issue, however in the nightly build it seems to work as mentioned by @tp86.
> 
> I'm experiencing another related issue, when adding new lines in insert mode, the mode in lualine will flicker to command mode and back to insert. It isn't consistent, sometimes it will flicker other times it won't.
> 
> https://asciinema.org/a/524485 (this was recorded with the default configuration on the newest build)
> 
> anyone else experiencing this?

This issue is related to cmdline not updating properly.  The one you are showing seems like something else, I suggest you open a seperate issue.  You will most likely get better support.

**Comment by jones-sam** [comment]
> > I also experienced the same issue, however in the nightly build it seems to work as mentioned by @tp86.
> > I'm experiencing another related issue, when adding new lines in insert mode, the mode in lualine will flicker to command mode and back to insert. It isn't consistent, sometimes it will flicker other times it won't.
> > [asciinema.org/a/524485](https://asciinema.org/a/524485) (this was recorded with the default configuration on the newest build)
> > anyone else experiencing this?
> 
> This issue is related to cmdline not updating when it has to ([neovim/neovim#19472](https://github.com/neovim/neovim/issues/19472)). The one you are showing seems like something else, I suggest you open a seperate issue. You will most likely get better support.

Created a new issue https://github.com/nvim-lualine/lualine.nvim/issues/852

**Comment by anthony-S93** [comment]
Just a quick update here. Updating neovim to version 0.8.0-3 fixed this issue entirely. Thank you, dev team.
