### ISSUE TITLE
Bug: builtin components update slowly

### ISSUE THREAD

**Issue by ces42** [nvim-lualine/lualine.nvim#792]
### Self Checks

- [ x ] I'm using the latest lualine.
- [ x ] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
Open a file with a couple hundred lines and hold `j`.

### Expected behaviour
Line numbers, progress in lualine update instantly.

### Actual behaviour
Line numbers only update (exactly) once per second.

However, if I write a progress component myself it will update instantly (as far as I can tell).
I guess this might be supposed to be a feature? Is there any way to turn it off, or to increase the refresh rate?

### Minimal config to reproduce the issue

<details>
minimal `.vimrc`

```
call plug#begin()
    Plug 'nvim-lualine/lualine.nvim'
call plug#end()
require'lualine'.setup()
```

</details>

### Aditional information
The bug does not happen with airline
`:version` gives
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
```
lualine version: latest master ([e22c7b3](https://github.com/nvim-lualine/lualine.nvim/commit/e22c7b3c9b5916b56654f8da91f4a139f3b5988f))

**Comment by harrygallagher4** [comment]
This was introduced by 6d11f9f50817020cf634903a235628cabe0c56f8 (#767)

If you specify 788805771c1ca7fe2c6652c38523cf208908934c in your packer config you can use the older version until this is sorted out.

```lua
{
  'nvim-lualine/lualine.nvim',
  commit = '788805771c1ca7fe2c6652c38523cf208908934c',
  lock = true
}
```

**Comment by shadmansaleh** [comment]
https://github.com/nvim-lualine/lualine.nvim/wiki/FAQ#my-statuslinetablinewinbar-updates-infrequently
