### ISSUE TITLE
Bug: Winbar

### ISSUE THREAD

**Issue by dstadelm** [nvim-lualine/lualine.nvim#802]
Hi

The advantage of winbar, IMHO, is when using globalstatus set to true. Then it would be nice, if every windo shows the winbar not only the focused one, otherwise I personally do not see the advantage of winbar.

**Comment by dstadelm** [comment]
Is there a way to define different separators for the winbar?

**Comment by shadmansaleh** [comment]
>  it would be nice, if every windo shows the winbar not only the focused one

There's `inactive_winbar` section that configures winbar on unfocused windows you can set it to same as `winbar` section.

> Is there a way to define different separators for the winbar?

You can define it on component basis with `separator` option. If a component specific value isn't given global option value is used.

**Comment by dstadelm** [comment]
Thank you! Awesome response time for what was, as it turns out, a stupid question.
