### ISSUE TITLE
Bug: LualineRenameTab has stopped working?

### ISSUE THREAD

**Issue by fakeharxy** [nvim-lualine/lualine.nvim#803]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

I think just install the Plugin and try to use :LualineRenameTab
### Expected behaviour
Up until this morning when I did a PlugUpdate, this command would rename my tab
### Actual behaviour
`E492: Not an editor command: LualineRenameTab main`

**Comment by fakeharxy** [comment]
nope, this is a me problem. Big apologies.

**Comment by beetol** [comment]
Can you please explain how you fixed this? I'm getting the "not an editor command" error when I type `:LualineRenameTab` as well. Plugin was installed under LunarVim config.

**Comment by KiLLeRRaT** [comment]
Did you guys ever get to the bottom of this?
