### ISSUE TITLE
Bug: Setting custom background color on component removes separators

### ISSUE THREAD

**Issue by zappolowski** [nvim-lualine/lualine.nvim#805]
### Self Checks

- [x] I'm using the latest lualine (c0510dd)
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Trying to set the `bg` color of a component removes separators before and after that component.

### Expected behaviour

The separator before and after the component is shown.

### Actual behaviour

Separators are missing.

### Minimal config to reproduce the issue

```
call plug#begin("/home/zappolowski/lualine-bug/.local/share/nvim/plugged")
Plug 'nvim-lualine/lualine.nvim'
call plug#end()

lua << END
require'lualine'.setup {
    sections = {
        lualine_a = {
            "mode",
            { "branch", color = { bg = "red" }, separator = "&" },
            "filename",
        },
    },
}
END
```

### Aditional information

When switching out `bg` with `fg` the separators appear as expected.

Using `bg = "red"`:
![lualine-bug_no_separators](https://user-images.githubusercontent.com/23430806/185389329-adc46e36-7f43-4eea-9090-f1375526dc2e.png)

Using `fg = "red"`:
![lualine-bug_fg_separators](https://user-images.githubusercontent.com/23430806/185389324-0b633ec2-7484-47d3-8e9c-f47019729f7a.png)

**Comment by shadmansaleh** [comment]
This is intentional behavior. The background color separates the components. And regular separators look really weird no matter whether you draw them in front or behind the background change. If you want you can have section separator like separators before or after the component with changed background with `separator` option.

**Comment by zappolowski** [comment]
Thanks for your reply.

Do I get this right, that by passing `color` I have to use `separator` as a table for section like separators? Doesn't this imply that I disable component like separators this way (e.g. in my configuration, `separator = "&"` is ignored, when setting a `bg` color).

**Comment by shadmansaleh** [comment]
> I have to use separator as a table for section like separators

it's not that you have to you can if you want special separation

> Doesn't this imply that I disable component like separators this way (e.g. in my configuration, separator = "&" is ignored, when setting a bg color

Yeah they are ignored .

The transitional/section separator chars are different then regular & as they have a solid portion that can be drawn in fg and empty part in bg . That lets us draw them as boundary between to parts with different bg color, it can't be done with '&' that'd just look weird :]

**Comment by zappolowski** [comment]
Thanks for your input.

I was able to find a workaround for my problem.
