### ISSUE TITLE
Weird behavior when using Goyo

### ISSUE THREAD

**Issue by indeedwatson** [nvim-lualine/lualine.nvim#806]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Simply install lualine, goyo, and enable Goyo. 

### What it should look like
![2022-08-18-07](https://user-images.githubusercontent.com/10749504/185533074-9e978135-ce41-4474-ace1-897636986395.png)

### What it look like
![2022-08-18-22](https://user-images.githubusercontent.com/10749504/185532551-2bdd45fa-033e-4592-aafb-54b9d23bcc11.png)

**Comment by shadmansaleh** [comment]
It's a goyo bug not a lualine one . We provide [api](https://github.com/nvim-lualine/lualine.nvim#disabling-lualine) to hide lualine goyo can use that . You can open an issue there.
