### ISSUE TITLE
Feat: LualineBuffersDelete command

### ISSUE THREAD

**Issue by marcelom97** [nvim-lualine/lualine.nvim#811]
### Requested feature
As lualine has the `LualineBuffersJump` command, I find it very handy to also have a `LualineBuffersDelete` command.

This command will be very similar to `LualineBuffersJump`.

- Check if is the last requested buffer
- Check if buffer requested is out of index
- Call the `bdelete` with the buffer number

### Motivation
I think it will be very easy to map this command and delete buffers with the same easy way as jumping between them.

**Comment by shadmansaleh** [comment]
Feels out of scope for lualine. It's a statusline plugin not a buffer management plugin.

**Comment by marcelom97** [comment]
I agree that it's a statusline, but there is already a small functionality about buffers.

What about to add something more in order to be more complete?

I think that the buffer deletion functionality would fit perfectly.

I also want to work on implementing this, but first I want an approval about the feature!

**Comment by shadmansaleh** [comment]
Can you already do this by using [bufpos2nr map](https://github.com/nvim-lualine/lualine.nvim/blob/3cf45404d4ab5e3b5da283877f57b676cb78d41d/lua/lualine/components/buffers/init.lua#L227) ? It's exposed to the user.

**Comment by marcelom97** [comment]
Yes you can

Actually I have made the changes on a local branch.

Function
```lua
function M.buffer_delete(buf_pos, bang)
  if buf_pos == '$' then
    buf_pos = #M.bufpos2nr
  else
    buf_pos = tonumber(buf_pos)
  end
  if buf_pos < 1 or buf_pos > #M.bufpos2nr then
    if bang ~= '!' then
      error('Error: Unable to delete buffer position out of range')
    else
      return
    end
  end
  vim.cmd(string.format('%s %d', "bd", M.bufpos2nr[buf_pos]))
end
```

Command
```lua
command! -nargs=1 -bang LualineBuffersDelete call v:lua.require'lualine.components.buffers'.buffer_delete(<f-args>, "<bang>")
```


If you know a better way of doing this, would be happy to hear that!

**Comment by shadmansaleh** [comment]
> Actually I have made the changes on a local branch.

That's not what I meant this command can be created by user even if we don't provide it . Adding this to your config should work just fine
```lua
vim.api.nvim_create_user_command('LualineBuffersDelete', function (args)
  local buffers = require'lualine.components.buffers'
  local buf_pos = args.fargs[1] == '$' and #buffers.bufpos2nr or tonumber(args.fargs[1])
  if buf_pos >= 1 and buf_pos <= #buffers.bufpos2nr then
    vim.api.nvim_buf_delete(buffers.bufpos2nr[buf_pos], {force = true})
  elseif not args.bang then
    error('Error: Unable to delete buffer position out of range')
  end
end, {desc='Delete buffer based on lualine-buffers index', force = true, nargs=1, bang=true})
```
