### ISSUE TITLE
Feat: ADD Lspsaga's LSoutline Support

### ISSUE THREAD

**Issue by NEX-S** [nvim-lualine/lualine.nvim#817]
Feat: ADD Lspsaga's LSoutline Support like support show Aerial Symbol in lualine

**Comment by shadmansaleh** [comment]
Lualine can show anything as lomg as you can return it from a function . LspSaga has [instructions](https://github.com/glepnir/lspsaga.nvim#show-symbols-in-winbarnvim-08-or-in-statusline) for using it in statusline follow them and make a [custom component](https://github.com/nvim-lualine/lualine.nvim#lua-functions-as-lualine-component) for lualine.
