### ISSUE TITLE
Bug: E539: Illegal character in filename

### ISSUE THREAD

**Issue by liuerfire** [nvim-lualine/lualine.nvim#820]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

set `path` to any value (1, 2 or 3) except the default 0 in filename section.

```
require('lualine').setup {
  sections = {
    lualine_c = {
      { 'filename', path = 3, },
    },
  },
}
```
Install https://github.com/mfussenegger/nvim-jdtls and jump to the definition of a class. 

### Expected behaviour
no errors

### Actual behaviour

![image](https://user-images.githubusercontent.com/745867/187383416-b9d95fa1-ea6f-49ed-b82f-93b5921c540d.png)

### Aditional information

The full path of this file is:

![image](https://user-images.githubusercontent.com/745867/187383259-0fb3c477-0ab6-46f6-b214-a875f1f326ed.png)

**Comment by liuerfire** [comment]
Maybe it's jdtls's bug, which shouldn't escape '/' to %5C?

**Comment by zeitchef** [comment]
I'm getting the exact same error

**Comment by ramanenka** [comment]
I've got the same error and here is how I've solved it:
```lua
lualine_c = {
  function()
    local fn = vim.fn.expand('%:~:.')
    if vim.startswith(fn, "jdt://") then
      fn = string.sub(fn, 0, string.find(fn, "?") - 1)
    end
    if fn == '' then
      fn = '[No Name]'
    end
    if vim.bo.modified then
      fn = fn .. ' [+]'
    end
    if vim.bo.modifiable == false or vim.bo.readonly == true then
      fn = fn .. ' [-]'
    end
    local tfn = vim.fn.expand('%')
    if tfn ~= '' and vim.bo.buftype == '' and vim.fn.filereadable(tfn) == 0 then
      fn = fn .. ' [New]'
    end
    return fn
  end
},
```
For some reason writing the same logic in an `fmt` function didn't prevent the error from happening.

**Comment by kmoschcau** [comment]
@ramanenka I figured out why `fmt` isn't working. What you get in that function is probably already shortened and looks like this:
`j//c/j/j/N/%/h/k/.g/c/m/f/j/j/2/8/j/g/m/=/o/%%5C/WEB-INF%%5C/lib=/%%3Cjavax.persistence(NoResultException.class`
So your prefix check doesn't even work in there.

**Comment by 1Jo1** [comment]
> I've got the same error and here is how I've solved it:
> 
> ```lua
> lualine_c = {
>   function()
>     local fn = vim.fn.expand('%:~:.')
>     if vim.startswith(fn, "jdt://") then
>       fn = string.sub(fn, 0, string.find(fn, "?") - 1)
>     end
>     if fn == '' then
>       fn = '[No Name]'
>     end
>     if vim.bo.modified then
>       fn = fn .. ' [+]'
>     end
>     if vim.bo.modifiable == false or vim.bo.readonly == true then
>       fn = fn .. ' [-]'
>     end
>     local tfn = vim.fn.expand('%')
>     if tfn ~= '' and vim.bo.buftype == '' and vim.fn.filereadable(tfn) == 0 then
>       fn = fn .. ' [New]'
>     end
>     return fn
>   end
> },
> ```
> 
> For some reason writing the same logic in an `fmt` function didn't prevent the error from happening.

I just had the same error, thanks for the this workaround fix
probably it would be better to fix this issue in lualine I guess long term

**Comment by massix** [comment]
> I've got the same error and here is how I've solved it:
> 
> [snip]
> 
> For some reason writing the same logic in an `fmt` function didn't prevent the error from happening.

Thanks to your input, I was able to fix it using the `fmt` parameter, without altering the already existing configuration nor the default behavior of lualine.

```lua
            {
              "filename",
              path = 1,
              symbols = { modified = "  ", readonly = "  ", unnamed = "  " },
              --- @param str string
              fmt = function(str)
                --- @type string
                local fn = vim.fn.expand("%:~:.")

                if vim.startswith(fn, "jdt://") then
                  return fn:gsub("?.*$", "")
                end
                return str
              end,
            },
```
