### ISSUE TITLE
lualine makes neovim's default start screen disappeared

### ISSUE THREAD

**Issue by hronro** [nvim-lualine/lualine.nvim#825]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

1. install lualine with packer.nvim
2. use default lualine config (`require'lualine'.setup {}`)
3. type `nvim` to start a neovim instance

### Expected behaviour
Should see neovim's default start screen like this:

```

                    NVIM v0.7.2

    Nvim is open source and freely distributable
              https://neovim.io/#chat

   type  :help nvim<Enter>       if you are new!
   type  :checkhealth<Enter>     to optimize Nvim
   type  :q<Enter>               to exit
   type  :help<Enter>            for help

           Become a registered Vim user!
   type  :help register<Enter>   for information

```

### Actual behaviour
Didn't see the start screen

### Minimal config to reproduce the issue

```lua
-- init.lua

require'packer'.startup(function(use)
  use 'wbthomason/packer.nvim'
  use {
    'nvim-lualine/lualine.nvim',
    requires = { 'kyazdani42/nvim-web-devicons', opt = true },
    config = function () require'lualine'.setup {} end,
  }
end)
```

**Comment by equal-l2** [comment]
I encountered this problem too.

With empty `sections` and `inactive_sections` this doesn't occur.
(I guess this effectively disable lualine, as the vanilla statusline appears with the config)
```
require "lualine".setup {
  sections = {},
  inactive_sections = {},
}
```

**Comment by equal-l2** [comment]
After some digging, I believe the problem is caused by `vim.api.nvim_win_set_option` because of https://github.com/neovim/neovim/issues/3416.

**Comment by equal-l2** [comment]
After digging I come to think this is an inevitable behaviour.

Setting `statusline` causes screen redraw and the intro cannot survive the redraw.
As lualine must set `statusline` to work, this cannot be evitable.

**Comment by hronro** [comment]
@equal-l2 That's very interesting. Several months ago, lualine worked pretty well with the intro(start screen) for me. Perhaps it's the updates of Neovim itself that caused the issue?

**Comment by equal-l2** [comment]
Or lualine changed how to work maybe?
I must dig deeper...

**Comment by hronro** [comment]
Just tried the latest lualine with nvim(0.5.1), and the intro screen still disappeared.

**Comment by equal-l2** [comment]
By bisecting, I found the problem occurs after 53aa3d.

**Comment by shadmansaleh** [comment]
duplicate #773 .

It's due to fact that setting statusline or tabline in scheduled functions causes neovim intro to disappear. Since lualine now updates on timer it's not possible for us to avoid scheduled functions. I had talked to neovim devs and have been told it's an issue in neovim. So unless it gets fixed in upstream this can't be resolved. If you want intro you can try out dashboard plugins they would be persistent. The default intro on neovim doesn't provide much so it's not really high priority.

**Comment by hronro** [comment]
@shadmansaleh Thx. I'll close it since it's duplicated.
