### ISSUE TITLE
Bug: lualine overrides global scroll option

### ISSUE THREAD

**Issue by rensftw** [nvim-lualine/lualine.nvim#830]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in existing issues or prs.

### How to reproduce the problem
1. Set a custom `scroll` value like `vim.o.scroll = 10`
2. Load Neovim with minimal lualine
3. Check the value of `scroll` like `:set scroll`; I expect it to be `10` but in reality it's the half of the window height.

### Expected behaviour
I can set a custom value to the global `scroll` option.

### Actual behaviour
Lualine resets the global `scroll` back to the default value (half the window height)

### Minimal config to reproduce the issue
```lua
-- init.lua
vim.o.scroll = 10

require'packer'.startup(function(use)
  use 'wbthomason/packer.nvim'
  use {
    'nvim-lualine/lualine.nvim',
    requires = { 'kyazdani42/nvim-web-devicons', opt = true },
    config = function () require'lualine'.setup {} end,
  }
end)
```
### Aditional information
```
INFO: Platform: macos
INFO: Nvim Version: NVIM v0.7.2
INFO: Node version: v18.8.0
```

**Comment by shadmansaleh** [comment]
It's not lualine issue rather neovim behavior. This is what docs says `:h 'scroll'`

> 	Number of lines to scroll with CTRL-U and CTRL-D commands.  Will be
	set to half the number of lines in the window when the window size
	changes.  This may happen when enabling the |status-line| or
	'tabline' option after setting the 'scroll' option.

Now you can't expect a statusline plugin not to change statusline right ?
