### ISSUE TITLE
cmdheight=0 will cause error in nvim-nightly

### ISSUE THREAD

**Issue by NEX-S** [nvim-lualine/lualine.nvim#843]
https://github.com/neovim/neovim/issues/20247#issue-1377698342

**Comment by notwidow** [comment]
> just get a reply from the neovim's developer, now if we are using the command mode in cmdheight=0, the status line should disappear, when we exit the command mode, the statusline should showup again, so maybe lualine should add a feature implements that?

cmdheight=0 ??/
 how you see the commands??????

**Comment by notwidow** [comment]
> just get a reply from the neovim's developer, now if we are using the command mode in cmdheight=0, the status line should disappear, when we exit the command mode, the statusline should showup again, so maybe lualine should add a feature implements that?

this is not a bug.. that label is wrong......it has nothing to do with lualine....

**Comment by notwidow** [comment]
> the command line will replace the statusline temporarily so we can see the command :D

okay Pentester!!!!!

**Comment by shadmansaleh** [comment]
This is not related to lualine. Statusline being hidden with cmdheight 0 is how neovim ui works. 

You can probably get your intended behavior by switching between cmdheight 0 & 1 with events CmdLineEnter & CmdLineLeave or by mapping `:` & `esc` key to make the switch . But that's out off scope of lualine.
