### ISSUE TITLE
Bug: terminal applications called with `on_click` don't start in insert mode

### ISSUE THREAD

**Issue by wimstefan** [nvim-lualine/lualine.nvim#848]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

First of all I'd like to apologize that I did neglect the template for reporting a bug. But I felt that my problem does not fit into the procedure used with the template so I'll try plain words to explain ... ;)

I'm playing around with the `on_click` feature by calling `lazygit` in the git diff part of lualine:
```lua
lualine_y = {
  {
    'diff',
    source = diff_source,
    diff_color = { added = 'GitSignsAdd', modified = 'GitSignsChange', removed = 'GitSignsDelete' },
    symbols = { added = '落 ', modified = '  ', removed = '  ' },
    on_click = function()
      vim.cmd('Lazygit')
      vim.cmd('startinsert!')
    end
  },
  {
    'branch',
    icon = 'שׂ '
  }
},
```
As you can see I'm trying already to call `startinsert` in the function since I want the terminal that pops up with lazygit (via [fm.nvim](https://github.com/is0n/fm-nvim)) to be in insert mode. That doesn't work the simple way I try to achieve that and I didn't succeed to find another solution to start the terminal in insert mode.

I've tried also to configure [toggleterm.nvim](https://github.com/akinsho/toggleterm.nvim) as described in the section "Custom terminal usage" of the README but the result was pretty much the same.

I hope I can get some ideas how to solve that (small) issue.

**Comment by lvimuser** [comment]
Try `vim.schedule`
```lua
on_click = function()
  vim.cmd('Lazygit')
  vim.schedule(vim.cmd.startinsert)
end
 ```
 or `vim.schedule(function() vim.cmd('startinsert') end)`

**Comment by wimstefan** [comment]
Thank you so much!
It certainly was more a user issue than a lualine issue but you helped me enormously to tackle my little problem the right way.
So for the `Lazygit` call I use `vim.schedule` and for another `Vifm` call I'm using `vim.defer_fn` in combination with `startinsert` and all is good :)
Thanks again!
