### ISSUE TITLE
Progress component changes size while scrolling

### ISSUE THREAD

**Issue by miguelbarao** [nvim-lualine/lualine.nvim#849]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Default settings

### Expected behaviour

The progress component should have a fixed size

### Actual behaviour

Progress is 3 chars wide for Top, Bot, 10% up to 99%, except between 1% and 9%.
This makes the component change size, which affect the position of other components on the lualine.
This "jumping" is distracting when scrolling.   

### Aditional information

This can be fixed by changing `lua/lualine/components/progress.lua` and change line 11 to something like 

```lua
    return string.format('%2d%%%%', math.floor(cur / total * 100))
```

**Comment by rs-loves-bugs** [comment]
I can't believe more people are not annoyed by this, thanks for providing a fix.
