### ISSUE TITLE
Feat: How can I remove `^^^` signs of current window

### ISSUE THREAD

**Issue by kostafey** [nvim-lualine/lualine.nvim#850]
### Requested feature

How can I remove `^^^` signs of current window?

![lualine](https://user-images.githubusercontent.com/1282079/192158699-e65a06f4-40c2-4dcf-8887-ec4ef296745a.png)

**Comment by shadmansaleh** [comment]
It's an upstream issue. Follow https://github.com/neovim/neovim/issues/19803.

**Comment by kostafey** [comment]
@shadmansaleh, thank you.
