### ISSUE TITLE
Bug: `cmdheight = 0` in 0.8 results in weird glitch

### ISSUE THREAD

**Issue by chrisgrieser** [nvim-lualine/lualine.nvim#853]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
- use neovim 0.8
- set `cmdheight = 0`

### Expected behaviour
The lualine should be displayed persistently.

### Actual behaviour
it glitches, with every keystroke the line appears briefly, but with then disappears again. might be related to `showcmd`'s display duration? However, toggling `showcmd` does not make a difference, though.

https://user-images.githubusercontent.com/73286100/193426286-86172a7b-9de0-4b95-a88d-0f93328a106e.mov

### Minimal config to reproduce the issue
```lua
vim.opt.cmdheight = 0
vim.opt.laststatus = 2
vim.opt.showcmd = true -- setting to "false" does not make a difference
```
### Additional Information
A similar issue has been reported in #843, but if I understand it correctly, the issue there was only that the lualine disappears in Command Mode (which I am totally fine with).

**Comment by fitrh** [comment]
Maybe related to https://github.com/neovim/neovim/pull/20582

**Comment by chrisgrieser** [comment]
for whatever reason, cmdheight=0 now runs without any issue. weird.
