### ISSUE TITLE
Bug: lualine's mode section does not show "COMMAND" mode

### ISSUE THREAD

**Issue by rodolfoksveiga** [nvim-lualine/lualine.nvim#854]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in existing issues or PRs.

My NVIM is at version v0.7.2.

### How to reproduce the problem

In a configured environment with lualine, open a new buffer, leave VIM's normal mode, and get into VIM's command mode pressing colon.

### Expected behaviour

When entering in VIM's command mode, it's expected that "COMMAND" shows in the first lualine section (mode section).

### Actual behaviour

When entering in VIM's command mode, nothing changes in the first lualine section (mode section), i.e. "NORMAL" still shows in this section, as VIM was still in normal mode.

### Minimal config to reproduce the issue

Just fresh install lualine and activate it.

In ~/.config/nvim/init.lua:

```lua
local use = require('packer').use

require('packer').startup(function()
    use 'wbthomason/packer.nvim'
    use 'nvim-lualine/lualine.nvim'
end)

require('lualine').setup({
    sections = {
        lualine_a = { 'mode' },
    }
})
```

**Comment by mnipritom** [comment]
hey i'm facing the same issue, how did you fix it?

**Comment by rodolfoksveiga** [comment]
I just updated `lualine` and the bug vanished somehow...
