### ISSUE TITLE
Bug: Bubbles theme rendering with square edges 

### ISSUE THREAD

**Issue by Ttibsi** [nvim-lualine/lualine.nvim#867]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

This has been tested in both Alacritty with DroidSansMono Nerd font and terminal.app with Hack Nerd font and MesloLGM Nerd font - the screenshot is of terminal.app and Hack Nerd, which is the least egregious of the lot, but they're all rendering with a square bar behind the rounded corners. 
<img width="512" alt="image" src="https://user-images.githubusercontent.com/60970073/195279400-303c6621-b7f4-4c08-a561-6f9fdb5ca4e7.png">

### Minimal config to reproduce the issue
```lua
	require("lualine").setup({
		options = {
			theme = bubbles_theme,
			component_separators = "|",
			section_separators = { left = "", right = "" },
		},
		sections = {
			lualine_a = {
				{ "mode", separator = { left = "" }, right_padding = 2 },
			},
			lualine_b = { "filename", "branch" },
			lualine_c = { "fileformat" },
			lualine_x = {},
			lualine_y = { "filetype", "progress" },
			lualine_z = {
				{
					"location",
					separator = { right = "" },
					left_padding = 2,
				},
			},
		},
		inactive_sections = {
			lualine_a = { "filename" },
			lualine_b = {},
			lualine_c = {},
			lualine_x = {},
			lualine_y = {},
			lualine_z = { "location" },
		},
		tabline = {},
		extensions = {},
	})
```
(If relevant, my full configs can be found here: https://github.com/Ttibsi/dotfiles-playbook/tree/master/templates/nvim)

**Comment by shadmansaleh** [comment]
Link StatusLine and StatusLineNC highlight groups to Normal

```lua
:hi! link StatusLine Normal
:hi! link StatusLineNC Normal
```

**Comment by Ttibsi** [comment]
Awesome, thank you!

**Comment by l00sed** [comment]
Hi @shadmansaleh, thanks for helping with this issue in the past. I'm Looking for some help with this too if anyone has any ideas. When I directly source my [lualine.lua](https://gist.github.com/l00sed/8cadeb747d24dea37f3e279ce18d8472) config file, it works and looks beautiful:
![image](https://user-images.githubusercontent.com/23065167/210109783-1b95d198-3e4b-41d9-811b-5a88c67630a4.png)

However, opening a file normally or opening an empty buffer without sourcing `luafile.lua` directly, I get the ugly square ends:
![image](https://user-images.githubusercontent.com/23065167/210109861-293f6fcc-96e6-4fb1-be66-728c7660812d.png)

Any ideas to help me debug further? I'm using a Neovim-specific gruvbox theme and I've tried messing with the loading order in packer, but I'm struggling to figure this out. The recommended highlight fix in this thread does not appear to have any effect. :(

**Comment by giusgad** [comment]
I had the same problem @l00sed, and linking `StatusLine` to `Normal` worked for me.

Before I found this tread, I found the issue was related to the following highlight groups:
- `lualine_transitional_lualine_a_command_to_statusline`
- `lualine_transitional_lualine_a_insert_to_statusline`
- `lualine_transitional_lualine_a_normal_to_statusline`

You could try changing the background value for those, or I guess you could check your `Normal` highlight group if you linked it and it still doesn't work.

**Comment by l00sed** [comment]
Hi @giusgad, thanks for posting a response, hope this helps others. I had found these highlight groups myself too and that seemed to fix the issue. I still ended up giving up on the bubble look because my 1080p monitor mangles the rounded Powerline glyphs. Maybe I'll revisit if I ever get a higher DPI monitor :/

**Comment by ArtemChandragupta** [comment]
> Link StatusLine and StatusLineNC highlight groups to Normal
> 
> ```viml
> :hi! link StatusLine Normal
> :hi! link StatusLineNC Normal
> ```

Hi! I am new to neovim (NixVim distribution) and have this issue. Can you say me more about this lines? What are they do? Where should I write them?

**Comment by arejula27** [comment]
![image](https://github.com/nvim-lualine/lualine.nvim/assets/46299278/0866c261-a9e0-4afb-94c5-ccc1df7c9eaa)
I have a similar problem, however doesn't work for me linking. I am using alacrity on fedora

**Comment by Edgar-P-yan** [comment]
@ArtemChandragupta I had to place these commands in the configuration files:
```lua
vim.cmd [[
  highlight! link StatusLine Normal
  highlight! link StatusLineNC Normal
]]
```
Where you should put this is either in the `nvim/init.lua` or the file where you usually put your global configs.
