### ISSUE TITLE
Feat: Command-line editing within status bar

### ISSUE THREAD

**Issue by nosvagor** [nvim-lualine/lualine.nvim#870]
### Requested feature

```Command-line mode is used to enter Ex commands (":"), search patterns("/" and "?"), and filter commands ("!").```

Could this be made into a component within lualine? 

### Motivation

One can set `cmdheight=0` to hide command line when not in use, and I would like this, but I don't like how the cmdline replaces the status (lualine). 

I tried to find some other implementations of this, looked through requested features (even of other status lines) and I couldn't find any discussion about such idea. 

I could be just completely missing an option to allow the cmdline to pop-up below the status line... but why not integrate it directly? I have a big gap in the middle of my status bar that could optionally show a cmd-line input box, and I'm assuming others might too. 

Furthermore, I suspect this might be hard to implement, and possibly slow things down. But, I'm curious if it is a reasonable request, or something I (naively) could maybe try to do.

**Comment by quantum-booty** [comment]
checkout https://github.com/folke/noice.nvim

**Comment by nosvagor** [comment]
> checkout https://github.com/folke/noice.nvim
> It doesn't implement the cmdline inside the statusline, however it moves it to the middle of your screen, and has statusline components so you could pipes the message into lualine.

Probably a better solution to my problem; definitely checking this out.
