### ISSUE TITLE
Bug: Strange error when scrolling through a line containing substring `['%']`?

### ISSUE THREAD

**Issue by nyngwang** [nvim-lualine/lualine.nvim#873]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

1. You will need to create a lua file, with lua LSP Client sumneko/lua-language-server attached.
2. The lua file should contain a lua table like this:
    ```lua
    window = {
      mappings = {
        -- root behaviour.
        ['-'] = 'navigate_up',
        ['<C-]>'] = 'set_root',
    
        -- tree itself.
        ['R'] = 'refresh',
    
        -- open files.
        ['<2-LeftMouse>'] = 'shift_M_open',
        ['<cr>'] = 'shift_M_open',
        ['w'] = 'picker_open',
        ['o'] = 'macOS_open',
        ['%'] = 'open_vsplit', -- THIS LINE TO BE SPECIFIC
      }
    }
    ```
3. Move your cursor upward until it is located at the line containing the substring `['%']`.

### Expected behaviour
Do nothing.

### Actual behaviour
An error occurred:

```
Error executing vim.schedule lua callback: ...acker/start/lualine.nvim/lua/lualine/utils/nvim_opts.lua:77: E539: Illegal character <'>
stack traceback:
        [C]: in function 'nvim_win_set_option'
        ...acker/start/lualine.nvim/lua/lualine/utils/nvim_opts.lua:77: in function 'setter_fn'
        ...acker/start/lualine.nvim/lua/lualine/utils/nvim_opts.lua:50: in function 'set_opt'
        ...acker/start/lualine.nvim/lua/lualine/utils/nvim_opts.lua:74: in function 'set'
        ...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:422: in function 'refresh'
        ...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:343: in function <...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:342>
Press ENTER or type command to continue
```

### Minimal config to reproduce the issue

```lua
use {
  'nvim-lualine/lualine.nvim',
  requires = {
    'kyazdani42/nvim-web-devicons',
    {
      'SmiteshP/nvim-navic',
      requires = 'neovim/nvim-lspconfig',
      config = function () require('nvim-navic').setup{ separator = '  ' } end
    }
  },
  config = function ()
    local navic = require('nvim-navic')
    require('lualine').setup {
      options = {
        theme = 'palenight', -- Purple
      },
      sections = {
        lualine_c = { 'filename', { navic.get_location, cond = navic.is_available } },
        lualine_x = { 'encoding', 'filetype' },
      }
    }
  end
}
```

### Aditional information

Reasoning: I guess the char `%` might have a special meaning to the next char that follow, thus causing the error. E.g. it escapes the single quote `'`.

<img src="https://user-images.githubusercontent.com/24765272/196693073-aa45ea37-ce5e-48be-80f5-3fc52b148e88.png" width="500">

and if you look closely, you will also find that the left-curly-braces, i.e. `{`s, showing in the image is bolded: (ignoring the cat which is from another desktop program.)

<img src="https://user-images.githubusercontent.com/24765272/196697501-e4bd2704-5615-4905-a5c0-07726d631dab.png" width="1200">

**Comment by shadmansaleh** [comment]
It's because of nvim-navic it needs to escape % in it's output as they have special meaning in statusline.

**Comment by nyngwang** [comment]
@shadmansaleh Thanks for the explanation, let me report it there. Closing.
