### ISSUE TITLE
Feat: paste mode

### ISSUE THREAD

**Issue by gsaple** [nvim-lualine/lualine.nvim#889]
#### description

Hi, can we please have the paste mode after pressing `:set paste`?
Following is a screen shot from [lightline](https://github.com/itchyny/lightline.vim).
![1](https://user-images.githubusercontent.com/108666441/201565469-94af8c49-abcb-4ecd-8482-93ceb280c6c9.png)

Following is another one from (neo)vim with no plugin at all.
![2](https://user-images.githubusercontent.com/108666441/201565832-c9c49f64-4dc3-47bf-a643-9b41772cfa28.png)

#### reason
It seems necessary to indicate when pasting code without auto-indent.

Thank you!

**Comment by shadmansaleh** [comment]
duplicate https://github.com/nvim-lualine/lualine.nvim/issues/325

If you still want it you can easily make a custom component for it. or even just use the fmt option on mode component like following.

```lua
require'lualine'.setup {
sections = {
  lualine_a = {
    { 'mode', fmt = function(mode) return vim.go.paste == true and mode .. ' (paste)' or mode end },
  },
}
```
