### ISSUE TITLE
Bug: All tab names have prefix "fugitive: " if current buffer is fugitive status buffer even if other tabs is not fugitive status buffer.

### ISSUE THREAD

**Issue by mars90226** [nvim-lualine/lualine.nvim#901]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

1. Use `:cd` to change directory to a git repo.
2. Open any file in the git repo in new tab.
3. Open fugitive status buffer with `:Git`.

### Expected behaviour
Only current tab should have the prefix "fugitive: ".

### Actual behaviour
All tabs have the prefix "fugitive: ".

### Minimal config to reproduce the issue

```
call plug#begin("/root/lualine_fugitive/.local/share/nvim/plugged")
" Your plugins go here like
Plug 'nvim-lualine/lualine.nvim'
Plug 'tpope/vim-fugitive'


call plug#end()

" Your Viml part of config goes here
" colorscheme onedark


lua << END
-- Your lua part of config goes here
require'lualine'.setup {
  tabline = {
    lualine_a = {
      {
        "tabs",
        max_length = vim.o.columns / 3,
        mode = 2,
      },
    },
    lualine_b = {},
    lualine_c = {},
    lualine_x = {},
    lualine_y = {},
    lualine_z = {},
  },
}


END

" Instructions:
" -------------------------------------------------------------
" Load this config with nvim_isolated_conf.sh -l /root/lualine_fugitive
" Remember to run :PlugInstall after changing plugin section
" Also delete the comments before putting this file on issue
" That will reduce noise
" You can delete /root/lualine_fugitive once you're done
```

### Aditional information
The fix for #900 check the `filetype` in current buffer. But it should check the `filetype` of the `bufnr` buffer.

**Comment by shadmansaleh** [comment]
If you already know why the issue is happening prs are welcome. At least you did follow the issue templates thanks for that. Otherwise, you probably would have to wait for quite a while before I took a look at it.

**Comment by mars90226** [comment]
For #900, I'm not sure how you gonna fix it. But for this bug, I think I should probably send the PR. Anyway, thank you for the quick fix!
