### ISSUE TITLE
Bug: g:coc_status conflict disabled_filetypes 

### ISSUE THREAD

**Issue by codebysandwich** [nvim-lualine/lualine.nvim#906]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

disabled_filetypes = { "dashboard", "NvimTree"}
lualine_c = {{'g:coc_status', color={fg='#97C379', gui='bold'}},}

### Expected behaviour
NvimTree no statusline

### Actual behaviour
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/32191093/205111484-6f9539de-79a0-4c2d-a666-c6eeee2cb112.png">

### Minimal config to reproduce the issue
disabled_filetypes = { "dashboard", "NvimTree"}
lualine_c = {{'g:coc_status', color={fg='#97C379', gui='bold'}},}

### Aditional information
neovim version: 0.8.0

**Comment by codebysandwich** [comment]
neovim version: 0.8.0

**Comment by shadmansaleh** [comment]
It's not lualine. If I remember correctly coc.nvim has a feature where it just places coc status in statusline. When  you set a filetype as disabed. lualine doesn't touch statusline of that window. If some other plugin is changing the statusline that's not a lualine issue.

**Comment by codebysandwich** [comment]
> 

thanks your answer, i removed `set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')} `in my init.vim, that's OK. I will add this feature with lualine! thanks :)

**Comment by codebysandwich** [comment]
i use `lualine_c = { {"%{coc#status()} %{get(b:,'coc_current_function','')}", color={fg='#97C379', gui='bold'}}, }` add `coc_status` and `current function` in lualine, thanks the plugin! its faster than airline :)
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/32191093/205225457-fb674667-d3b2-4d0f-80e0-a80b36efe34c.png">
