### ISSUE TITLE
Bug: exponent symbols showing up when using with `NvimTree` with certain themes.

### ISSUE THREAD

**Issue by ChrisMGeo** [nvim-lualine/lualine.nvim#907]
### Self Checks

- [x] I'm using the latest lualine.
- [ ] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

My setup uses `LunarVim`, which comes with `NvimTree` and `LuaLine` by default. Use a theme like `techtuner/aura-neovim`, and open `NvimTree` using `<leader> + e`

### Expected behaviour
No exponent symbols should show up when using certain themes.

### Actual behaviour
Exponent symbols show up in the `c` (`x` too?) section of the line.

### Aditional information

Pictures as proof:
Normal:
![image](https://user-images.githubusercontent.com/44679968/206047782-b6743b87-7ca8-4625-adc9-566b65146356.png)

While `NvimTree` is open:
![image](https://user-images.githubusercontent.com/44679968/206047863-1b4bc82b-b212-4705-8666-495094fa25b9.png)

**Comment by shadmansaleh** [comment]
upstream: https://github.com/neovim/neovim/issues/19803

duplicate: https://github.com/nvim-lualine/lualine.nvim/issues/850
