### ISSUE TITLE
Feat: Add catppuccin theme

### ISSUE THREAD

**Issue by arijit79** [nvim-lualine/lualine.nvim#908]
### Requested feature
Add [catppuccin](https://github.com/catppuccin) theme by default.
### Motivation
This theme has gone quite trendy these days and rather than everyone copying the theme for their lualine configuration, we should add it as a default option.

I seriously wanted to help by filing a PR but I am quite busy these days :-(

**Comment by shadmansaleh** [comment]
If you install the catppuccin colorschem you should already have the lualine theme since the colorscheme supports lualine. I don't see why you'd need to copy it to your config.

**Comment by arijit79** [comment]
I understand that. I think that the look that I get for lualine is the one that catppuccin goes with. Actually it looked a bit odd so I opened an issue. But now I get that that's what it is. Closing off the issue
