### ISSUE TITLE
Bug: setup error, This function expects a maximum of 0 argument(s) but instead it is receiving 1.

### ISSUE THREAD

**Issue by akahanaton** [nvim-lualine/lualine.nvim#910]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Adding this lines into Lunarvim's config file config.lua:
```
require('lualine').setup {
  options = { theme = 'slanted-gaps' }
}

```
### Actual behaviour
`This function expects a maximum of 0 argument(s) but instead it is receiving 1.`

### Minimal config to reproduce the issue
```
require('lualine').setup {
  options = { theme = 'slanted-gaps' }
}

```

**Comment by akahanaton** [comment]
nerver mind, I found the problem

**Comment by ibeex** [comment]
> nerver mind, I found the problem

what was the problem?
