### ISSUE TITLE
Bug: bug report template contains typos

### ISSUE THREAD

**Issue by ZyX-II** [nvim-lualine/lualine.nvim#922]
List of typos found in the template below:

- `placeing` → `placing`.
- `exsisting` → `existing`.
- `prs` → `PRs`.
- `IMPORTENT` → `IMPORTANT`.

### Self Checks

- [ ] I'm using the latest lualine.
- [ ] I didn't find the issue in exsisting issues or prs.

**Comment by shadmansaleh** [comment]
Thanks. Sorry about that.
