### ISSUE TITLE
Feat: Support for %S showcmd statusline component 

### ISSUE THREAD

**Issue by aloknigam247** [nvim-lualine/lualine.nvim#949]
### Requested feature

Neovim added a statusline component to show showcmd in lualine using %S in statusline. See neovim help below
https://neovim.io/doc/user/options.html#'showcmdloc'

Lualine does not support %S and reports error when try to use it.
Looking at the code, it looks like lualine uses %S for some internal usage.

This feature requests to provide support for %S statusline component in lualine.

**Comment by telbizov** [comment]
+1 for the feature request

I am looking for a way to display the exact same information that `showcmd` shows in lualine itself. For example when in visual block mode it shows `6x3` etc

**Comment by aloknigam247** [comment]
Thanks @shadmansaleh

**Comment by jdhao** [comment]
It seems that we also need to set option `showcmdloc` to `statusline` to use `%S` component in lualine:

```
vim.o.showcmdloc = "statusline"
```

without above, the `%S` component does not work.
