### ISSUE TITLE
Quastion about filename

### ISSUE THREAD

**Issue by lanox** [nvim-lualine/lualine.nvim#969]
Hi, 

I am not sure if this exists already, but I was wondering if there is a way to set the filename to show the dir + file name?

e.g
If you are in this dir `/code/project1/`

and you open main.go from within the `project1` I would like  lualine to show `project1/main.go`  

I have played with `path` from documentation but neither of the options does what I want.

thanks

**Comment by shadmansaleh** [comment]
it's not too hard to achieve this with fmt

```lua
    lualine_c = { {'filename', path = 2, fmt = function (path)
      return table.concat({vim.fs.basename(vim.fs.dirname(path)),
                           vim.fs.basename(path)}, package.config:sub(1, 1))
    end } },
````

**Comment by lanox** [comment]
thanks @shadmansaleh  it worked great.
