### ISSUE TITLE
Doesn't render characters without custom font on Windows

### ISSUE THREAD

**Issue by TrueBers** [nvim-lualine/lualine.nvim#974]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in existing issues or PRs.

### How to reproduce the problem

Install latest neovim on Windows 11 10.0.22621 using
`choco install neovim`

add plugin with Packer
`use 'nvim-lualine/lualine.nvim'`

Disable icons with
```lua
options = {
    icons_enabled = false,
},
```

Install `Windows Terminal` from Microsoft Store.

Run nvim in Windows Terminal.

### Expected behaviour
It seems all symbols in the line should be rendered.

### Actual behaviour
Many Tofu symbols instead of proper ones.
![image](https://user-images.githubusercontent.com/1314261/219526718-15035c84-e9b6-4ae6-bc00-e03951a82062.png)

### Minimal config to reproduce the issue
```lua
use 'nvim-lualine/lualine.nvim'

local lualine = require('lualine')
lualine.setup {
  options = {
    icons_enabled = false,
  },
}
```

### Additional information
Readme states 
https://github.com/nvim-lualine/lualine.nvim/blob/e99d733e0213ceb8f548ae6551b04ae32e590c80/README.md#L88
But is seems, you still have to have an additional font to render the line properly even if you have disabled icons.

**Comment by shadmansaleh** [comment]
turn off the section separators too. default ones require nerd fonts

```lua
 options = {
    icons_enabled = false,
    component_separators = '|',
    section_separators = '',
  }
```
