### ISSUE TITLE
Bug: Weird character '^' 

### ISSUE THREAD

**Issue by niksingh710** [nvim-lualine/lualine.nvim#978]
### Self Checks

- [ x ] I'm using the latest lualine.
- [ x ] I didn't find the issue in existing issues or PRs.

### How to reproduce the problem

use pywal theme for lualine.
![image](https://user-images.githubusercontent.com/60490474/220256942-feaedd16-c41b-45f2-bd77-b0c6e98a5f7d.png)
and if any floating window comes e.g notify.nvim or glow markdown previewer or  hover window.
i get this ^ character in my lualine.
### Expected behaviour
lualine mid should be clean

**Comment by uZer** [comment]
Hi, I'm currently trying to improve the pywal.nvim theme [in a fork](https://github.com/uZer/pywal.nvim), adding background transparency and better color management. The original project has been archived, so I guess it won't get maintained anymore. I'm just building this fork for my own usage at the moment.

I can reproduce this, and am trying to deal with it too.

If this issue is related to a specific highlight color (which I'm not sure), does anyone know what is the highlight name of this special char?

**Comment by niksingh710** [comment]
> Hi, I'm currently trying to improve the pywal.nvim theme [in a fork](https://github.com/uZer/pywal.nvim), adding background transparency and better color management. The original project has been archived, so I guess it won't get maintained anymore. I'm just building this fork for my own usage at the moment.
> 
> I can reproduce this, and am trying to deal with it too.
> 
> I don't think this issue is related to a specific highlight color nor the pywal theme.

Will try the fork.
I am also re building my config fro scratch as this is what m facing in lunarvim if that comes in my new config too will report.

**Comment by niksingh710** [comment]
> Hi, I'm currently trying to improve the pywal.nvim theme [in a fork](https://github.com/uZer/pywal.nvim), adding background transparency and better color management. The original project has been archived, so I guess it won't get maintained anymore. I'm just building this fork for my own usage at the moment.
> 
> I can reproduce this `^` issue, and am trying to deal with it too.
> 
> I don't think it is related to a specific highlight color nor the pywal theme.

i can make sure that this comes when using pywal.nvim only.
same on the fork too.

**Comment by shadmansaleh** [comment]
Upstream bug. I've said it so many times. there are a ton of duplicates of this issue in the bug tracker.

**Comment by titaniumtraveler** [comment]
Just writing this here in case someone else gets this issue:

It seems the solution is to just remove the highlights `StatusLine` and `StatusLineNC` from your colorscheme.

**Comment by uZer** [comment]
Hi,

This PR has just been merged:
https://github.com/neovim/neovim/pull/25267
