### ISSUE TITLE
Overwrite filetype icon color

### ISSUE THREAD

**Issue by Maritsu** [nvim-lualine/lualine.nvim#980]
I'm making a config based on [evil_lualine](https://github.com/nvim-lualine/lualine.nvim/blob/master/examples/evil_lualine.lua), and wanted to include an icon for the `filetype` component. I've set the `fg` color and enabled icons for it. However, the filetype icon seems to be colored independently from the text. **How would I be able to make the icon a specific, constant color (preferably, same as the icon)**
Examples of the icon being a different color from the text:
![help](https://user-images.githubusercontent.com/66056347/221421322-cfe1db39-df51-495b-9d49-b6220fa62a40.png) ![cpp header file](https://user-images.githubusercontent.com/66056347/221421373-588b3601-fd86-4268-96f1-9213ed8c6991.png) ![cpp source file](https://user-images.githubusercontent.com/66056347/221421386-e3b6cf38-8f8d-4471-96a1-17382225de09.png) ![cmake](https://user-images.githubusercontent.com/66056347/221421396-2260c682-e3e9-41b9-ac34-1946fb3114a2.png) ![html](https://user-images.githubusercontent.com/66056347/221421425-fd4b1253-95d2-45dc-b755-cb512c8b1bba.png) ![markdown](https://user-images.githubusercontent.com/66056347/221421445-85073dc2-0b22-4c1d-9e6a-6d73d91d4b93.png) ![sh](https://user-images.githubusercontent.com/66056347/221421483-4018413b-37aa-413d-a53d-1870b5aad1ae.png)  
etc.

Snippet from the config:
```lua
ins_right {
	'filetype',
	color = { fg = col.blue, gui = 'bold' },
}
```
where `col.blue` is already defined as #89B4FA, and `ins_right` is defined the same as in [evil_lualine](https://github.com/nvim-lualine/lualine.nvim/blob/master/examples/evil_lualine.lua#L77).

**Comment by CraigglesO** [comment]
This is old but for other people:
lualine depends upon `nvim-web-devicons` so you actually edit that package:

```lua
local DevIcons = require("nvim-web-devicons")
DevIcons.set_icon {
  zig = {
    icon = "",
    color = "#f7a41d",
    cterm_color = "65",
    name = "Zig"
  },
  v = {
    icon = "",
    color = "#4b6b88",
    cterm_color = "65",
    name = "V"
  }
}

```

I'm not bothering updating the cterm_color for these, but you get the idea.

**Comment by Maritsu** [comment]
Ah, so in that case I should change the filetype icons for all langs. Tyvm!
