### ISSUE TITLE
How does one hide the platform icon (Windows/Linux/Mac) on the right? 

### ISSUE THREAD

**Issue by caldwell-63** [nvim-lualine/lualine.nvim#984]
- [x] I'm using the latest lualine.
- [x] I didn't find the issue in existing issues or PRs.

I use default sections:

```lua
  sections = {
    lualine_a = { 'mode' },
    lualine_b = { 'branch', 'diff', 'diagnostics' },
    lualine_c = { 'filename' },
    lualine_x = { 'encoding', 'fileformat', 'filetype' },
    lualine_y = { 'progress' },
    lualine_z = { 'location' }
  },
```

I read about components but there's nothing about "platform", is this like a built-in?

**Comment by shadmansaleh** [comment]
It's now platform icon. It's showing the fileformat. remove that component from your config and you won't get it.
